server {
    listen 80;
    server_name _;

    root /srv;

    location /debian/ {
        autoindex on;
        try_files $uri =404;
    }

    location /debian-security/ {
        autoindex on;
        try_files $uri =404;
    }

    location /dairyos/ {
        autoindex on;
        try_files $uri =404;
    }

    location /dairyos-pxe/ {
        autoindex on;
        try_files $uri =404;
    }
}
