import React, { useEffect, useMemo, useState } from 'react';
import { Activity, HeartPulse, Milk, Save, X } from 'lucide-react';
import { API_BASE_URL } from '../config/api';
import OperatorDataBlock from './OperatorDataBlock';
import { useFarmDateField } from '../utils/farmDate';

type AnimalData={id:string;category:string;breed:string;age:string;status:string;frequency:string;earTag:string;gender?:string;stage?:string};
type BackendAnimal={animal_id:string;animal_type?:string|null;animal_category?:string|null;legacy_animal_id?:string|null;ear_tag?:string|null;rfid?:string|null;breed?:string|null;sex?:string|null;date_of_birth?:string|null;date_of_acquisition?:string|null;dam_id?:string|null;sire_id?:string|null;lifecycle_status?:string|null;status?:string|null;milking_frequency?:string|null;is_currently_milking?:boolean;production_group?:string|null;location?:string|null;active?:boolean};
type Props={animalId:string;onClose:()=>void;onSave?:(animal:AnimalData)=>void;onOpenPassport?:(animalId:string)=>void};
const API_BASE=API_BASE_URL||'http://127.0.0.1:8000';
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#111827',border:'1px solid #334155',color:'#fff',padding:'9px',borderRadius:5,fontSize:12};
const btn=(bg:string):React.CSSProperties=>({background:bg,color:'#fff',border:0,borderRadius:5,padding:'8px 11px',fontSize:10,fontWeight:800,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:6});
const age=(value?:string|null)=>{if(!value)return 'Unknown';const d=new Date(value);if(Number.isNaN(d.getTime()))return 'Unknown';const now=new Date();let y=now.getFullYear()-d.getFullYear();if(now.getMonth()<d.getMonth()||(now.getMonth()===d.getMonth()&&now.getDate()<d.getDate()))y--;return y>0?`${y} Years`:`${Math.max(0,Math.floor((now.getTime()-d.getTime())/2592000000))} Months`};
const toUi=(a:BackendAnimal):AnimalData=>({id:a.animal_id,category:a.animal_category||'Unclassified',breed:a.breed||'Unknown',age:age(a.date_of_birth),status:a.status||(a.active===false?'INACTIVE':'ACTIVE'),frequency:a.milking_frequency||'NONE',earTag:a.ear_tag||a.animal_id,gender:(a.sex||'').toUpperCase()==='MALE'?'Male':'Female',stage:a.lifecycle_status||undefined});
function RecordBlock({value}:{value:any}):React.ReactNode{return <OperatorDataBlock value={value}/>}
function findSection(source:any,keys:string[]){for(const key of keys)if(source&&source[key]!==undefined)return source[key];return null}
function displayCell(value:any):string{if(value===null||value===undefined||value==='')return '—';if(typeof value==='boolean')return value?'Yes':'No';if(typeof value==='number')return value.toLocaleString('en-PK');return String(value).replace(/_/g,' ')}
function PassportTable({rows,columns,empty='No history recorded.'}:{rows:any[];columns:{key:string;label:string;render?:(row:any)=>React.ReactNode}[];empty?:string}){if(!rows.length)return <div style={muted}>{empty}</div>;return <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:10}}><thead><tr>{columns.map(column=><th key={column.key} style={th}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row?.record_id||row?.id||row?.animal_id||index)}>{columns.map(column=><td key={column.key} style={td}>{column.render?column.render(row):displayCell(row?.[column.key])}</td>)}</tr>)}</tbody></table></div>}
function lineageLink(row:any,onOpen?:(id:string)=>void){const id=String(row?.animal_id||'').trim();if(!id)return '—';return <button type="button" onClick={()=>onOpen?.(id)} style={{background:'transparent',border:0,padding:0,color:'#7dd3fc',fontWeight:900,cursor:onOpen?'pointer':'default'}}>{id}</button>}
function LineageView({lineage,onOpenPassport}:{lineage:any;onOpenPassport?:(id:string)=>void}){const parents=(Array.isArray(lineage?.parents)?lineage.parents:[]).map((item:any)=>({...item,generation:'Parent'}));const ancestors=(Array.isArray(lineage?.ancestors)?lineage.ancestors:[]).map((item:any)=>({...item,generation:`Ancestor ${item.depth||''}`.trim()}));const descendants=(Array.isArray(lineage?.descendants)?lineage.descendants:[]).map((item:any)=>({...item,generation:`Descendant ${item.depth||''}`.trim()}));const rows=[...parents,...ancestors,...descendants];return <div style={{display:'grid',gap:10}}><PassportTable rows={rows} empty="No lineage or pedigree links recorded." columns={[{key:'generation',label:'Generation'},{key:'relation',label:'Relation'},{key:'animal_id',label:'Animal ID',render:row=>lineageLink(row,onOpenPassport)},{key:'ear_tag',label:'Ear Tag'},{key:'sex',label:'Sex'},{key:'breed',label:'Breed'},{key:'lifecycle_status',label:'Life Stage'},{key:'status',label:'Status'}]}/><div style={muted}>Lineage integrity: {lineage?.integrity?.broken_parent_links?.length||0} broken parent link(s), {lineage?.integrity?.ancestor_cycles?.length||0} ancestor cycle(s), {lineage?.integrity?.descendant_cycles?.length||0} descendant cycle(s).</div></div>}

export default function AnimalPassportModal({animalId,onClose,onSave,onOpenPassport}:Props){
 const isNew=animalId==='NEW-ANIMAL';
 const [animal,setAnimal]=useState<BackendAnimal|null>(null),[passport,setPassport]=useState<any>(null),[exits,setExits]=useState<any[]>([]),[passportVaccinations,setPassportVaccinations]=useState<any[]>([]),[tab,setTab]=useState<'overview'|'milk'|'health'|'vaccination'|'breeding'|'lineage'|'exit'>('overview');
 const [availableDams,setAvailableDams]=useState<BackendAnimal[]>([]);
 const [loading,setLoading]=useState(!isNew),[saving,setSaving]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 const [form,setForm]=useState({category:'Milking',breed:'',birthDate:'',acquisitionDate:'',sire:'',dam:'',rfid:'',frequency:'TWICE_DAILY',legacyId:'',earTag:'',location:'',productionGroup:''});
 const [exitEffectiveDate,setExitEffectiveDate,resetExitEffectiveDateToToday]=useFarmDateField();
 const [exitForm,setExitForm]=useState({veterinarian:'',cause:'',notes:''});
 const load=async()=>{if(isNew)return;setLoading(true);setError('');try{const [a,p]=await Promise.all([fetch(`${API_BASE}/farm/animals/${encodeURIComponent(animalId)}`),fetch(`${API_BASE}/farm/animals/${encodeURIComponent(animalId)}/passport`)]);if(!a.ok)throw new Error(`Unable to load animal (${a.status})`);if(!p.ok)throw new Error(`Unable to load lifetime passport (${p.status})`);const animalData=await a.json() as BackendAnimal;const passportData=await p.json();setAnimal(animalData);setPassport(passportData);const safeFetch=async(url:string)=>{try{return await fetch(url)}catch{return null}};const [d,v]=await Promise.all([safeFetch(`${API_BASE}/farm/animals/${encodeURIComponent(animalId)}/disposition-history`),safeFetch(`${API_BASE}/farm/animals/${encodeURIComponent(animalId)}/vaccinations`)]);setExits(d?.ok?await d.json():[]);setPassportVaccinations(v?.ok?await v.json():[]);setForm({category:animalData.animal_category||'Unclassified',breed:animalData.breed||'',birthDate:animalData.date_of_birth||'',acquisitionDate:animalData.date_of_acquisition||'',sire:animalData.sire_id||'',dam:animalData.dam_id||'',rfid:animalData.rfid||'',frequency:animalData.milking_frequency||'TWICE_DAILY',legacyId:animalData.legacy_animal_id||'',earTag:animalData.ear_tag||'',location:animalData.location||'',productionGroup:animalData.production_group||''})}catch(e){setError(e instanceof Error?e.message:'Unable to load passport')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[animalId]);
 useEffect(()=>{const loadDams=async()=>{try{const response=await fetch(`${API_BASE}/farm/animals`);if(!response.ok)return;const body=await response.json();const rows=Array.isArray(body)?body:Array.isArray(body?.animals)?body.animals:[];setAvailableDams(rows.filter((item:BackendAnimal)=>String(item.sex||'').toUpperCase()==='FEMALE'&&item.active!==false&&item.animal_id!==animalId))}catch{setAvailableDams([])}};void loadDams()},[animalId]);
 const identity=findSection(passport,['identity','animal','animal_identity','profile'])||animal||{};const lineage=findSection(passport,['lineage','lineage_projection'])||{};const production=findSection(passport,['production','lactation','lifetime_production','milk_production'])||{};const health=findSection(passport,['health_state','health','health_cases','health_history'])||{};const healthObservations=health?.clinical_log||passport?.history?.health||[];const treatmentHistory=passport?.history?.treatments||[];const breeding=findSection(passport,['reproduction','breeding','reproductive_history'])||{};
 const title=useMemo(()=>isNew?'New Animal Comprehensive Passport':`Animal Passport — ${animal?.animal_id||animalId}`,[isNew,animal,animalId]);
 const isMilking=animal?.is_currently_milking===true||form.category==='Milking';
 const resolveCategory=async()=>{const response=await fetch(`${API_BASE}/farm/animals/classification?category=${encodeURIComponent(form.category)}`);const data=await response.json();if(!response.ok)throw new Error(data.detail||'Invalid animal category.');return data as {animal_category:string;lifecycle_status:string;sex:string};};
 const handleSave=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const classification=await resolveCategory();const payload={legacy_animal_id:form.legacyId||null,ear_tag:form.earTag||null,rfid:form.rfid||null,breed:form.breed||null,date_of_birth:form.birthDate||null,date_of_acquisition:form.acquisitionDate||null,sire_id:form.sire||null,dam_id:form.dam||null,lifecycle_status:classification.lifecycle_status,sex:classification.sex,milking_frequency:classification.lifecycle_status==='LACTATING'?form.frequency:null,production_group:form.productionGroup||null,location:form.location||null,operator:'Operator UI'};const url=isNew?`${API_BASE}/farm/animals`:`${API_BASE}/farm/animals/${encodeURIComponent(animalId)}`;const response=await fetch(url,{method:isNew?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(isNew?{...payload,animal_type:'CATTLE'}:payload)});if(!response.ok)throw new Error((await response.text())||`Unable to save animal (${response.status})`);const savedAnimal=await response.json() as BackendAnimal;setAnimal(savedAnimal);setSaved(true);onSave?.(toUi(savedAnimal));if(isNew)setTimeout(onClose,900);else await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save animal')}finally{setSaving(false)}};
 const recordExit=async(e:React.FormEvent)=>{e.preventDefault();if(isNew)return;setSaving(true);setError('');try{const response=await fetch(`${API_BASE}/farm/animals/${encodeURIComponent(animalId)}/disposition`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({disposition:'DECEASED',effective_date:exitEffectiveDate,veterinarian:exitForm.veterinarian||null,cause:exitForm.cause||null,notes:exitForm.notes||null,operator:'Operator UI'})});if(!response.ok)throw new Error((await response.text())||`Unable to record exit (${response.status})`);const result=await response.json();setAnimal(result.animal);setSaved(true);onSave?.(toUi(result.animal));await load()}catch(e){setError(e instanceof Error?e.message:'Unable to record animal exit')}finally{setSaving(false)}};
 const tabs=[['overview','Identity & Status'],['milk','Milk & Production'],['health','Clinical Health'],['vaccination','Vaccination'],['breeding','Reproduction'],['lineage','Lineage & Pedigree'],['exit','Final Disposal']];
 return <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.78)',zIndex:10000,display:'flex',alignItems:'center',justifyContent:'center',padding:12}}><div style={{background:'#0f172a',width:'min(1180px,100%)',height:'min(92vh,900px)',borderRadius:9,border:'1px solid #334155',display:'flex',flexDirection:'column',overflow:'hidden',boxShadow:'0 25px 50px rgba(0,0,0,.6)'}}>
  <div style={{padding:'14px 18px',background:'#111827',borderBottom:'1px solid #1f2937',display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><div style={{fontSize:9,color:'#38bdf8',fontWeight:800,textTransform:'uppercase'}}>Lifetime biological record</div><div style={{fontSize:17,fontWeight:900}}>{title}</div><div style={{fontSize:10,color:'#94a3b8',marginTop:2}}>Identity, lineage, production summaries, reproduction, clinical history and exit outcomes remain linked to one permanent Animal ID.</div></div><button aria-label="Close Animal Passport" title="Close Animal Passport" onClick={onClose} style={{background:'transparent',border:0,color:'#94a3b8',cursor:'pointer'}}><X size={20}/></button></div>
  <div style={{display:'flex',gap:0,background:'#1e293b',borderBottom:'1px solid #334155',overflowX:'auto'}}>{tabs.map(([id,label])=><button key={id} onClick={()=>{if(id==='exit')resetExitEffectiveDateToToday();setTab(id as any)}} style={{background:'transparent',border:0,borderBottom:tab===id?'2px solid #38bdf8':'2px solid transparent',color:tab===id?'#38bdf8':'#cbd5e1',padding:'10px 12px',fontSize:10,fontWeight:800,whiteSpace:'nowrap',cursor:'pointer'}}>{label}</button>)}</div>
  <div style={{flex:1,minHeight:0,overflowY:'auto',padding:14}}>{loading&&<div style={notice}>Loading authoritative lifetime passport…</div>}{saved&&<div style={{...notice,background:'#064e3b',color:'#6ee7b7'}}>Persistent animal record updated.</div>}{error&&<div style={{...notice,background:'#450a0a',color:'#fca5a5',borderColor:'#7f1d1d'}}>{error}</div>}
   {!isNew&&tab==='overview'&&<Section title="Identity & Current Biological Status"><RecordBlock value={identity}/></Section>}
   {tab==='overview'&&isNew&&<form onSubmit={handleSave}><Section title="Identity & Registration"><ProfileForm form={form} setForm={setForm} isNew={true} generatedId={animal?.animal_id} availableDams={availableDams}/></Section><div style={{display:'flex',justifyContent:'flex-end',marginTop:11}}><button disabled={saving} type="submit" style={btn('#0284c7')}><Save size={12}/> {saving?'Saving…':'Create Permanent Animal Record'}</button></div></form>}
   {!isNew&&tab==='overview'&&<form onSubmit={handleSave} style={{marginTop:10}}><Section title="Editable Master Profile"><ProfileForm form={form} setForm={setForm} generatedId={animal?.animal_id} availableDams={availableDams}/><div style={{display:'flex',justifyContent:'flex-end',marginTop:10}}><button disabled={saving} type="submit" style={btn('#0284c7')}><Save size={12}/> {saving?'Saving…':'Save Profile'}</button></div></Section></form>}
   {!isNew&&tab==='milk'&&<div style={{display:'grid',gap:10}}><Section title="Production Summary"><RecordBlock value={production?.lifetime||production?.summary||{}}/></Section><Section title="Lactation History"><PassportTable rows={Array.isArray(production?.lactations)?production.lactations:[]} empty="No lactation history recorded." columns={[{key:'lactation_number',label:'Lactation'},{key:'calving_date',label:'Calving Date'},{key:'status',label:'Status'},{key:'days_in_lactation',label:'Days in Lactation'},{key:'milk_liters',label:'Total Milk (L)'},{key:'average_liters_per_recorded_day',label:'Avg / Recorded Day (L)'},{key:'peak_daily_yield_liters',label:'Peak Daily Yield (L)'},{key:'peak_daily_yield_date',label:'Peak Date'}]}/></Section><Section title="Monthly Production"><PassportTable rows={Array.isArray(production?.monthly_output)?production.monthly_output:[]} empty="No monthly production summary available." columns={[{key:'month',label:'Month'},{key:'milk_liters',label:'Milk (L)'},{key:'recorded_days',label:'Recorded Days'},{key:'average_liters_per_recorded_day',label:'Avg / Recorded Day (L)'},{key:'peak_daily_yield_liters',label:'Peak Daily Yield (L)'},{key:'peak_daily_yield_date',label:'Peak Date'}]}/></Section><div style={muted}>Detailed daily and milking-session entries remain in the Milk module; the Passport retains meaningful animal-level production summaries.</div></div>}
   {!isNew&&tab==='health'&&<div style={{display:'grid',gap:10}}><Section title="Current Clinical Status"><RecordBlock value={health?.summary||{}}/></Section><Section title="Clinical History"><PassportTable rows={Array.isArray(healthObservations)?healthObservations:[]} columns={[{key:'event_date',label:'Date'},{key:'event_type',label:'Event'},{key:'detail',label:'Clinical Detail'},{key:'severity',label:'Severity'},{key:'status',label:'Status'},{key:'medicine',label:'Medicine'}]}/></Section><Section title="Treatment History"><PassportTable rows={Array.isArray(treatmentHistory)?treatmentHistory:[]} columns={[{key:'treated_at',label:'Date / Time'},{key:'diagnosis',label:'Diagnosis'},{key:'medicine',label:'Medicine'},{key:'dose',label:'Dose'},{key:'milk_withdrawal_until',label:'Withdrawal Until'},{key:'veterinarian',label:'Veterinarian'}]}/></Section></div>}
   {!isNew&&tab==='vaccination'&&<Section title="Vaccination History"><PassportTable rows={passportVaccinations} empty="No vaccination history recorded." columns={[{key:'administered_date',label:'Administered'},{key:'vaccine',label:'Vaccine'},{key:'dose',label:'Dose'},{key:'veterinarian',label:'Veterinarian'},{key:'next_due_date',label:'Next Due'},{key:'notes',label:'Notes'}]}/></Section>}
   {!isNew&&tab==='breeding'&&<div style={{display:'grid',gap:10}}><Section title="Current Reproductive Status"><RecordBlock value={breeding?.current||{}}/></Section><Section title="Reproductive History"><PassportTable rows={Array.isArray(breeding?.lifetime_events)?breeding.lifetime_events:[]} empty="No reproductive history recorded." columns={[{key:'event_date',label:'Date'},{key:'event_type',label:'Event'},{key:'result',label:'Result'},{key:'technician',label:'Technician'}]}/></Section></div>}
   {!isNew&&tab==='lineage'&&<Section title="Lineage & Pedigree — Parents, Ancestors & Offspring"><LineageView lineage={lineage} onOpenPassport={onOpenPassport}/></Section>}
   {!isNew&&tab==='exit'&&<div style={{display:'grid',gap:12}}><Section title="Record Mortality"><form onSubmit={recordExit}><div style={grid2}><Field label="Date of Mortality"><input required type="date" value={exitEffectiveDate} onChange={e=>setExitEffectiveDate(e.target.value)} style={input}/></Field><Field label="Cause of Mortality"><input required value={exitForm.cause} onChange={e=>setExitForm({...exitForm,cause:e.target.value})} style={input}/></Field><Field label="Veterinarian / Responsible Person"><input value={exitForm.veterinarian} onChange={e=>setExitForm({...exitForm,veterinarian:e.target.value})} style={input}/></Field><Field label="Notes"><textarea value={exitForm.notes} onChange={e=>setExitForm({...exitForm,notes:e.target.value})} style={{...input,minHeight:70}}/></Field></div><div style={{marginTop:9,fontSize:10,color:'#f59e0b'}}>Recording mortality permanently marks this animal as deceased and removes it from active herd strength. The Animal Passport and all historical records remain preserved.</div><div style={{display:'flex',justifyContent:'flex-end',marginTop:10}}><button disabled={saving} type="submit" style={btn('#b91c1c')}>{saving?'Recording…':'Record Mortality'}</button></div></form></Section><Section title="Mortality History"><PassportTable rows={exits.filter((item:any)=>String(item?.disposition||'').toUpperCase()==='DECEASED')} empty="No mortality has been recorded for this animal." columns={[{key:'effective_date',label:'Date of Mortality'},{key:'cause',label:'Cause of Mortality'},{key:'veterinarian',label:'Veterinarian / Responsible Person'},{key:'notes',label:'Notes'}]}/></Section></div>}
  </div>
 </div></div>
}

function ProfileForm({form,setForm,isNew=false,generatedId,availableDams=[]}:{form:any;setForm:(v:any)=>void;isNew?:boolean;generatedId?:string;availableDams?:BackendAnimal[]}){const milking=form.category==='Milking';const calf=form.category==='Female Calf'||form.category==='Male Calf';const setCategory=(category:string)=>setForm({...form,category,frequency:category==='Milking'?(form.frequency||'TWICE_DAILY'):'',dam:(category==='Female Calf'||category==='Male Calf')?form.dam:''});return <div style={grid2}>
 <Field label="Permanent DairyOS Animal ID"><input value={generatedId||'Will be generated automatically by DairyOS'} readOnly disabled style={{...input,color:generatedId?'#6ee7b7':'#94a3b8',fontWeight:800}}/></Field>
 <Field label="Legacy ID (optional)"><input value={form.legacyId} placeholder="Prior or external identifier; does not replace the permanent DairyOS ID" onChange={e=>setForm({...form,legacyId:e.target.value})} style={input}/></Field>
 <Field label="Ear Tag"><input value={form.earTag} placeholder="Physical ear tag, if different" onChange={e=>setForm({...form,earTag:e.target.value})} style={input}/></Field>
 <Field label="Category"><select value={form.category} onChange={e=>setCategory(e.target.value)} style={input}><option>Milking</option><option>Dry</option><option>Heifer</option><option>Female Calf</option><option>Male Calf</option><option>Bull</option></select></Field>
 <Field label="Breed"><input value={form.breed} onChange={e=>setForm({...form,breed:e.target.value})} style={input}/></Field>
 <Field label="RFID"><input value={form.rfid} onChange={e=>setForm({...form,rfid:e.target.value})} style={input}/></Field>
 <Field label="Date of Birth"><input type="date" value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})} style={input}/></Field>
 <Field label="Date of Acquisition"><input type="date" value={form.acquisitionDate} onChange={e=>setForm({...form,acquisitionDate:e.target.value})} style={input}/></Field>
 <Field label="Sire ID"><input value={form.sire} onChange={e=>setForm({...form,sire:e.target.value})} style={input}/></Field>
 <Field label={calf?'Mother / Dam ID':'Dam ID'}>{calf?<select value={form.dam} required onChange={e=>setForm({...form,dam:e.target.value})} style={input}><option value="">Select mother from Animal Register</option>{availableDams.map(dam=><option key={dam.animal_id} value={dam.animal_id}>{dam.animal_id} · {dam.breed||'Breed not recorded'} · {dam.lifecycle_status||dam.status||'Female'}</option>)}</select>:<input value={form.dam} placeholder="Optional dam Animal ID" onChange={e=>setForm({...form,dam:e.target.value})} style={input}/>}</Field>
 {milking&&<Field label="Milking Frequency"><select value={form.frequency||'TWICE_DAILY'} onChange={e=>setForm({...form,frequency:e.target.value})} style={input}><option value="TWICE_DAILY">TWICE DAILY</option><option value="THRICE_DAILY">THRICE DAILY</option></select></Field>}
 <Field label="Location"><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} style={input}/></Field>
 <Field label="Production Group"><input value={form.productionGroup} onChange={e=>setForm({...form,productionGroup:e.target.value})} style={input}/></Field>
 {!milking&&<div style={{gridColumn:'1/-1',fontSize:9,color:'#64748b'}}>Milking Frequency is not applicable to {form.category} animals and is therefore not shown.</div>}
 </div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{fontSize:10,color:'#b6c2d2'}}><div style={{marginBottom:4,fontWeight:800}}>{label}</div>{children}</label>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section style={{background:'#111827',border:'1px solid #1f2937',borderRadius:7,padding:11,marginBottom:10}}><div style={{fontSize:12,fontWeight:900,marginBottom:8}}>{title}</div>{children}</section>}
const notice:React.CSSProperties={background:'#1e293b',border:'1px solid #334155',color:'#dbe4ee',padding:10,borderRadius:5,fontSize:10,marginBottom:9};
const grid2:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8};
const muted:React.CSSProperties={fontSize:10,color:'#64748b'};

const th:React.CSSProperties={textAlign:'left',color:'#94a3b8',fontWeight:900,padding:'7px 8px',borderBottom:'1px solid #334155',whiteSpace:'nowrap',background:'#0f172a'};
const td:React.CSSProperties={color:'#e2e8f0',padding:'7px 8px',borderBottom:'1px solid #1f2937',verticalAlign:'top',whiteSpace:'nowrap'};
