import React, { useMemo, useState } from 'react';
import { Activity, HeartPulse, Milk, Plus, Search, Users } from 'lucide-react';

type BackendAnimal={animal_id:string;ear_tag?:string|null;rfid?:string|null;breed?:string|null;sex?:string|null;date_of_birth?:string|null;lifecycle_status?:string|null;status?:string|null;milking_frequency?:string|null;active?:boolean;dam_id?:string|null;sire_id?:string|null;location?:string|null;production_group?:string|null};
type HerdCategory='Milking'|'Dry'|'Heifers'|'Female Calves'|'Male Calves'|'Bulls';
type Props={animals:BackendAnimal[];onOpenPassport:(id:string)=>void;onRegister:()=>void;onRefresh?:()=>void};
const categories:HerdCategory[]=['Milking','Dry','Heifers','Female Calves','Male Calves','Bulls'];
function category(a:BackendAnimal):HerdCategory{const l=(a.lifecycle_status||'').toUpperCase(),s=(a.sex||'').toUpperCase();if(l==='LACTATING')return 'Milking';if(l==='DRY')return 'Dry';if(l==='HEIFER'||l==='CLOSE_UP')return 'Heifers';if(l==='CALF')return s==='MALE'?'Male Calves':'Female Calves';return s==='MALE'?'Bulls':'Heifers'}
function age(v?:string|null){if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.getTime()))return '—';const now=new Date();let y=now.getFullYear()-d.getFullYear();if(now.getMonth()<d.getMonth()||(now.getMonth()===d.getMonth()&&now.getDate()<d.getDate()))y--;return y>0?`${y} yr${y===1?'':'s'}`:`${Math.max(0,Math.floor((now.getTime()-d.getTime())/2592000000))} mo`}
function active(a:BackendAnimal){return a.active!==false&&!['SOLD','DECEASED'].includes((a.lifecycle_status||'').toUpperCase())}

export default function AnimalTab({animals,onOpenPassport,onRegister}:Props){
 const [filter,setFilter]=useState<'ALL'|HerdCategory>('ALL'),[search,setSearch]=useState(''),[showExited,setShowExited]=useState(true);
 const activeAnimals=useMemo(()=>animals.filter(active),[animals]);
 const counts=useMemo(()=>({Total:activeAnimals.length,...Object.fromEntries(categories.map(c=>[c,activeAnimals.filter(a=>category(a)===c).length])) as Record<HerdCategory,number>}),[activeAnimals]);
 const rows=useMemo(()=>animals.filter(a=>{const q=search.trim().toLowerCase();const hay=[a.animal_id,a.ear_tag,a.rfid,a.breed,a.lifecycle_status,a.status,a.sex].map(v=>String(v??'').toLowerCase()).join(' ');const cat=category(a);const inFilter=filter==='ALL'||cat===filter;const exited=!active(a);return inFilter&&(!q||hay.includes(q))&&(showExited||!exited)}),[animals,filter,search,showExited]);
 return <div style={{padding:14,color:'#fff',height:'100%',boxSizing:'border-box',overflowY:'auto',overflowX:'hidden',minWidth:0}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap',marginBottom:10}}><div><div style={{fontSize:18,fontWeight:800,display:'flex',alignItems:'center',gap:7}}><Users size={18} color="#38bdf8"/> Animals</div><div style={{fontSize:10,color:'#94a3b8'}}>Complete herd register. Animal records remain visible after sale or mortality.</div></div><div style={{display:'flex',gap:6}}><button onClick={onRegister} style={{...btn,background:'#0284c7',color:'#fff',borderColor:'#0284c7'}}><Plus size={12}/> Register Animal</button></div></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(7,minmax(0,1fr))',gap:7,marginBottom:10}}><Stat label="Total Herd" value={counts.Total} active={filter==='ALL'} onClick={()=>setFilter('ALL')}/>{categories.map(c=><Stat key={c} label={c} value={counts[c]||0} active={filter===c} onClick={()=>setFilter(c)}/>)}</div>
  <div style={{display:'flex',gap:7,alignItems:'center',flexWrap:'wrap',background:'#111827',border:'1px solid #1f2937',borderRadius:7,padding:8,marginBottom:9}}><div style={{display:'flex',alignItems:'center',gap:5,flex:1,minWidth:220,background:'#1e293b',border:'1px solid #334155',borderRadius:5,padding:'6px 8px'}}><Search size={12} color="#94a3b8"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search Animal ID, tag, breed, RFID, status…" style={{background:'transparent',border:0,outline:0,color:'#fff',fontSize:10,width:'100%'}}/></div><label style={{fontSize:9,color:'#cbd5e1',display:'flex',alignItems:'center',gap:5}}><input type="checkbox" checked={showExited} onChange={e=>setShowExited(e.target.checked)}/> Include sold / mortality records</label><span style={{fontSize:9,color:'#64748b'}}>{rows.length} records</span></div>
  <div style={{background:'#111827',border:'1px solid #1f2937',borderRadius:7,overflow:'auto'}}><table style={{width:'100%',minWidth:900,borderCollapse:'collapse',fontSize:10}}><thead><tr style={{background:'#161f30',color:'#94a3b8',textAlign:'left'}}>{['Animal ID / Tag','Category','Sex','Breed','Age','Lifecycle','Status','Milk Schedule','Passport'].map(h=><th key={h} style={{padding:'8px 9px',whiteSpace:'nowrap'}}>{h}</th>)}</tr></thead><tbody>{rows.map(a=>{const exited=!active(a);return <tr key={a.animal_id} style={{borderBottom:'1px solid #1a2234',opacity:exited?.72:1}}><td style={{padding:'8px 9px'}}><button onClick={()=>onOpenPassport(a.animal_id)} style={{background:'none',border:0,padding:0,color:'#38bdf8',fontWeight:800,cursor:'pointer',textDecoration:'underline',fontSize:10}}>{a.animal_id}</button><div style={{fontSize:8,color:'#64748b'}}>{a.ear_tag||a.rfid||'No tag'}</div></td><td style={{padding:'8px 9px'}}>{category(a)}</td><td style={{padding:'8px 9px'}}>{a.sex||'—'}</td><td style={{padding:'8px 9px'}}>{a.breed||'—'}</td><td style={{padding:'8px 9px',color:'#94a3b8'}}>{age(a.date_of_birth)}</td><td style={{padding:'8px 9px'}}>{a.lifecycle_status||'—'}</td><td style={{padding:'8px 9px'}}><span style={{fontSize:8,fontWeight:800,padding:'3px 6px',borderRadius:4,background:exited?'#3f1d1d':'#064e3b',color:exited?'#fca5a5':'#6ee7b7'}}>{a.status||(a.active===false?'INACTIVE':'ACTIVE')}</span></td><td style={{padding:'8px 9px'}}>{a.milking_frequency||'—'}</td><td style={{padding:'8px 9px'}}><button onClick={()=>onOpenPassport(a.animal_id)} style={{...btn,padding:'4px 7px',fontSize:8}}>Open Passport</button></td></tr>})}</tbody></table>{rows.length===0&&<div style={{padding:18,textAlign:'center',color:'#64748b',fontSize:10}}>No animal records match this view.</div>}</div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:7,marginTop:9}}><LinkageCard icon={<Milk size={13}/>} title="Milk linkage" text="Passport links production and lactation history to the animal ID."/><LinkageCard icon={<HeartPulse size={13}/>} title="Health linkage" text="Passport links cases, treatments and withdrawal state."/><LinkageCard icon={<Activity size={13}/>} title="Breeding linkage" text="Passport links reproductive events, lineage and offspring."/></div>
 </div>
}
function Stat({label,value,active,onClick}:{label:string;value:number;active?:boolean;onClick:()=>void}){return <button onClick={onClick} style={{textAlign:'left',background:active?'#16263a':'#111827',border:`1px solid ${active?'#38bdf8':'#1f2937'}`,borderRadius:7,padding:'9px 10px',color:'#fff',cursor:'pointer',minWidth:0}}><div style={{fontSize:8,color:'#94a3b8',fontWeight:800,textTransform:'uppercase',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{label}</div><div style={{fontSize:17,fontWeight:900,color:active?'#38bdf8':'#fff',marginTop:3}}>{value}</div></button>}
function LinkageCard({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div style={{background:'#111827',border:'1px solid #1f2937',borderRadius:7,padding:9,display:'flex',gap:7,alignItems:'flex-start'}}><div style={{color:'#38bdf8',paddingTop:1}}>{icon}</div><div><div style={{fontSize:10,fontWeight:800}}>{title}</div><div style={{fontSize:8,color:'#64748b',marginTop:2}}>{text}</div></div></div>}
const btn:React.CSSProperties={background:'#1e293b',border:'1px solid #334155',color:'#cbd5e1',borderRadius:5,padding:'6px 9px',fontSize:9,fontWeight:700,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:4};
