import { useMemo, useState } from 'react';
import { Bot, Search, ShieldCheck } from 'lucide-react';

type KnowledgeAnswer = {
  topic: string;
  keywords: string[];
  answer: string;
  steps: string[];
  next: string;
  safety: string;
  source: string;
};

const knowledge: KnowledgeAnswer[] = [
  { topic: 'Milk late entry', keywords: ['milk', 'missed', 'late', 'entry', 'production'], answer: 'Enter the measured milk against the actual operational date and session. A late entry should remain a historical fact for that date, not become a value for today.', steps: ['Confirm permanent Animal ID and session.', 'Use the actual event date.', 'Save once and verify milk history and passport.', 'Review period totals and dependent COP/revenue views.'], next: 'Use the supported amendment path if the saved value is wrong; do not blind-retry.', safety: 'This assistant cannot create or amend a milk record.', source: 'Milk production knowledge base: milk.late-entry, milk.period-total' },
  { topic: 'Feed Cost / L', keywords: ['feed', 'cost', 'litre', 'liter', 'tmr', 'cost/l'], answer: 'Feed Cost/L is the selected-period governed daily TMR cost total divided by valid milk litres for the same period. Historical formula changes must not rewrite prior daily authority.', steps: ['Confirm the inclusive analysis dates.', 'Review the daily TMR calculation log.', 'Check feed status and consumed quantity.', 'Reconcile the milk denominator and missing dates.'], next: 'Investigate unavailable or partial days before using the value for COP decisions.', safety: 'The assistant does not substitute current TMR cost multiplied by days.', source: 'Feed/TMR and analytics knowledge base: feed.feed-cost-per-litre, analytics.period-and-cop' },
  { topic: 'Treatment and withdrawal', keywords: ['treatment', 'medicine', 'withdrawal', 'withheld', 'milk'], answer: 'Record veterinarian-authorised treatment and the approved withdrawal instruction. Milk during withdrawal must remain out of the sale stream through the governed disposition workflow.', steps: ['Confirm animal identity and treatment authority.', 'Record the actual treatment facts.', 'Verify the active withdrawal interval.', 'Record withheld milk as non-sale and schedule follow-up.'], next: 'Do not release milk until the authorised withdrawal condition is complete.', safety: 'No diagnosis, medicine selection, dosage, or withdrawal override is provided.', source: 'Veterinary knowledge base: health.treatment-withdrawal, disease-reference-catalog' },
  { topic: 'Vaccination', keywords: ['vaccine', 'vaccination', 'booster', 'due', 'immunization'], answer: 'Use a veterinarian-approved, region-specific programme. DairyOS records actual administrations and due information; a reminder is not proof that a vaccine was given.', steps: ['Confirm eligible animal or group.', 'Check approved product, storage, expiry, and instructions.', 'Record actual date, product, administrator, and next due date.', 'Review coverage and missed events.'], next: 'Escalate adverse reactions or missed programme decisions to the veterinarian.', safety: 'The assistant does not prescribe a universal schedule or dose.', source: 'Veterinary knowledge base: vaccination.programme-design, vaccination.event' },
  { topic: 'Breeding and pregnancy', keywords: ['breeding', 'insemination', 'pregnancy', 'reproductive', 'service'], answer: 'Record actual reproductive events and authorised diagnostic results. Current reproductive state is derived from persisted chronology; predictions and reminders are not confirmed events.', steps: ['Confirm permanent Animal ID.', 'Record the actual event date and responsible person.', 'Enter the result when known.', 'Review chronology, current state, and passport.'], next: 'Record pregnancy recheck, calving, loss, or subsequent service when actually observed.', safety: 'The assistant does not diagnose pregnancy or infer an event from a reminder.', source: 'Veterinary knowledge base: breeding.event, breeding.pregnancy, breeding.chronology' },
  { topic: 'Calving', keywords: ['calving', 'birth', 'calf', 'post-calving', 'fresh cow'], answer: 'Record the actual calving event and available offspring details. DairyOS then derives the post-calving reproductive state; milk, health, treatment, and follow-up remain separate records.', steps: ['Confirm dam identity and actual date.', 'Record calving and offspring facts.', 'Refresh reproductive state and passport.', 'Record fresh-cow milk and health observations separately.'], next: 'Follow the approved post-calving health and breeding-readiness plan.', safety: 'An expected calving date is not an actual calving event.', source: 'Veterinary knowledge base: breeding.calving, breeding.post-calving-return' },
  { topic: 'System health', keywords: ['health check', 'system health', 'database', 'readiness', 'startup'], answer: 'System Health is a read-only readiness check. It should report service, database, configuration, and projection status without changing operational records, backups, or settings.', steps: ['Open Settings and choose System Health.', 'Run the read-only check.', 'Review each component and timestamp.', 'Escalate failures with the displayed evidence.'], next: 'Do not use reset or manual database editing as a troubleshooting shortcut.', safety: 'The assistant cannot run health checks or repair the database.', source: 'Operations knowledge base: settings.system-health, startup.readiness' },
  { topic: 'Reset safety', keywords: ['reset', 'zero state', 'delete', 'deployment', 'clear data'], answer: 'Zero-state reset is an explicitly authorised pre-deployment action, not normal troubleshooting. It requires protected authentication, exact confirmation, recovery protection, and controlled processing.', steps: ['Confirm the target is not an active farm dataset.', 'Verify recovery protection.', 'Authenticate and use the exact confirmation.', 'Verify the resulting state after controlled restart.'], next: 'Retain recovery evidence and never use reset to fix a calculation or display issue.', safety: 'The assistant cannot request or execute a reset.', source: 'Operations knowledge base: settings.zero-state-reset' },
  { topic: 'Missing or stale data', keywords: ['missing', 'stale', 'not showing', 'orphan', 'saved', 'disappear'], answer: 'Trace the permanent identity, operational date, authoritative record, projection, and refresh path before entering anything again. A visible value or HTTP success alone is not proof of complete propagation.', steps: ['Capture the source identifier and timestamp.', 'Refresh the source and destination views.', 'Compare authoritative history with projections and audit evidence.', 'Escalate mismatches without blind duplicate retries.'], next: 'Use a controlled replay or correction only after the cause is isolated and authorised.', safety: 'The assistant does not edit or replay live records.', source: 'Persistence knowledge base: persistence.authority-and-audit, troubleshooting.missing-data' },
  { topic: 'Produced, sold, and non-sale milk', keywords: ['sold', 'sale', 'revenue', 'non-sale', 'receivable', 'disposition'], answer: 'Produced milk is not automatically sold. Reconcile valid production with sold, non-sale, withheld, and unallocated litres; revenue uses valid sold-litre sale facts.', steps: ['Confirm the period and production total.', 'Review dispositions by operational date.', 'Reconcile sold and non-sale quantities.', 'Check sale price, cash, receivable, amendments, and voids.'], next: 'Correct the source disposition or sale record rather than changing a report total.', safety: 'The assistant cannot create or amend revenue entries.', source: 'Revenue knowledge base: revenue.sold-litres, revenue.disposition, revenue.revenue' },
];

export default function DairyOSAssistant() {
  const [query, setQuery] = useState('');
  const [selectedTopic, setSelectedTopic] = useState(knowledge[0].topic);
  const selected = knowledge.find(item => item.topic === selectedTopic) ?? knowledge[0];
  const matches = useMemo(() => {
    const normalized = query.trim().toLowerCase();
    if (!normalized) return knowledge;
    return knowledge.filter(item => `${item.topic} ${item.keywords.join(' ')} ${item.answer}`.toLowerCase().includes(normalized));
  }, [query]);

  return (
    <section style={{ background: '#0f172a', border: '1px solid #1f2937', borderRadius: 8, padding: 14 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, alignItems: 'flex-start', flexWrap: 'wrap' }}>
        <div><div style={{ color: '#38bdf8', fontSize: 9, fontWeight: 900, letterSpacing: 1 }}>DAIRYOS ASSISTANT</div><h3 style={{ margin: '4px 0', fontSize: 17 }}>Ask about DairyOS</h3><div style={{ color: '#94a3b8', fontSize: 10 }}>Offline, read-only guidance from the reviewed knowledge base. It cannot write farm records.</div></div>
        <div style={{ display: 'inline-flex', gap: 5, alignItems: 'center', color: '#bbf7d0', fontSize: 9, fontWeight: 800 }}><ShieldCheck size={14} /> NO LIVE DATA ACCESS</div>
      </div>
      <div style={{ display: 'flex', gap: 7, marginTop: 12 }}><div style={{ position: 'relative', flex: 1 }}><Search size={14} style={{ position: 'absolute', left: 9, top: 9, color: '#64748b' }} /><input aria-label="Ask DairyOS Assistant" value={query} onChange={event => setQuery(event.target.value)} placeholder="Ask about milk, TMR, health, breeding, finance or settings…" style={{ width: '100%', boxSizing: 'border-box', padding: '8px 9px 8px 29px', background: '#1e293b', color: '#fff', border: '1px solid #334155', borderRadius: 6, fontSize: 11 }} /></div><button type="button" onClick={() => setQuery('')} style={{ background: '#334155', color: '#fff', border: 0, borderRadius: 6, padding: '8px 10px', cursor: 'pointer', fontSize: 10 }}>Clear</button></div>
      <div style={{ display: 'grid', gridTemplateColumns: 'minmax(190px,.75fr) minmax(0,1.8fr)', gap: 10, marginTop: 12 }}>
        <div style={{ display: 'grid', gap: 5, alignContent: 'start' }}>{matches.map(item => <button key={item.topic} type="button" onClick={() => setSelectedTopic(item.topic)} style={{ textAlign: 'left', background: selectedTopic === item.topic ? '#0c4a6e' : '#1e293b', color: '#f8fafc', border: selectedTopic === item.topic ? '1px solid #38bdf8' : '1px solid #334155', borderRadius: 6, padding: '8px 9px', cursor: 'pointer', fontSize: 10, fontWeight: 800 }}>{item.topic}</button>)}{matches.length === 0 && <div style={{ color: '#94a3b8', fontSize: 10, padding: 8 }}>No reviewed topic matched. Ask an authorised person or add the question to the knowledge-base review queue.</div>}</div>
        <div style={{ background: '#111827', border: '1px solid #1f2937', borderRadius: 7, padding: 12 }}>{matches.length > 0 ? <><div style={{ display: 'flex', gap: 7, alignItems: 'center', color: '#a78bfa', fontSize: 12, fontWeight: 900 }}><Bot size={16} />{selected.topic}</div><div style={{ marginTop: 9, fontSize: 12, lineHeight: 1.5, color: '#e2e8f0' }}>{selected.answer}</div><div style={{ marginTop: 12, color: '#38bdf8', fontSize: 9, fontWeight: 900, textTransform: 'uppercase' }}>Suggested steps</div><ol style={{ margin: '5px 0 0 18px', padding: 0, color: '#cbd5e1', fontSize: 11, lineHeight: 1.5 }}>{selected.steps.map(item => <li key={item}>{item}</li>)}</ol><div style={{ marginTop: 10, padding: 9, background: '#0f172a', borderRadius: 6, color: '#cbd5e1', fontSize: 10 }}><strong style={{ color: '#38bdf8' }}>What next:</strong> {selected.next}</div><div style={{ marginTop: 8, padding: 9, background: '#1c1917', border: '1px solid #78350f', borderRadius: 6, color: '#fde68a', fontSize: 10 }}><strong>Safety:</strong> {selected.safety}</div><div style={{ marginTop: 9, color: '#64748b', fontSize: 9 }}>Source: {selected.source}</div></> : <div style={{ color: '#94a3b8', fontSize: 11 }}>No answer available for this query.</div>}</div>
      </div>
    </section>
  );
}
