import React, { useEffect, useState } from 'react';
import { AlertTriangle, Utensils, Wheat, Wrench } from 'lucide-react';
import { API_BASE_URL } from '../config/api';
import TMRPreparationTool from './TMRPreparationTool';

const API_BASE = API_BASE_URL || 'http://127.0.0.1:8000';
type FeedItem = { id:number; item:string; unit:string; purchased:number; used:number; balance:number; status?:string };
type Equipment = { id:number; equipment_id:string; name?:string|null; category?:string|null; location?:string|null; status:string; condition:string; running_hours?:number|null; next_service_due_at?:string|null; active:boolean };
const panel:React.CSSProperties={background:'#111827',border:'1px solid #1f2937',borderRadius:8,padding:12,minWidth:0};
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#1e293b',color:'#fff',border:'1px solid #334155',borderRadius:5,padding:'7px 8px',fontSize:11};
const button=(background:string):React.CSSProperties=>({background,color:'#fff',border:0,borderRadius:5,padding:'8px 10px',fontSize:10,fontWeight:800,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:5});

export default function FeedTab(){
 const [feedItems,setFeedItems]=useState<FeedItem[]>([]),[equipment,setEquipment]=useState<Equipment[]>([]),[selectedItem,setSelectedItem]=useState(''),[usageType,setUsageType]=useState<'CONSUMPTION'|'WASTAGE'>('CONSUMPTION'),[usageQty,setUsageQty]=useState(''),[notes,setNotes]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [feedResponse,equipmentResponse]=await Promise.all([fetch(`${API_BASE}/farm/feed-inventory/authoritative`),fetch(`${API_BASE}/farm/equipment`)]);if(!feedResponse.ok)throw new Error('Authoritative feed inventory unavailable.');const body=await feedResponse.json();setFeedItems((body.items??[]).map((row:any)=>({id:Number(row.id),item:String(row.item),unit:String(row.unit||'unit'),purchased:Number(row.purchased_from_finance||0),used:Number(row.used_from_operations||0),balance:Number(row.balance||0),status:row.status})));if(equipmentResponse.ok){const payload=await equipmentResponse.json();setEquipment(Array.isArray(payload)?payload:Array.isArray(payload?.equipment)?payload.equipment:[])} }catch(e){setError(e instanceof Error?e.message:'Unable to load Feed data.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const current=feedItems.find(item=>String(item.id)===selectedItem);
 const recordUsage=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setError('');setMessage('');try{if(!current)throw new Error('Select a purchased feed item.');const quantity=Number(usageQty);if(!(quantity>0))throw new Error('Usage quantity must be greater than zero.');const catalog=await fetch(`${API_BASE}/farm/feed-inventory/dashboard`);if(catalog.ok){const dashboard=await catalog.json();const exists=(dashboard.items||[]).some((row:any)=>row.item===current.item);if(!exists){const create=await fetch(`${API_BASE}/farm/feed-inventory/items`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item:current.item,category:'FEED',unit:current.unit,reorder_level:0,active:true})});if(!create.ok)throw new Error('Could not initialize the purchased feed item for usage tracking.')}}const response=await fetch(`${API_BASE}/farm/feed-inventory/movements`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item:current.item,quantity,movement_type:usageType,unit:current.unit,notes:notes||null,recorded_by:'WEB'})});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:data.detail?.message||'Usage could not be recorded.');setMessage(`${usageType==='CONSUMPTION'?'Consumption':'Wastage'} recorded for ${current.item}.`);setUsageQty('');setNotes('');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to record feed usage.')}finally{setSaving(false)}};
 const totalPurchased=feedItems.reduce((sum,item)=>sum+item.purchased,0),totalBalance=feedItems.reduce((sum,item)=>sum+item.balance,0),lowBalance=feedItems.filter(item=>item.purchased>0&&item.balance<=0);
 const overdueEquipment=equipment.filter(item=>item.active&&item.next_service_due_at&&new Date(item.next_service_due_at).getTime()<Date.now());
 return <div style={{height:'100%',overflowY:'auto',overflowX:'hidden',boxSizing:'border-box',padding:14,color:'#fff',minWidth:0}}>
  <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:12,flexWrap:'wrap'}}><div><div style={{fontSize:18,fontWeight:800,display:'flex',alignItems:'center',gap:7}}><Wheat size={18} color="#38bdf8"/> Feed & Nutrition</div><div style={{fontSize:10,color:'#94a3b8',marginTop:3}}>Purchases come only from Finance Feed expenses. Usage is tracked here; balance = authoritative operational stock projection.</div></div></div>
  {error&&<div style={{...panel,color:'#fecaca',borderColor:'#ef4444',marginBottom:10,fontSize:10}}>{error}</div>}{message&&<div style={{...panel,color:'#bbf7d0',borderColor:'#34d399',marginBottom:10,fontSize:10}}>{message}</div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8,marginBottom:10}}><Metric label="Purchased in Finance" value={`${totalPurchased.toLocaleString()} kg/unit`} accent="#38bdf8"/><Metric label="Current Feed Balance" value={`${totalBalance.toLocaleString()} kg/unit`} accent="#34d399"/><Metric label="Items Purchased" value={String(feedItems.length)} accent="#f59e0b"/></div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(0,1.4fr) minmax(280px,.6fr)',gap:10,alignItems:'start',minWidth:0}}>
   <section style={panel}><div style={{fontSize:12,fontWeight:800,marginBottom:8}}>Feed Purchased in Finance</div>{loading?<div style={{fontSize:10,color:'#64748b'}}>Loading authoritative feed inventory…</div>:feedItems.length===0?<div style={{padding:20,textAlign:'center',color:'#64748b',fontSize:10}}>No Feed expenses have been entered in Finance yet.</div>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:10,minWidth:520}}><thead><tr style={{color:'#94a3b8',textAlign:'left',borderBottom:'1px solid #1f2937'}}><th style={{padding:7}}>Feed item</th><th style={{padding:7,textAlign:'right'}}>Purchased</th><th style={{padding:7,textAlign:'right'}}>Used</th><th style={{padding:7,textAlign:'right'}}>Balance</th><th style={{padding:7}}>Unit</th></tr></thead><tbody>{feedItems.map(item=><tr key={item.id} style={{borderBottom:'1px solid #1a2234'}}><td style={{padding:7,fontWeight:700}}>{item.item}</td><td style={{padding:7,textAlign:'right',color:'#38bdf8'}}>{item.purchased.toLocaleString()}</td><td style={{padding:7,textAlign:'right',color:'#f59e0b'}}>{item.used.toLocaleString()}</td><td style={{padding:7,textAlign:'right',color:item.balance<=0?'#f87171':'#34d399',fontWeight:800}}>{item.balance.toLocaleString()}</td><td style={{padding:7,color:'#94a3b8'}}>{item.unit}</td></tr>)}</tbody></table></div>}</section>
   <section style={panel}><div style={{fontSize:12,fontWeight:800,marginBottom:8,display:'flex',alignItems:'center',gap:6}}><Utensils size={14} color="#34d399"/> Record Feed Usage</div><form onSubmit={recordUsage} style={{display:'grid',gap:7}}><select required value={selectedItem} onChange={e=>setSelectedItem(e.target.value)} style={input}><option value="">Select purchased item…</option>{feedItems.map(item=><option key={item.id} value={String(item.id)}>{item.item}</option>)}</select><select value={usageType} onChange={e=>setUsageType(e.target.value as 'CONSUMPTION'|'WASTAGE')} style={input}><option value="CONSUMPTION">Consumption</option><option value="WASTAGE">Wastage</option></select><input required type="number" min="0.001" step="0.001" placeholder={current?`Quantity (${current.unit})`:'Quantity'} value={usageQty} onChange={e=>setUsageQty(e.target.value)} style={input}/><input placeholder="Notes" value={notes} onChange={e=>setNotes(e.target.value)} style={input}/><button disabled={saving||!current} type="submit" style={button('#059669')}>{saving?'Saving…':'Record Usage'}</button></form></section>
  </div>
  <section style={{...panel,marginTop:10}}><div style={{fontSize:12,fontWeight:800,marginBottom:8,display:'flex',alignItems:'center',gap:6}}><Wheat size={14} color="#a78bfa"/> Total Mixed Ration Preparation</div><div style={{fontSize:9,color:'#64748b',marginBottom:10}}>Operational TMR planning is now inside Feed. The calculator carries stage, herd size, ingredient quantities, units, unit prices, batch quantity and batch cost.</div><TMRPreparationTool/></section>
  <section style={{...panel,marginTop:10}}><div style={{fontSize:12,fontWeight:800,marginBottom:8,display:'flex',alignItems:'center',gap:6}}><Wrench size={14} color="#f59e0b"/> Feed-Related Equipment</div>{equipment.length===0?<div style={{fontSize:10,color:'#64748b'}}>No equipment records are currently registered.</div>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:10}}><thead><tr style={{color:'#94a3b8',textAlign:'left',borderBottom:'1px solid #1f2937'}}><th style={{padding:7}}>Equipment</th><th style={{padding:7}}>Category</th><th style={{padding:7}}>Location</th><th style={{padding:7}}>Status</th><th style={{padding:7}}>Condition</th><th style={{padding:7,textAlign:'right'}}>Hours</th><th style={{padding:7}}>Next Service</th></tr></thead><tbody>{equipment.map(item=><tr key={item.id} style={{borderBottom:'1px solid #1a2234'}}><td style={{padding:7,fontWeight:700}}>{item.name||item.equipment_id}</td><td style={{padding:7}}>{item.category||'—'}</td><td style={{padding:7}}>{item.location||'—'}</td><td style={{padding:7,color:item.status==='OUT_OF_SERVICE'?'#f87171':item.status==='MAINTENANCE'?'#fbbf24':'#86efac',fontWeight:800}}>{item.status}</td><td style={{padding:7}}>{item.condition}</td><td style={{padding:7,textAlign:'right'}}>{Number(item.running_hours||0).toLocaleString()}</td><td style={{padding:7,color:item.next_service_due_at&&new Date(item.next_service_due_at).getTime()<Date.now()?'#f87171':'#cbd5e1'}}>{item.next_service_due_at?item.next_service_due_at.slice(0,10):'—'}</td></tr>)}</tbody></table></div>}{overdueEquipment.length>0&&<div style={{marginTop:8,color:'#fbbf24',fontSize:10}}>{overdueEquipment.length} active equipment service item(s) are overdue and remain governed by the Equipment API/findings path.</div>}</section>
  {lowBalance.length>0&&<div style={{...panel,marginTop:10,borderColor:'#f59e0b'}}><div style={{color:'#f59e0b',fontWeight:800,fontSize:11,display:'flex',alignItems:'center',gap:5}}><AlertTriangle size={12}/> Feed balance needs attention</div><div style={{color:'#94a3b8',fontSize:10,marginTop:4}}>{lowBalance.map(item=>item.item).join(', ')} has no remaining balance from recorded purchases.</div></div>}
 </div>;
}
function Metric({label,value,accent}:{label:string;value:string;accent:string}){return <div style={{...panel,borderLeft:`4px solid ${accent}`}}><div style={{fontSize:8,color:'#94a3b8',textTransform:'uppercase',fontWeight:800}}>{label}</div><div style={{marginTop:4,fontSize:16,fontWeight:800,color:accent}}>{value}</div></div>}