import React, { useEffect, useMemo, useState } from 'react';
import { Ban, Edit3, Printer, Search } from 'lucide-react';
import { API_BASE_URL } from '../config/api';
const API_BASE=API_BASE_URL||'http://127.0.0.1:8000';
type MasterCategory='FEED'|'OPEX';type LedgerFilter='ALL'|MasterCategory;
type TaxonomyResponse={master_categories:MasterCategory[];taxonomies:Record<string,Record<string,string[]>>;items:Record<MasterCategory,string[]>};
type Transaction={id:number;transaction_type:string;category:string;master_category?:MasterCategory|null;sub_category?:string|null;custom_specification?:string|null;amount:number;quantity?:number|null;unit?:string|null;unit_rate?:number|null;date?:string|null;reference?:string|null;payment_method?:string|null;counterparty?:string|null;vendor_name?:string|null;notes?:string|null;status?:string|null;due_date?:string|null;settled_date?:string|null};
type Payables={as_of:string;outstanding_total:number;overdue_total:number;count:number;ageing_buckets:Record<string,number>;supplier_rollup:{supplier:string;outstanding:number}[];transactions:(Transaction&{days_overdue:number|null;age_bucket:string})[]};
type Props={onSaveSale?:(liters:number)=>void;onUpdateReceivables?:(amount:number)=>void};
const inputStyle:React.CSSProperties={background:'#1e293b',color:'#fff',border:'1px solid #334155',padding:'7px 8px',borderRadius:5,fontSize:11,boxSizing:'border-box',width:'100%'};
const smallButton:React.CSSProperties={background:'#1e293b',border:'1px solid #334155',color:'#cbd5e1',padding:'4px 7px',borderRadius:4,fontSize:9,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:4};
const button=(bg:string):React.CSSProperties=>({background:bg,color:'#fff',border:0,borderRadius:5,padding:'8px 12px',fontSize:10,fontWeight:800,cursor:'pointer'});const today=()=>new Date().toISOString().slice(0,10);const money=(v:number)=>`PKR ${Number(v||0).toLocaleString('en-PK',{maximumFractionDigits:2})}`;

export default function FinanceTab({onSaveSale,onUpdateReceivables}:Props={}){
 const [transactions,setTransactions]=useState<Transaction[]>([]),[taxonomy,setTaxonomy]=useState<TaxonomyResponse|null>(null),[payables,setPayables]=useState<Payables|null>(null),[masterCategory,setMasterCategory]=useState<MasterCategory>('FEED'),[subCategory,setSubCategory]=useState(''),[customSpecification,setCustomSpecification]=useState(''),[quantity,setQuantity]=useState(''),[unit,setUnit]=useState('kg'),[unitRate,setUnitRate]=useState(''),[directAmount,setDirectAmount]=useState(''),[expenseDate,setExpenseDate]=useState(today()),[vendor,setVendor]=useState(''),[paymentMethod,setPaymentMethod]=useState('BANK'),[reference,setReference]=useState(''),[notes,setNotes]=useState(''),[dueDate,setDueDate]=useState(''),[ledgerFilter,setLedgerFilter]=useState<LedgerFilter>('ALL'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [voidTarget,setVoidTarget]=useState<Transaction|null>(null),[voidReason,setVoidReason]=useState(''),[editTarget,setEditTarget]=useState<Transaction|null>(null),[editSaving,setEditSaving]=useState(false),[revCategory,setRevCategory]=useState('Milk Sales'),[revAmount,setRevAmount]=useState(''),[revQty,setRevQty]=useState(''),[revDate,setRevDate]=useState(today()),[revRef,setRevRef]=useState(''),[revNotes,setRevNotes]=useState(''),[revStatus,setRevStatus]=useState<'RECEIVED'|'RECEIVABLE'>('RECEIVABLE'),[revDueDate,setRevDueDate]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [ledgerRes,taxRes,payRes]=await Promise.all([fetch(`${API_BASE}/farm/finance-ledger`),fetch(`${API_BASE}/farm/finance-ledger/taxonomy`),fetch(`${API_BASE}/farm/finance-ledger/payables`)]);if(!ledgerRes.ok||!taxRes.ok)throw new Error('Finance API unavailable.');const ledger=await ledgerRes.json(),tax=await taxRes.json();setTransactions(ledger.transactions??[]);setTaxonomy(tax);if(payRes.ok)setPayables(await payRes.json())}catch(e){setError(e instanceof Error?e.message:'Unable to load Finance data.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);useEffect(()=>{const items=taxonomy?.items?.[masterCategory]??[];setSubCategory(items[0]??'');setCustomSpecification('')},[masterCategory,taxonomy]);
 const expenseRows=useMemo(()=>transactions.filter(t=>(t.transaction_type==='EXPENSE'||t.transaction_type==='PAYMENT')&&t.status!=='VOID'),[transactions]);const revenueRows=useMemo(()=>transactions.filter(t=>(t.transaction_type==='INCOME'||t.transaction_type==='RECEIPT')&&t.status!=='VOID'),[transactions]);
 const filteredExpenses=useMemo(()=>{const q=search.trim().toLowerCase();const base=ledgerFilter==='ALL'?expenseRows:expenseRows.filter(t=>t.master_category===ledgerFilter);return base.filter(t=>!q||[t.sub_category,t.custom_specification,t.vendor_name,t.counterparty,t.reference,t.notes].some(v=>String(v??'').toLowerCase().includes(q)))},[expenseRows,ledgerFilter,search]);
 const cashRevenue=revenueRows.filter(t=>['RECEIVED','RECORDED','PAID'].includes(String(t.status))).reduce((s,t)=>s+t.amount,0),receivables=revenueRows.filter(t=>t.status==='RECEIVABLE').reduce((s,t)=>s+t.amount,0),totalExpenses=expenseRows.reduce((s,t)=>s+t.amount,0),payableTotal=expenseRows.filter(t=>t.status==='PAYABLE').reduce((s,t)=>s+t.amount,0),netCash=cashRevenue-totalExpenses;
 const subItems=taxonomy?.items?.[masterCategory]??[];const calculatedAmount=quantity&&unitRate?Number(quantity)*Number(unitRate):Number(directAmount||0);useEffect(()=>{onUpdateReceivables?.(receivables)},[receivables,onUpdateReceivables]);
 const saveExpense=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const status=paymentMethod==='CREDIT'?'PAYABLE':'PAID';const r=await fetch(`${API_BASE}/farm/finance-ledger`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transaction_type:'EXPENSE',master_category:masterCategory,sub_category:subCategory,custom_specification:subCategory==='Other'?customSpecification:null,quantity:quantity?Number(quantity):null,unit:quantity?unit:null,unit_rate:quantity?Number(unitRate):null,amount:calculatedAmount,transaction_date:expenseDate,payment_method:paymentMethod,counterparty:vendor||null,reference:reference||null,notes:notes||null,status,due_date:status==='PAYABLE'?dueDate:null})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Expense could not be saved.');setQuantity('');setUnitRate('');setDirectAmount('');setVendor('');setReference('');setNotes('');setCustomSpecification('');setDueDate('');await load()}catch(e){setError(e instanceof Error?e.message:'Expense save failed.')}finally{setSaving(false)}};
 const saveRevenue=async(e:React.FormEvent)=>{e.preventDefault();const amount=Number(revAmount);if(!(amount>0))return;setSaving(true);setError('');try{const map:Record<string,string>={'Milk Sales':'MILK_SALES','Organic Manure / Dung':'MANURE_SALES','Male Calf Sales':'MALE_CALF_SALES'};const r=await fetch(`${API_BASE}/farm/finance-ledger`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transaction_type:revStatus==='RECEIVED'?'RECEIPT':'INCOME',category:map[revCategory]??'OTHER_REVENUE',amount,quantity:revQty?Number(revQty):null,transaction_date:revDate,payment_method:revStatus==='RECEIVABLE'?'CREDIT':'CASH',status:revStatus,due_date:revStatus==='RECEIVABLE'?revDueDate:null,reference:revRef||null,notes:revNotes||null})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Revenue could not be saved.');if(revCategory==='Milk Sales'&&revQty)onSaveSale?.(Number(revQty));setRevAmount('');setRevQty('');setRevRef('');setRevNotes('');setRevDueDate('');await load()}catch(e){setError(e instanceof Error?e.message:'Revenue save failed.')}finally{setSaving(false)}};
 const updateStatus=async(t:Transaction,status:string,reason?:string)=>{try{const r=await fetch(`${API_BASE}/farm/finance-ledger/${t.id}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,reason})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Status update failed.');await load()}catch(e){setError(e instanceof Error?e.message:'Status update failed.')}finally{setVoidTarget(null);setVoidReason('')}};
 const saveEdit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editTarget)return;setEditSaving(true);setError('');try{const f=new FormData(e.currentTarget),qty=Number(f.get('quantity')||0),rate=Number(f.get('unit_rate')||0),amount=qty>0?qty*rate:Number(f.get('amount')||0);const r=await fetch(`${API_BASE}/farm/finance-ledger/${editTarget.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({master_category:f.get('master_category'),sub_category:f.get('sub_category'),custom_specification:f.get('custom_specification')||null,quantity:qty>0?qty:null,unit:qty>0?String(f.get('unit')||'kg'):null,unit_rate:qty>0?rate:null,amount,transaction_date:f.get('transaction_date'),payment_method:f.get('payment_method'),counterparty:f.get('counterparty'),reference:f.get('reference'),notes:f.get('notes'),status:f.get('status'),due_date:f.get('due_date')||null})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Finance entry could not be edited.');setEditTarget(null);await load()}catch(e){setError(e instanceof Error?e.message:'Finance edit failed.')}finally{setEditSaving(false)}};
 return <div style={{padding:14,color:'#fff',height:'100%',overflowY:'auto',overflowX:'hidden',boxSizing:'border-box',minWidth:0}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap',marginBottom:10}}><div><div style={{fontSize:18,fontWeight:800}}>Finance & Accounting</div><div style={{fontSize:10,color:'#94a3b8'}}>Revenue, receivables, expenses, payables and the persistent accounting ledger.</div></div></div>
  {error&&<div style={{background:'rgba(239,68,68,.12)',border:'1px solid #ef4444',color:'#fecaca',padding:8,borderRadius:6,marginBottom:10,fontSize:10}}>{error}</div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(5,minmax(0,1fr))',gap:7,marginBottom:10}}>{[['Cash Revenue',cashRevenue,'#34d399'],['Receivables',receivables,'#f59e0b'],['Payables',payableTotal,'#fb7185'],['Total Expenses',totalExpenses,'#f87171'],['Net Cash Position',netCash,'#38bdf8']].map(([label,value,color])=><div key={String(label)} style={{background:'#111827',border:'1px solid #1f2937',borderLeft:`4px solid ${String(color)}`,borderRadius:7,padding:'9px 10px',minWidth:0}}><div style={{fontSize:8,color:'#94a3b8',textTransform:'uppercase',fontWeight:800}}>{String(label)}</div><div style={{fontSize:15,fontWeight:900,color:String(color),marginTop:3}}>{money(Number(value))}</div></div>)}</div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr)',gap:10,alignItems:'start'}}>
   <div style={{display:'grid',gap:10}}>
    <form onSubmit={saveRevenue} style={card}><div style={sectionTitle}>Record Revenue</div><div style={{display:'grid',gridTemplateColumns:'1.2fr 1fr 1fr',gap:6}}><select value={revCategory} onChange={e=>setRevCategory(e.target.value)} style={inputStyle}><option>Milk Sales</option><option>Organic Manure / Dung</option><option>Male Calf Sales</option></select><input required type="number" min="0" step="0.01" value={revAmount} onChange={e=>setRevAmount(e.target.value)} style={inputStyle} placeholder="Amount"/><input type="number" min="0" step="0.01" value={revQty} onChange={e=>setRevQty(e.target.value)} style={inputStyle} placeholder="Quantity"/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:6,marginTop:6}}><input type="date" value={revDate} onChange={e=>setRevDate(e.target.value)} style={inputStyle}/><select value={revStatus} onChange={e=>setRevStatus(e.target.value as 'RECEIVED'|'RECEIVABLE')} style={inputStyle}><option value="RECEIVABLE">Credit / Receivable</option><option value="RECEIVED">Cash Received</option></select>{revStatus==='RECEIVABLE'?<input required type="date" value={revDueDate} onChange={e=>setRevDueDate(e.target.value)} style={inputStyle}/>:<input value={revRef} onChange={e=>setRevRef(e.target.value)} style={inputStyle} placeholder="Reference"/>}</div>{revStatus==='RECEIVABLE'&&<input value={revRef} onChange={e=>setRevRef(e.target.value)} style={{...inputStyle,marginTop:6}} placeholder="Reference"/>}<input value={revNotes} onChange={e=>setRevNotes(e.target.value)} style={{...inputStyle,marginTop:6}} placeholder="Notes"/><button disabled={saving} type="submit" style={{...button('#059669'),width:'100%',marginTop:6}}>{saving?'Saving…':'Save Revenue'}</button></form>
    <section style={card}><div style={sectionTitle}>Revenue Ledger</div>{revenueRows.slice(0,50).map(r=><div key={r.id} style={row}><div style={{flex:1,minWidth:0}}><strong>{r.notes||r.category}</strong><div style={muted}>{r.date?.slice(0,10)} • {r.reference||'No reference'}{r.due_date?` • Due ${r.due_date}`:''}</div></div><div style={{fontWeight:800,color:r.status==='RECEIVABLE'?'#f59e0b':'#34d399'}}>{money(r.amount)}</div>{r.status==='RECEIVABLE'&&<button onClick={()=>void updateStatus(r,'RECEIVED')} style={smallButton}>Paid</button>}</div>)}{!loading&&revenueRows.length===0&&<div style={empty}>No persisted revenue entries.</div>}</section>
   </div>
   <div style={{display:'grid',gap:10}}>
    <form onSubmit={saveExpense} style={card}><div style={sectionTitle}>Record Expense</div><div style={{fontSize:9,color:'#64748b',marginBottom:7}}>Feed purchases are entered here and automatically appear in the Feed tab. Other operating expenses remain accounting entries here.</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}>
  <button
    type="button"
    onClick={()=>setMasterCategory('FEED')}
    style={{
      background:masterCategory==='FEED'?'#0369a1':'#1e293b',
      border:'1px solid',
      borderColor:masterCategory==='FEED'?'#38bdf8':'#334155',
      color:'#fff',
      padding:'10px 10px',
      borderRadius:5,
      fontSize:11,
      fontWeight:800,
      cursor:'pointer'
    }}
  >
    Feed Expenses
  </button>

  <button
    type="button"
    onClick={()=>setMasterCategory('OPEX')}
    style={{
      background:masterCategory==='OPEX'?'#92400e':'#1e293b',
      border:'1px solid',
      borderColor:masterCategory==='OPEX'?'#f59e0b':'#334155',
      color:'#fff',
      padding:'10px 10px',
      borderRadius:5,
      fontSize:11,
      fontWeight:800,
      cursor:'pointer'
    }}
  >
    OPEX
  </button>
</div>

<div style={{marginTop:6}}>
  <select
    required
    value={subCategory}
    onChange={e=>setSubCategory(e.target.value)}
    style={inputStyle}
  >
    {(Object.entries(taxonomy?.taxonomies?.[masterCategory]??{}) as [string,string[]][]).map(([group,items])=>(
      <optgroup key={group} label={group.replace(/_/g,' ')}>
        {items.map(item=>(
          <option key={item} value={item}>{item}</option>
        ))}
      </optgroup>
    ))}
  </select>
</div>{subCategory==='Other'&&<input required value={customSpecification} onChange={e=>setCustomSpecification(e.target.value)} style={{...inputStyle,marginTop:6}} placeholder="Specification"/>}<input value={vendor} onChange={e=>setVendor(e.target.value)} style={{...inputStyle,marginTop:6}} placeholder="Vendor / Supplier"/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr 1fr',gap:6,marginTop:6}}><input type="number" min="0" step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)} style={inputStyle} placeholder="Quantity"/><select value={unit} onChange={e=>setUnit(e.target.value)} style={inputStyle}><option>kg</option><option>bag</option><option>ton</option><option>litre</option><option>service</option><option>head</option><option>unit</option></select><input type="number" min="0" step="0.01" value={unitRate} onChange={e=>setUnitRate(e.target.value)} style={inputStyle} placeholder="Unit rate" disabled={!quantity}/><input type="number" min="0" step="0.01" value={quantity?calculatedAmount:directAmount} onChange={e=>quantity?undefined:setDirectAmount(e.target.value)} style={inputStyle} placeholder="Amount" readOnly={Boolean(quantity)}/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:6,marginTop:6}}><input type="date" value={expenseDate} onChange={e=>setExpenseDate(e.target.value)} style={inputStyle}/><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)} style={inputStyle}><option>BANK</option><option>CASH</option><option>MOBILE</option><option value="CREDIT">Credit / Payable</option></select>{paymentMethod==='CREDIT'?<input required type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} style={inputStyle}/>:<input value={reference} onChange={e=>setReference(e.target.value)} style={inputStyle} placeholder="Reference"/>}</div>{paymentMethod==='CREDIT'&&<input value={reference} onChange={e=>setReference(e.target.value)} style={{...inputStyle,marginTop:6}} placeholder="Reference"/>}<input value={notes} onChange={e=>setNotes(e.target.value)} style={{...inputStyle,marginTop:6}} placeholder="Notes"/><button disabled={saving} type="submit" style={{...button('#0284c7'),width:'100%',marginTop:6}}>{saving?'Saving…':'Save Expense'}</button></form>
    <section style={card}><div style={sectionTitle}>Accounting Expense Ledger</div><div style={{display:'flex',gap:5,flexWrap:'wrap',marginBottom:7}}>{(['ALL','FEED','OPEX'] as LedgerFilter[]).map(f=><button key={f} onClick={()=>setLedgerFilter(f)} style={{...smallButton,background:ledgerFilter===f?'#0ea5e9':'#1e293b',color:'#fff'}}>{f}</button>)}<div style={{display:'flex',alignItems:'center',gap:4,flex:1,minWidth:150,background:'#1e293b',border:'1px solid #334155',padding:'4px 6px',borderRadius:4}}><Search size={11} color="#94a3b8"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search ledgerâ€¦" style={{...inputStyle,border:0,padding:0,background:'transparent'}}/></div><button onClick={()=>window.print()} style={smallButton}><Printer size={11}/></button></div>{loading?<div style={empty}>Loading persistent ledgerâ€¦</div>:filteredExpenses.slice(0,100).map(r=><div key={r.id} style={row}><div style={{minWidth:80}}><div style={muted}>{r.date?.slice(0,10)}</div><strong>{r.master_category||'LEGACY'}</strong></div><div style={{flex:1,minWidth:0}}><div style={{fontWeight:700}}>{r.sub_category||r.category}{r.custom_specification?` — ${r.custom_specification}`:''}</div><div style={muted}>{r.vendor_name||'No vendor'} • {r.payment_method||'No payment'}{r.due_date?` • Due ${r.due_date}`:''}</div></div><div style={{textAlign:'right'}}><strong>{money(r.amount)}</strong><div style={muted}>{r.status}</div></div>{r.status!=='VOID'&&<button onClick={()=>setEditTarget(r)} style={smallButton}><Edit3 size={10}/></button>}{r.status!=='VOID'&&<button onClick={()=>setVoidTarget(r)} style={{...smallButton,color:'#f87171'}}><Ban size={10}/></button>}</div>)}{!loading&&filteredExpenses.length===0&&<div style={empty}>No expenses match this view.</div>}</section>
   </div>
  </div>
  <section style={{...card,marginTop:10}}><div style={sectionTitle}>Payables</div>{payables?<><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:7}}><Summary label="Outstanding" value={money(payables.outstanding_total)}/><Summary label="Overdue" value={money(payables.overdue_total)}/><Summary label="Open bills" value={String(payables.count)}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:6,marginTop:7}}>{[['CURRENT',payables.ageing_buckets.CURRENT],['1-30',payables.ageing_buckets['1_30']],['31-60',payables.ageing_buckets['31_60']],['61-90',payables.ageing_buckets['61_90']],['90+',payables.ageing_buckets['90_PLUS']],['NO DUE DATE',payables.ageing_buckets.NO_DUE_DATE]].map(([l,v])=><Summary key={String(l)} label={String(l)} value={money(Number(v))}/>)}</div>{payables.transactions.slice(0,20).map(r=><div key={r.id} style={row}><div style={{flex:1}}><strong>{r.vendor_name||'Unspecified Supplier'}</strong><div style={muted}>{r.sub_category||r.category} • Due {r.due_date||'—'}</div></div><div style={{textAlign:'right'}}><strong>{money(r.amount)}</strong><div style={muted}>{r.days_overdue&&r.days_overdue>0?`${r.days_overdue} days overdue`:'Current'}</div></div><button onClick={()=>void updateStatus(r,'PAID')} style={smallButton}>Paid</button></div>)}</>:<div style={empty}>No payables data available.</div>}</section>
  {editTarget&&<div style={modalBackdrop}><form onSubmit={saveEdit} style={modalCard}><strong style={{fontSize:13}}>Edit Finance Entry #{editTarget.id}</strong><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6,marginTop:8}}><input name="transaction_date" type="date" defaultValue={editTarget.date?.slice(0,10)} style={inputStyle}/><select name="master_category" defaultValue={editTarget.master_category||'FEED'} style={inputStyle}><option>FEED</option><option>OPEX</option></select><input name="sub_category" defaultValue={editTarget.sub_category||''} style={inputStyle}/><input name="custom_specification" defaultValue={editTarget.custom_specification||''} style={inputStyle}/><input name="quantity" type="number" step="0.001" defaultValue={editTarget.quantity??''} style={inputStyle}/><input name="unit" defaultValue={editTarget.unit||'kg'} style={inputStyle}/><input name="unit_rate" type="number" step="0.01" defaultValue={editTarget.unit_rate??''} style={inputStyle}/><input name="amount" type="number" step="0.01" defaultValue={editTarget.amount} style={inputStyle}/><input name="counterparty" defaultValue={editTarget.vendor_name||''} style={inputStyle} placeholder="Vendor"/><input name="reference" defaultValue={editTarget.reference||''} style={inputStyle} placeholder="Reference"/><select name="payment_method" defaultValue={editTarget.payment_method||'BANK'} style={inputStyle}><option>BANK</option><option>CASH</option><option>MOBILE</option><option>CREDIT</option></select><select name="status" defaultValue={editTarget.status==='PAYABLE'?'PAYABLE':'PAID'} style={inputStyle}><option>PAID</option><option>PAYABLE</option></select><input name="due_date" type="date" defaultValue={editTarget.due_date||''} style={inputStyle}/><input name="notes" defaultValue={editTarget.notes||''} style={inputStyle} placeholder="Notes"/></div><div style={{display:'flex',justifyContent:'flex-end',gap:6,marginTop:8}}><button type="button" onClick={()=>setEditTarget(null)} style={smallButton}>Cancel</button><button disabled={editSaving} type="submit" style={button('#0284c7')}>{editSaving?'Saving…':'Save Changes'}</button></div></form></div>}
  {voidTarget&&<div style={modalBackdrop}><div style={modalCard}><strong style={{color:'#ef4444'}}>Void Finance Entry #{voidTarget.id}</strong><textarea required value={voidReason} onChange={e=>setVoidReason(e.target.value)} placeholder="Reason" style={{...inputStyle,minHeight:70,marginTop:8}}/><div style={{display:'flex',justifyContent:'flex-end',gap:6,marginTop:8}}><button onClick={()=>setVoidTarget(null)} style={smallButton}>Cancel</button><button disabled={!voidReason.trim()} onClick={()=>void updateStatus(voidTarget,'VOID',voidReason)} style={button('#dc2626')}>Confirm Void</button></div></div></div>}
 </div>
}
const card:React.CSSProperties={background:'#111827',border:'1px solid #1f2937',borderRadius:8,padding:10,minWidth:0};const sectionTitle:React.CSSProperties={fontSize:11,fontWeight:800,marginBottom:7};const row:React.CSSProperties={display:'flex',alignItems:'center',gap:8,padding:'7px 8px',borderBottom:'1px solid #1a2234',fontSize:10,minWidth:0};const muted:React.CSSProperties={fontSize:8,color:'#64748b'};const empty:React.CSSProperties={padding:14,color:'#64748b',fontSize:10,textAlign:'center'};const modalBackdrop:React.CSSProperties={position:'fixed',inset:0,background:'rgba(0,0,0,.72)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000,padding:16};const modalCard:React.CSSProperties={background:'#111827',border:'1px solid #334155',borderRadius:8,padding:16,width:'min(720px,100%)',maxHeight:'90vh',overflowY:'auto'};
function Summary({label,value}:{label:string;value:string}){return <div style={{background:'#1e293b',border:'1px solid #334155',borderRadius:5,padding:7}}><div style={{fontSize:8,color:'#94a3b8'}}>{label}</div><div style={{fontSize:10,fontWeight:800,marginTop:2}}>{value}</div></div>}
