import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,HeartPulse,Plus,Search,X} from 'lucide-react';
import AnimalPassportModal from './AnimalPassportModal';
import {apiUrl} from '../config/api';
interface HerdAnimal{id:string;breed:string;category:string;status:string}
type CaseRow={id?:number|string;case_id?:number|string;animal_id?:string;status?:string;severity?:string;diagnosis?:string;notes?:string;follow_up_due_at?:string|null};
type Row={id:string;animalId:string;date:string;kind:'Treatment'|'Observation';detail:string;medicine:string;veterinarian:string;withdrawalDays:number;active:boolean};
interface Props{onOpenPassport?:(id:string)=>void;herdMasterList?:HerdAnimal[];onChanged?:()=>void}
const DIAGNOSES=['Mastitis','Metritis / Endometritis','Lameness / Hoof Disorder','Ketosis','Milk Fever / Hypocalcemia','Retained Placenta','Displaced Abomasum','Respiratory Disease / Pneumonia','Diarrhea / Enteritis','Foot Rot','Bloat / Tympany','Ruminal Acidosis','Fever / Pyrexia','Injury / Trauma','Other'];
const MEDICINES=['Oxytetracycline','Penicillin / Streptomycin','Ceftiofur','Amoxicillin / Ampicillin','Flunixin meglumine','Meloxicam','Ketoprofen','Calcium borogluconate','Dextrose / Energy support','Oral / IV electrolytes','Intramammary mastitis treatment','Anthelmintic / Dewormer','Topical antiseptic / wound care','Supportive therapy','Other'];
const field:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#0f172a',color:'#fff',border:'1px solid #334155',padding:'9px 10px',borderRadius:6,fontSize:12};
const card:React.CSSProperties={background:'#111827',border:'1px solid #1f2937',borderRadius:8,minWidth:0};
const th:React.CSSProperties={padding:'9px 10px',textAlign:'left',color:'#cbd5e1',fontSize:10,whiteSpace:'nowrap'};
const td:React.CSSProperties={padding:'9px 10px',borderTop:'1px solid #1f2937',verticalAlign:'top'};
const btn=(bg:string):React.CSSProperties=>({background:bg,color:'#fff',border:0,padding:'8px 11px',borderRadius:6,fontWeight:800,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:5,fontSize:11});
function d(v:unknown){if(!v)return'';const x=new Date(String(v));return Number.isNaN(x.getTime())?String(v).slice(0,10):x.toISOString().slice(0,10)}
async function get<T>(p:string):Promise<T>{const r=await fetch(apiUrl(p));if(!r.ok)throw new Error(`Request failed: ${r.status}`);return r.json() as Promise<T>}
async function post<T>(p:string,x:unknown):Promise<T>{const r=await fetch(apiUrl(p),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});if(!r.ok){let m=`Request failed: ${r.status}`;try{const b=await r.json() as {detail?:unknown};if(typeof b.detail==='string')m=b.detail}catch{}throw new Error(m)}return r.json() as Promise<T>}
function counts<T>(rows:T[],key:(r:T)=>string){const m=new Map<string,number>();rows.forEach(r=>{const k=key(r).trim()||'Unspecified';m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)}
export default function HealthTab({onOpenPassport,herdMasterList=[],onChanged}:Props){
 const [cases,setCases]=useState<CaseRow[]>([]),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[show,setShow]=useState(false),[passport,setPassport]=useState<string|null>(null);
 const [animal,setAnimal]=useState(herdMasterList[0]?.id||''),[diagnosis,setDiagnosis]=useState(''),[medicine,setMedicine]=useState(''),[vet,setVet]=useState(''),[withdrawal,setWithdrawal]=useState('0'),[dose,setDose]=useState(''),[route,setRoute]=useState(''),[severity,setSeverity]=useState('NORMAL'),[follow,setFollow]=useState('');
 useEffect(()=>{if(herdMasterList.length&&!herdMasterList.some(a=>a.id===animal))setAnimal(herdMasterList[0].id)},[herdMasterList,animal]);
 const openPassport=(id:string)=>onOpenPassport?onOpenPassport(id):setPassport(id);
 const load=async()=>{setLoading(true);setError('');try{const [cp,obs,trt]=await Promise.all([get<{cases?:CaseRow[]}>('/farm/health-cases'),get<any[]>('/farm/health-observations'),get<any[]>('/farm/treatments')]);const cs=Array.isArray(cp?.cases)?cp.cases:[];setCases(cs);const active=new Set(cs.filter(c=>String(c.status||'').toUpperCase()!=='RESOLVED').map(c=>String(c.animal_id||'')));setRows([...obs.map((x,i)=>({id:`OBS-${x.id??i}`,animalId:String(x.animal_id||''),date:d(x.timestamp||x.observed_at||x.date),kind:'Observation' as const,detail:String(x.observation||x.symptom||'Clinical observation'),medicine:'â€”',veterinarian:String(x.reported_by||x.operator||'API'),withdrawalDays:0,active:active.has(String(x.animal_id||''))})),...trt.map((x,i)=>({id:`TRT-${x.treatment_id??x.id??i}`,animalId:String(x.animal_id||''),date:d(x.treated_at||x.timestamp||x.date),kind:'Treatment' as const,detail:String(x.diagnosis||x.notes||x.medicine||'Treatment'),medicine:String(x.medicine||'â€”'),veterinarian:String(x.treated_by||x.operator||'API'),withdrawalDays:Number(x.milk_withdrawal_days||0),active:active.has(String(x.animal_id||''))}))].sort((a,b)=>b.date.localeCompare(a.date)))}catch(e){setError(e instanceof Error?e.message:'Unable to load Health.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[herdMasterList]);
 const active=useMemo(()=>cases.filter(c=>String(c.status||'').toUpperCase()!=='RESOLVED'),[cases]),withdrawals=useMemo(()=>rows.filter(r=>r.active&&r.withdrawalDays>0).length,[rows]);
 const overdueFollow=useMemo(()=>active.filter(c=>{const x=d(c.follow_up_due_at);return x&&x<=new Date().toISOString().slice(0,10)}).length,[active]);
 const recent=useMemo(()=>{const cut=new Date();cut.setDate(cut.getDate()-7);return rows.filter(r=>r.date&&new Date(r.date)>=cut).length},[rows]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?rows.filter(r=>`${r.animalId} ${r.detail} ${r.medicine} ${r.veterinarian}`.toLowerCase().includes(q)):rows},[rows,search]);
 const illness=useMemo(()=>counts(rows.filter(r=>r.kind==='Treatment'),r=>r.detail),[rows]),meds=useMemo(()=>counts(rows.filter(r=>r.kind==='Treatment'),r=>r.medicine),[rows]);
 const resolve=async(c:CaseRow)=>{const id=String(c.id??c.case_id??''),aid=String(c.animal_id||'');if(!id)return setError('Missing clinical case ID.');if(!confirm(`Declare ${aid} healthy and resolve case ${id}?`))return;setSaving(true);try{await post(`/farm/health-cases/${encodeURIComponent(id)}/resolve`,{resolution:'Declared healthy after clinical recovery.',resolved_by:vet||'Operator UI',operator:vet||'Operator UI'});setMessage(`${aid} declared healthy; history retained.`);await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to resolve case.')}finally{setSaving(false)}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const hc=await post<any>('/farm/health-cases',{animal_id:animal,severity,diagnosis,notes:diagnosis,follow_up_due_at:follow||null,operator:vet||'Operator UI'});await post('/farm/treatments',{animal_id:animal,medicine,diagnosis,treated_by:vet||null,milk_withdrawal_days:Number(withdrawal||0),notes:diagnosis,operator:vet||'Operator UI',dose:[dose,route].filter(Boolean).join(' / ')||null,health_case_id:hc.id});setShow(false);setDiagnosis('');setMedicine('');setWithdrawal('0');setDose('');setRoute('');setSeverity('NORMAL');setFollow('');setMessage('Treatment recorded and linked to the Animal Passport.');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to save treatment.')}finally{setSaving(false)}};
 return <div style={{padding:16,color:'#fff',height:'100%',overflowY:'auto',boxSizing:'border-box'}}><Header title="Clinical Health" subtitle="Reactive care: identify illness, treat, follow up, recover." action={<button onClick={()=>setShow(true)} style={btn('#b91c1c')}><Plus size={14}/>Record Treatment</button>}/>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:8,marginBottom:12}}><Metric title="Active Sick Animals" value={new Set(active.map(c=>c.animal_id)).size}/><Metric title="Follow-ups Due / Overdue" value={overdueFollow}/><Metric title="Animals in Milk Withdrawal" value={withdrawals}/><Metric title="Clinical Events â€” 7 Days" value={recent}/></div>
 {error&&<Notice error text={error}/>} {message&&<Notice text={message}/>}
 <section style={{...card,marginBottom:12,overflowX:'auto'}}><h3 style={{padding:'0 12px'}}>Action Queue - Active Clinical Cases</h3><table style={{width:'100%',minWidth:860,borderCollapse:'collapse',fontSize:11}}><thead><tr><th style={th}>Animal</th><th style={th}>Diagnosis</th><th style={th}>Severity</th><th style={th}>Follow-up</th><th style={th}>Status</th><th style={th}>Action</th></tr></thead><tbody>{!loading&&active.map((c,i)=><tr key={String(c.id??c.case_id??i)}><td style={td}><Link id={String(c.animal_id||'')} open={openPassport}/></td><td style={td}>{c.diagnosis||c.notes||'Unspecified'}</td><td style={td}>{c.severity||'NORMAL'}</td><td style={td}>{d(c.follow_up_due_at)||'â€”'}</td><td style={td}>{c.status||'OPEN'}</td><td style={td}><button disabled={saving} onClick={()=>void resolve(c)} style={btn('#166534')}><CheckCircle2 size={12}/>Declare Healthy</button></td></tr>)}</tbody></table></section>
 <section style={{...card,marginBottom:12,overflowX:'auto'}}><div style={{padding:12,display:'flex',justifyContent:'space-between',gap:8,flexWrap:'wrap'}}><strong>Complete Clinical Log</strong><SearchBox value={search} set={setSearch} placeholder="Search animal, illness, medicine, vet"/></div><table style={{width:'100%',minWidth:940,borderCollapse:'collapse',fontSize:11}}><thead><tr><th style={th}>Date</th><th style={th}>Animal</th><th style={th}>Type</th><th style={th}>Diagnosis / Detail</th><th style={th}>Medicine</th><th style={th}>Veterinarian</th><th style={th}>Withdrawal</th><th style={th}>State</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td style={td}>{r.date}</td><td style={td}><Link id={r.animalId} open={openPassport}/></td><td style={td}>{r.kind}</td><td style={td}>{r.detail}</td><td style={td}>{r.medicine}</td><td style={td}>{r.veterinarian}</td><td style={td}>{r.withdrawalDays>0?<span style={{color:'#fbbf24'}}><AlertTriangle size={12}/> {r.withdrawalDays}d</span>:'None'}</td><td style={td}>{r.active?'Active':'Historical'}</td></tr>)}</tbody></table></section>
 <section style={{...card,padding:12,marginBottom:12}}><strong>Health Analytics</strong><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,marginTop:10}}><Stats title="Most Recorded Illnesses / Diagnoses" rows={illness}/><Stats title="Most Used Medicines" rows={meds}/><Stats title="Management Signals" rows={[['Active cases',active.length],['Follow-ups due',overdueFollow],['Withdrawal animals',withdrawals]]}/></div></section>
 {show&&<Modal close={()=>setShow(false)}><form onSubmit={save} style={{display:'grid',gap:10}}><strong>Record Clinical Treatment</strong><Field label="Animal"><select required value={animal} onChange={e=>setAnimal(e.target.value)} style={field}>{herdMasterList.map(a=><option key={a.id} value={a.id}>{a.id} Â· {a.category}</option>)}</select></Field><Field label="Veterinarian"><input value={vet} onChange={e=>setVet(e.target.value)} style={field} placeholder="Enter veterinarian"/></Field><Field label="Diagnosis / Condition"><select required value={diagnosis} onChange={e=>setDiagnosis(e.target.value)} style={field}><option value="">Select standard diagnosis</option>{DIAGNOSES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Medication Administered"><select required value={medicine} onChange={e=>setMedicine(e.target.value)} style={field}><option value="">Select medicine</option>{MEDICINES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Dose / Frequency"><input value={dose} onChange={e=>setDose(e.target.value)} style={field}/></Field><Field label="Route"><input value={route} onChange={e=>setRoute(e.target.value)} style={field}/></Field><Field label="Milk Withdrawal Days"><input type="number" min="0" value={withdrawal} onChange={e=>setWithdrawal(e.target.value)} style={field}/></Field><Field label="Severity"><select value={severity} onChange={e=>setSeverity(e.target.value)} style={field}><option>NORMAL</option><option>LOW</option><option>MODERATE</option><option>SEVERE</option><option>CRITICAL</option></select></Field><Field label="Follow-up Due"><input type="datetime-local" value={follow} onChange={e=>setFollow(e.target.value)} style={field}/></Field><button disabled={saving} style={btn('#dc2626')}>Save Treatment</button></form></Modal>}
 {passport&&<AnimalPassportModal animalId={passport} onClose={()=>setPassport(null)}/>}</div>
}
function Header({title,subtitle,action}:{title:string;subtitle:string;action:React.ReactNode}){return <div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',flexWrap:'wrap',marginBottom:12}}><div><h2 style={{margin:0,color:'#ef4444',display:'flex',gap:7,alignItems:'center'}}><HeartPulse size={20}/>{title}</h2><div style={{fontSize:11,color:'#94a3b8'}}>{subtitle}</div></div>{action}</div>}
function Metric({title,value}:{title:string;value:React.ReactNode}){return <div style={card}><div style={{padding:11}}><div style={{fontSize:9,color:'#94a3b8',fontWeight:800,textTransform:'uppercase'}}>{title}</div><div style={{fontSize:20,fontWeight:900,marginTop:3}}>{value}</div></div></div>}
function Notice({text,error=false}:{text:string;error?:boolean}){return <div style={{background:error?'#450a0a':'#064e3b',color:error?'#fecaca':'#a7f3d0',padding:9,borderRadius:6,marginBottom:10,fontSize:11}}>{text}</div>}
function SearchBox({value,set,placeholder}:{value:string;set:(x:string)=>void;placeholder:string}){return <div style={{position:'relative',minWidth:250}}><Search size={13} style={{position:'absolute',left:9,top:10,color:'#64748b'}}/><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} style={{...field,paddingLeft:28}}/></div>}
function Link({id,open}:{id:string;open:(id:string)=>void}){return <button onClick={()=>open(id)} style={{background:'none',border:0,color:'#7dd3fc',fontWeight:800,cursor:'pointer'}}>#{id}</button>}
function Stats({title,rows}:{title:string;rows:Array<[string,number]>}){return <div style={{background:'#0f172a',border:'1px solid #1f2937',borderRadius:6,padding:10}}><div style={{fontSize:10,color:'#94a3b8',fontWeight:900}}>{title}</div>{rows.map(([n,c])=><div key={n} style={{display:'flex',justifyContent:'space-between',borderTop:'1px solid #1f2937',padding:'5px 0',fontSize:10}}><span>{n}</span><strong>{c}</strong></div>)}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{fontSize:10,color:'#94a3b8'}}>{label}{children}</label>}
function Modal({close,children}:{close:()=>void;children:React.ReactNode}){return <div style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(0,0,0,.82)',display:'flex',alignItems:'center',justifyContent:'center',padding:14,overflowY:'auto'}}><div style={{width:'min(620px,100%)',maxHeight:'calc(100vh - 28px)',overflowY:'auto',background:'#111827',border:'1px solid #ef4444',borderRadius:9,padding:18,boxSizing:'border-box',position:'relative'}}><button onClick={close} style={{position:'absolute',right:10,top:10,background:'none',border:0,color:'#fff'}}><X size={18}/></button>{children}</div></div>}
