import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,HeartPulse,Plus,Search,X} from 'lucide-react';
import AnimalPassportModal from './AnimalPassportModal';
import {apiUrl} from '../config/api';

interface HerdAnimal{id:string;breed:string;category:string;status:string}
type CaseRow={id?:number|string;case_id?:number|string;animal_id?:string;status?:string;severity?:string;diagnosis?:string;notes?:string;follow_up_due_at?:string|null;opened_at?:string|null;resolved_at?:string|null;resolution?:string|null};
type ObservationRow={id?:number|string;animal_id?:string;health_case_id?:number|string|null;timestamp?:string;observed_at?:string;date?:string;observation?:string;symptom?:string;severity?:string;reported_by?:string;operator?:string};
type TreatmentRow={id?:number|string;treatment_id?:number|string;animal_id?:string;health_case_id?:number|string|null;treated_at?:string;timestamp?:string;date?:string;diagnosis?:string;notes?:string;medicine?:string;dose?:string;treated_by?:string;operator?:string;milk_withdrawal_days?:number};
type ClinicalRow={id:string;caseRef?:CaseRow;animalId:string;date:string;diagnosis:string;severity:string;symptoms:string;treatment:string;withdrawalDays:number;nextCheck:string;active:boolean};
interface Props{onOpenPassport?:(id:string)=>void;herdMasterList?:HerdAnimal[];onChanged?:()=>void}

const DIAGNOSES=['Mastitis','Metritis / Endometritis','Lameness / Hoof Disorder','Ketosis','Milk Fever / Hypocalcemia','Retained Placenta','Displaced Abomasum','Respiratory Disease / Pneumonia','Diarrhea / Enteritis','Foot Rot','Bloat / Tympany','Ruminal Acidosis','Fever / Pyrexia','Injury / Trauma','Other'];
const MEDICINES=['Oxytetracycline','Penicillin / Streptomycin','Ceftiofur','Amoxicillin / Ampicillin','Flunixin meglumine','Meloxicam','Ketoprofen','Calcium borogluconate','Dextrose / Energy support','Oral / IV electrolytes','Intramammary mastitis treatment','Anthelmintic / Dewormer','Topical antiseptic / wound care','Supportive therapy','Other'];
const field:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#0f172a',color:'#fff',border:'1px solid #334155',padding:'9px 10px',borderRadius:6,fontSize:12};
const card:React.CSSProperties={background:'#111827',border:'1px solid #1f2937',borderRadius:8,minWidth:0};
const th:React.CSSProperties={padding:'9px 10px',textAlign:'left',color:'#cbd5e1',fontSize:10,whiteSpace:'nowrap'};
const td:React.CSSProperties={padding:'9px 10px',borderTop:'1px solid #1f2937',verticalAlign:'top'};
const btn=(bg:string):React.CSSProperties=>({background:bg,color:'#fff',border:0,padding:'8px 11px',borderRadius:6,fontWeight:800,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:5,fontSize:11});

function d(v:unknown){if(!v)return'';const x=new Date(String(v));return Number.isNaN(x.getTime())?String(v).slice(0,10):x.toISOString().slice(0,10)}
function ts(v:unknown){if(!v)return 0;const x=new Date(String(v));return Number.isNaN(x.getTime())?0:x.getTime()}
async function get<T>(p:string):Promise<T>{const r=await fetch(apiUrl(p));if(!r.ok)throw new Error(`Request failed: ${r.status}`);return r.json() as Promise<T>}
async function post<T>(p:string,x:unknown):Promise<T>{const r=await fetch(apiUrl(p),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});if(!r.ok){let m=`Request failed: ${r.status}`;try{const b=await r.json() as {detail?:unknown};if(typeof b.detail==='string')m=b.detail}catch{}throw new Error(m)}return r.json() as Promise<T>}
function counts<T>(rows:T[],key:(r:T)=>string){const m=new Map<string,number>();rows.forEach(r=>{const k=key(r).trim()||'Unspecified';m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)}
function caseId(c:CaseRow){return String(c.id??c.case_id??'')}
function belongsToCase(row:{health_case_id?:number|string|null;animal_id?:string},c:CaseRow){const cid=caseId(c);return row.health_case_id!=null?String(row.health_case_id)===cid:String(row.animal_id||'')===String(c.animal_id||'')}
function inCaseWindow(value:unknown,c:CaseRow){const time=ts(value),opened=ts(c.opened_at),resolved=ts(c.resolved_at);if(!time)return true;if(opened&&time<opened)return false;if(resolved&&time>resolved)return false;return true}

export default function HealthTab({onOpenPassport,herdMasterList=[],onChanged}:Props){
 const [cases,setCases]=useState<CaseRow[]>([]),[observations,setObservations]=useState<ObservationRow[]>([]),[treatments,setTreatments]=useState<TreatmentRow[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[show,setShow]=useState(false),[passport,setPassport]=useState<string|null>(null);
 const [animal,setAnimal]=useState(herdMasterList[0]?.id||''),[diagnosis,setDiagnosis]=useState(''),[symptoms,setSymptoms]=useState(''),[medicine,setMedicine]=useState(''),[vet,setVet]=useState(''),[withdrawal,setWithdrawal]=useState('0'),[dose,setDose]=useState(''),[route,setRoute]=useState(''),[severity,setSeverity]=useState('NORMAL'),[follow,setFollow]=useState('');
 useEffect(()=>{if(herdMasterList.length&&!herdMasterList.some(a=>a.id===animal))setAnimal(herdMasterList[0].id)},[herdMasterList,animal]);
 const openPassport=(id:string)=>onOpenPassport?onOpenPassport(id):setPassport(id);

 const load=async()=>{setLoading(true);setError('');try{const [cp,obs,trt]=await Promise.all([get<{cases?:CaseRow[]}>('/farm/health-cases'),get<ObservationRow[]>('/farm/health-observations'),get<TreatmentRow[]>('/farm/treatments')]);setCases(Array.isArray(cp?.cases)?cp.cases:[]);setObservations(Array.isArray(obs)?obs:[]);setTreatments(Array.isArray(trt)?trt:[])}catch(e){setError(e instanceof Error?e.message:'Unable to load Health.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[herdMasterList]);

 const active=useMemo(()=>cases.filter(c=>String(c.status||'').toUpperCase()!=='RESOLVED'),[cases]);
 const clinicalRows=useMemo<ClinicalRow[]>(()=>{
   const rows:ClinicalRow[]=[];
   const usedTreatments=new Set<string>();
   for(const c of cases){
     const cid=caseId(c);
     const obs=observations.filter(x=>belongsToCase(x,c)&&inCaseWindow(x.timestamp||x.observed_at||x.date,c));
     const trt=treatments.filter(x=>belongsToCase(x,c)&&inCaseWindow(x.treated_at||x.timestamp||x.date,c));
     trt.forEach(x=>usedTreatments.add(String(x.treatment_id??x.id??'')));
     const details=[String(c.notes||'').trim(),...obs.map(x=>String(x.symptom||x.observation||'').trim())].filter(Boolean);
     const uniqueDetails=[...new Set(details)];
     const treatmentText=trt.map(x=>[x.medicine,x.dose].filter(Boolean).join(' · ')).filter(Boolean).join('; ');
     const withdrawalDays=trt.reduce((m,x)=>Math.max(m,Number(x.milk_withdrawal_days||0)),0);
     const firstTreatment=trt[0];
     rows.push({id:`CASE-${cid||c.animal_id}`,caseRef:c,animalId:String(c.animal_id||''),date:d(c.opened_at||firstTreatment?.treated_at||firstTreatment?.timestamp||firstTreatment?.date),diagnosis:String(c.diagnosis||firstTreatment?.diagnosis||'Unspecified'),severity:String(c.severity||'NORMAL'),symptoms:uniqueDetails.join('; ')||'—',treatment:treatmentText||'—',withdrawalDays,nextCheck:d(c.follow_up_due_at),active:String(c.status||'').toUpperCase()!=='RESOLVED'});
   }
   for(const x of treatments){
     const tid=String(x.treatment_id??x.id??'');if(tid&&usedTreatments.has(tid))continue;
     rows.push({id:`TRT-${tid||rows.length}`,animalId:String(x.animal_id||''),date:d(x.treated_at||x.timestamp||x.date),diagnosis:String(x.diagnosis||x.notes||'Unspecified'),severity:'—',symptoms:String(x.notes||'—'),treatment:[x.medicine,x.dose].filter(Boolean).join(' · ')||'—',withdrawalDays:Number(x.milk_withdrawal_days||0),nextCheck:'',active:false});
   }
   return rows.sort((a,b)=>b.date.localeCompare(a.date));
 },[cases,observations,treatments]);

 const withdrawals=useMemo(()=>new Set(clinicalRows.filter(r=>r.active&&r.withdrawalDays>0).map(r=>r.animalId)).size,[clinicalRows]);
 const overdueFollow=useMemo(()=>active.filter(c=>{const x=d(c.follow_up_due_at);return x&&x<=new Date().toISOString().slice(0,10)}).length,[active]);
 const recent=useMemo(()=>{const cut=new Date();cut.setDate(cut.getDate()-7);return clinicalRows.filter(r=>r.date&&new Date(r.date)>=cut).length},[clinicalRows]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?clinicalRows.filter(r=>`${r.animalId} ${r.diagnosis} ${r.symptoms} ${r.treatment}`.toLowerCase().includes(q)):clinicalRows},[clinicalRows,search]);
 const illness=useMemo(()=>counts(clinicalRows,r=>r.diagnosis),[clinicalRows]);
 const meds=useMemo(()=>counts(clinicalRows.filter(r=>r.treatment!=='—'),r=>r.treatment.split(' · ')[0]),[clinicalRows]);

 const resolve=async(c:CaseRow)=>{const id=caseId(c),aid=String(c.animal_id||'');if(!id)return setError('Missing clinical case ID.');if(!confirm(`Mark ${aid} healthy and close clinical case ${id}?`))return;setSaving(true);setError('');try{await post(`/farm/health-cases/${encodeURIComponent(id)}/resolve`,{resolution:'Marked healthy after clinical recovery.',resolved_by:vet||'Operator UI',operator:vet||'Operator UI'});setMessage(`${aid} marked healthy. Health history and Animal Passport record retained; active Dashboard case cleared.`);await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to mark animal healthy.')}finally{setSaving(false)}};

 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const hc=await post<any>('/farm/health-cases',{animal_id:animal,severity,diagnosis,notes:symptoms||diagnosis,follow_up_due_at:follow||null,operator:vet||'Operator UI'});if(symptoms.trim()){await post('/farm/health-observations',{animal_id:animal,observation:symptoms,symptom:symptoms,severity,health_case_id:hc.id??hc.case_id,operator:vet||'Operator UI'})}await post('/farm/treatments',{animal_id:animal,medicine,diagnosis,treated_by:vet||null,milk_withdrawal_days:Number(withdrawal||0),notes:symptoms||diagnosis,operator:vet||'Operator UI',dose:[dose,route].filter(Boolean).join(' / ')||null,health_case_id:hc.id??hc.case_id});setShow(false);setDiagnosis('');setSymptoms('');setMedicine('');setWithdrawal('0');setDose('');setRoute('');setSeverity('NORMAL');setFollow('');setMessage('Clinical case and treatment recorded and linked to the Animal Passport.');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to save treatment.')}finally{setSaving(false)}};

 return <div style={{padding:16,color:'#fff',height:'100%',overflowY:'auto',boxSizing:'border-box'}}><Header title="Clinical Health" subtitle="Reactive care: identify illness, treat, follow up, recover." action={<button onClick={()=>setShow(true)} style={btn('#b91c1c')}><Plus size={14}/>Record Treatment</button>}/>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:8,marginBottom:12}}><Metric title="Active Sick Animals" value={new Set(active.map(c=>c.animal_id)).size}/><Metric title="Follow-ups Due / Overdue" value={overdueFollow}/><Metric title="Animals in Milk Withdrawal" value={withdrawals}/><Metric title="Clinical Events — 7 Days" value={recent}/></div>
 {error&&<Notice error text={error}/>} {message&&<Notice text={message}/>}
 <section style={{...card,marginBottom:12,overflowX:'auto'}}><div style={{padding:12,display:'flex',justifyContent:'space-between',gap:8,flexWrap:'wrap'}}><strong>Complete Clinical Log</strong><SearchBox value={search} set={setSearch} placeholder="Search animal, diagnosis, symptoms, treatment"/></div><table style={{width:'100%',minWidth:1180,borderCollapse:'collapse',fontSize:11}}><thead><tr><th style={th}>Date</th><th style={th}>Animal ID</th><th style={th}>Diagnosis</th><th style={th}>Severity</th><th style={th}>Symptoms & Details</th><th style={th}>Treatment</th><th style={th}>Withdrawal</th><th style={th}>Next Check-up</th></tr></thead><tbody>{!loading&&filtered.map(r=><tr key={r.id}><td style={td}>{r.date||'—'}</td><td style={td}><Link id={r.animalId} open={openPassport}/></td><td style={td}>{r.diagnosis}</td><td style={td}>{r.severity}</td><td style={{...td,maxWidth:320}}>{r.symptoms}</td><td style={{...td,maxWidth:280}}>{r.treatment}</td><td style={td}>{r.withdrawalDays>0?<span style={{color:'#fbbf24',display:'inline-flex',gap:4,alignItems:'center'}}><AlertTriangle size={12}/>{r.withdrawalDays}d</span>:'None'}</td><td style={td}>{r.nextCheck||'—'}</td></tr>)}</tbody></table>
 <div style={{padding:12,borderTop:'1px solid #1f2937'}}><div style={{fontSize:10,color:'#94a3b8',fontWeight:900,marginBottom:7}}>Mark Healthy</div>{active.length===0?<div style={{fontSize:10,color:'#64748b'}}>No active clinical cases.</div>:<div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{active.map((c,i)=><button key={String(c.id??c.case_id??i)} disabled={saving} onClick={()=>void resolve(c)} style={btn('#166534')}><CheckCircle2 size={12}/>Mark Healthy #{String(c.animal_id||'')}</button>)}</div>}</div></section>
 <section style={{...card,padding:12,marginBottom:12}}><strong>Health Analytics</strong><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,marginTop:10}}><Stats title="Most Recorded Illnesses / Diagnoses" rows={illness}/><Stats title="Most Used Treatments" rows={meds}/><Stats title="Management Signals" rows={[['Active cases',active.length],['Follow-ups due',overdueFollow],['Withdrawal animals',withdrawals]]}/></div></section>
 {show&&<Modal close={()=>setShow(false)}><form onSubmit={save} style={{display:'grid',gap:10}}><strong>Record Clinical Treatment</strong><Field label="Animal"><select required value={animal} onChange={e=>setAnimal(e.target.value)} style={field}>{herdMasterList.map(a=><option key={a.id} value={a.id}>{a.id} · {a.category}</option>)}</select></Field><Field label="Veterinarian"><input value={vet} onChange={e=>setVet(e.target.value)} style={field} placeholder="Enter veterinarian"/></Field><Field label="Diagnosis / Condition"><select required value={diagnosis} onChange={e=>setDiagnosis(e.target.value)} style={field}><option value="">Select standard diagnosis</option>{DIAGNOSES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Symptoms & Details"><textarea required value={symptoms} onChange={e=>setSymptoms(e.target.value)} style={{...field,minHeight:72}} placeholder="Clinical signs, observations and relevant details"/></Field><Field label="Medication Administered"><select required value={medicine} onChange={e=>setMedicine(e.target.value)} style={field}><option value="">Select medicine</option>{MEDICINES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Dose / Frequency"><input value={dose} onChange={e=>setDose(e.target.value)} style={field}/></Field><Field label="Route"><input value={route} onChange={e=>setRoute(e.target.value)} style={field}/></Field><Field label="Milk Withdrawal Days"><input type="number" min="0" value={withdrawal} onChange={e=>setWithdrawal(e.target.value)} style={field}/></Field><Field label="Severity"><select value={severity} onChange={e=>setSeverity(e.target.value)} style={field}><option>NORMAL</option><option>LOW</option><option>MODERATE</option><option>SEVERE</option><option>CRITICAL</option></select></Field><Field label="Next Check-up"><input type="datetime-local" value={follow} onChange={e=>setFollow(e.target.value)} style={field}/></Field><button disabled={saving} style={btn('#dc2626')}>Save Treatment</button></form></Modal>}
 {passport&&<AnimalPassportModal animalId={passport} onClose={()=>setPassport(null)}/>}</div>
}

function Header({title,subtitle,action}:{title:string;subtitle:string;action:React.ReactNode}){return <div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',flexWrap:'wrap',marginBottom:12}}><div><h2 style={{margin:0,color:'#ef4444',display:'flex',gap:7,alignItems:'center'}}><HeartPulse size={20}/>{title}</h2><div style={{fontSize:11,color:'#94a3b8'}}>{subtitle}</div></div>{action}</div>}
function Metric({title,value}:{title:string;value:React.ReactNode}){return <div style={card}><div style={{padding:11}}><div style={{fontSize:9,color:'#94a3b8',fontWeight:800,textTransform:'uppercase'}}>{title}</div><div style={{fontSize:20,fontWeight:900,marginTop:3}}>{value}</div></div></div>}
function Notice({text,error=false}:{text:string;error?:boolean}){return <div style={{background:error?'#450a0a':'#064e3b',color:error?'#fecaca':'#a7f3d0',padding:9,borderRadius:6,marginBottom:10,fontSize:11}}>{text}</div>}
function SearchBox({value,set,placeholder}:{value:string;set:(x:string)=>void;placeholder:string}){return <div style={{position:'relative',minWidth:250}}><Search size={13} style={{position:'absolute',left:9,top:10,color:'#64748b'}}/><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} style={{...field,paddingLeft:28}}/></div>}
function Link({id,open}:{id:string;open:(id:string)=>void}){return <button onClick={()=>open(id)} style={{background:'none',border:0,color:'#7dd3fc',fontWeight:800,cursor:'pointer'}}>#{id}</button>}
function Stats({title,rows}:{title:string;rows:Array<[string,number]>}){return <div style={{background:'#0f172a',border:'1px solid #1f2937',borderRadius:6,padding:10}}><div style={{fontSize:10,color:'#94a3b8',fontWeight:900}}>{title}</div>{rows.map(([n,c])=><div key={n} style={{display:'flex',justifyContent:'space-between',borderTop:'1px solid #1f2937',padding:'5px 0',fontSize:10}}><span>{n}</span><strong>{c}</strong></div>)}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{fontSize:10,color:'#94a3b8',display:'grid',gap:4}}>{label}{children}</label>}
function Modal({close,children}:{close:()=>void;children:React.ReactNode}){return <div style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(0,0,0,.82)',display:'flex',alignItems:'center',justifyContent:'center',padding:14,overflowY:'auto'}}><div style={{width:'min(620px,100%)',maxHeight:'calc(100vh - 28px)',overflowY:'auto',background:'#111827',border:'1px solid #ef4444',borderRadius:9,padding:18,boxSizing:'border-box',position:'relative'}}><button onClick={close} style={{position:'absolute',right:10,top:10,background:'none',border:0,color:'#fff'}}><X size={18}/></button>{children}</div></div>}
