import React, { useEffect, useState } from 'react';
import { MainAppShell } from '../App';
import HumanOperatorConsole from './HumanOperatorConsole';
import { API_BASE_URL } from '../config/api';

const API = API_BASE_URL || '';
const HUMAN_SESSION_KEY = 'dairyos.human.session';
type Group = { id: string; label: string };
type Person = { id: number; display_name: string; entry_group: string; role: string; pin_set: boolean; active: boolean };

export default function HumanAccessGate() {
  const [state, setState] = useState<'loading' | 'bootstrap' | 'login' | 'management' | 'operator' | 'error'>('loading');
  const [identity, setIdentity] = useState<Person | null>(null);
  const [groups, setGroups] = useState<Group[]>([]); const [group, setGroup] = useState('MANAGEMENT'); const [people, setPeople] = useState<Person[]>([]); const [personId, setPersonId] = useState('');
  const [pin, setPin] = useState(''); const [name, setName] = useState(''); const [confirmPin, setConfirmPin] = useState(''); const [setupCode, setSetupCode] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { try { const response = await fetch(`${API}/human-access/status`); if (!response.ok) throw new Error('Unable to resolve DairyOS access state.'); const status = await response.json(); setGroups(status.entry_groups || []); const existing = sessionStorage.getItem(HUMAN_SESSION_KEY); if (existing) { const me = await fetch(`${API}/human-access/me`, { headers: { 'X-DairyOS-Human-Session': existing } }); if (me.ok) { const body = await me.json(); setIdentity(body.identity); setState(body.identity?.entry_group === 'MANAGEMENT' ? 'management' : 'operator'); return; } sessionStorage.removeItem(HUMAN_SESSION_KEY); } setState(status.bootstrap_required ? 'bootstrap' : 'login'); } catch (error) { setMessage(error instanceof Error ? error.message : 'DairyOS access initialization failed.'); setState('error'); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (state !== 'login') return; void fetch(`${API}/human-access/people?entry_group=${encodeURIComponent(group)}`).then(response => response.json()).then(payload => { const rows = payload.people || []; setPeople(rows); setPersonId(rows[0] ? String(rows[0].id) : ''); }).catch(() => setMessage('Unable to load active people.')); }, [group, state]);
  const bootstrap = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); const response = await fetch(`${API}/human-access/bootstrap`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ display_name: name, pin, pin_confirmation: confirmPin }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setMessage(payload.detail || 'Primary Administrator setup failed.'); return; } setMessage('Primary Administrator created.'); setPin(''); setConfirmPin(''); setState('login'); };
  const login = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); const selected = people.find(person => String(person.id) === personId); if (!selected) { setMessage('Select a person.'); return; } if (!selected.pin_set) { const setup = await fetch(`${API}/human-access/people/${selected.id}/pin/initial`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ setup_code: setupCode, pin, pin_confirmation: confirmPin }) }); const setupPayload = await setup.json().catch(() => ({})); if (!setup.ok) { setMessage(setupPayload.detail || 'Initial PIN setup failed.'); return; } } const response = await fetch(`${API}/human-access/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ identity_id: Number(personId), pin }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setMessage(payload.detail || 'Unable to authenticate.'); return; } sessionStorage.setItem(HUMAN_SESSION_KEY, payload.session_token); setIdentity(payload.identity); setPin(''); setConfirmPin(''); setSetupCode(''); setState(payload.identity?.entry_group === 'MANAGEMENT' ? 'management' : 'operator'); };
  const logout = async () => { await fetch(`${API}/human-access/logout`, { method: 'POST' }); sessionStorage.removeItem(HUMAN_SESSION_KEY); setIdentity(null); setState('login'); };
  if (state === 'management') return <MainAppShell />; if (state === 'operator' && identity) return <HumanOperatorConsole identity={identity} onLogout={() => void logout()} />; if (state === 'loading') return <div style={screen}>Loading DairyOS access…</div>; if (state === 'error') return <div style={screen}><h2>DairyOS access unavailable</h2><p>{message}</p></div>;
  if (state === 'bootstrap') return <form onSubmit={bootstrap} style={card}><h1>Primary Administrator setup</h1><p>Establish the first DairyOS administrator. Do not share the PIN.</p><input aria-label="Administrator name" placeholder="Name" value={name} onChange={e => setName(e.target.value)} required /><input aria-label="Administrator PIN" type="password" inputMode="numeric" maxLength={4} placeholder="Four-digit PIN" value={pin} onChange={e => setPin(e.target.value)} required /><input aria-label="Confirm administrator PIN" type="password" inputMode="numeric" maxLength={4} placeholder="Confirm PIN" value={confirmPin} onChange={e => setConfirmPin(e.target.value)} required /><button type="submit">Create Primary Administrator</button>{message && <p role="alert">{message}</p>}</form>;
  const selected = people.find(person => String(person.id) === personId); const needsSetup = Boolean(selected && !selected.pin_set);
  return <form onSubmit={login} style={card}><h1>DairyOS access</h1>{groups.map(item => <button key={item.id} type="button" onClick={() => setGroup(item.id)} style={group === item.id ? activeGroup : groupButton}><strong>{item.id === 'MANAGEMENT' ? 'DAIRYOS MANAGEMENT' : item.id === 'MILK_OPERATOR' ? 'MILK OPERATOR' : 'ACCOUNTS OPERATOR'}</strong><span>{item.label}</span></button>)}<label>Person<select value={personId} onChange={e => setPersonId(e.target.value)} required><option value="">Select person</option>{people.map(person => <option key={person.id} value={person.id}>{person.display_name}{person.pin_set ? '' : ' — PIN NOT YET SET'}</option>)}</select></label>{needsSetup && <input aria-label="One-time PIN setup code" value={setupCode} onChange={e => setSetupCode(e.target.value)} placeholder="One-time setup code" required /> }<input aria-label="PIN" type="password" inputMode="numeric" maxLength={4} placeholder={needsSetup ? 'Create four-digit PIN' : 'PIN'} value={pin} onChange={e => setPin(e.target.value)} required />{needsSetup && <input aria-label="Confirm PIN" type="password" inputMode="numeric" maxLength={4} placeholder="Confirm PIN" value={confirmPin} onChange={e => setConfirmPin(e.target.value)} required />}<button type="submit">{needsSetup ? 'Set PIN and continue' : 'Continue'}</button>{message && <p role="alert">{message}</p>}</form>;
}
const screen: React.CSSProperties = { minHeight: '100vh', display: 'grid', placeItems: 'center', background: '#0b0f19', color: '#f8fafc', fontFamily: 'sans-serif' };
const card: React.CSSProperties = { ...screen, display: 'flex', flexDirection: 'column', gap: 12, padding: 32 };
const groupButton: React.CSSProperties = { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 3, padding: 12, background: '#1e293b', color: '#fff', border: '1px solid #475569', borderRadius: 8 };
const activeGroup: React.CSSProperties = { ...groupButton, background: '#0369a1', borderColor: '#38bdf8' };
