import React, { useEffect, useMemo, useState } from 'react';
import { MainAppShell } from '../App';
import HumanOperatorConsole from './HumanOperatorConsole';
import { API_BASE_URL } from '../config/api';

const API = API_BASE_URL || '';
const HUMAN_SESSION_KEY = 'dairyos.human.session';
type Person = { id: number; display_name: string; entry_group: string; role: string; pin_set: boolean; active: boolean };
type GateState = 'loading' | 'bootstrap' | 'welcome' | 'pin' | 'management' | 'operator' | 'help' | 'error';
const initials = (name: string) => name.trim().split(/\s+/).slice(0, 2).map(part => part[0]?.toUpperCase() || '').join('');
const logoFrame: React.CSSProperties = { display: 'grid', placeItems: 'center', width: 42, height: 42, flex: '0 0 42px', borderRadius: 11, overflow: 'hidden', background: '#0284c7' };
const logo: React.CSSProperties = { display: 'block', width: 30, height: 30, maxWidth: 30, maxHeight: 30, objectFit: 'contain' };

export default function HumanAccessGate() {
  const [state, setState] = useState<GateState>('loading'); const [identity, setIdentity] = useState<Person | null>(null); const [people, setPeople] = useState<Person[]>([]); const [selected, setSelected] = useState<Person | null>(null); const [name, setName] = useState(''); const [pin, setPin] = useState(''); const [confirmPin, setConfirmPin] = useState(''); const [message, setMessage] = useState(''); const [search, setSearch] = useState(''); const [clock, setClock] = useState(new Date()); const [wallpaper, setWallpaper] = useState<string | null>(null);
  const load = async () => { try { const statusResponse = await fetch(`${API}/human-access/status`); if (!statusResponse.ok) throw new Error('Unable to resolve DairyOS access state.'); const status = await statusResponse.json(); const wallpaperResponse = await fetch(`${API}/settings/welcome-screen`); if (wallpaperResponse.ok) { const wallpaperPayload = await wallpaperResponse.json(); setWallpaper(typeof wallpaperPayload.wallpaper === 'string' ? wallpaperPayload.wallpaper : null); } const existing = sessionStorage.getItem(HUMAN_SESSION_KEY); if (existing) { const me = await fetch(`${API}/human-access/me`, { headers: { 'X-DairyOS-Human-Session': existing } }); if (me.ok) { const body = await me.json(); setIdentity(body.identity); setState(body.identity?.entry_group === 'MANAGEMENT' ? 'management' : 'operator'); return; } sessionStorage.removeItem(HUMAN_SESSION_KEY); } if (status.bootstrap_required) { setState('bootstrap'); return; } const response = await fetch(`${API}/human-access/people`); const payload = await response.json(); setPeople(payload.people || []); setState('welcome'); } catch (error) { setMessage(error instanceof Error ? error.message : 'DairyOS access initialization failed.'); setState('error'); } };
  useEffect(() => { void load(); }, []); useEffect(() => { const timer = window.setInterval(() => setClock(new Date()), 1000); return () => window.clearInterval(timer); }, []);
  const filteredPeople = useMemo(() => people.filter(person => person.display_name.toLowerCase().includes(search.toLowerCase())), [people, search]);
  const choose = (person: Person) => { setSelected(person); setPin(''); setConfirmPin(''); setMessage(''); setState('pin'); };
  const bootstrap = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); const response = await fetch(`${API}/human-access/bootstrap`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ display_name: name, pin, pin_confirmation: confirmPin }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setMessage(payload.detail || 'Primary Administrator setup failed.'); return; } setPin(''); setConfirmPin(''); await load(); };
  const login = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; setMessage(''); if (!selected.pin_set) { const setup = await fetch(`${API}/human-access/people/${selected.id}/pin/initial`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pin, pin_confirmation: confirmPin }) }); const setupPayload = await setup.json().catch(() => ({})); if (!setup.ok) { setMessage(setupPayload.detail || 'Initial PIN setup failed.'); return; } } const response = await fetch(`${API}/human-access/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ identity_id: selected.id, pin }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setMessage(payload.detail || 'Unable to authenticate.'); return; } sessionStorage.setItem(HUMAN_SESSION_KEY, payload.session_token); setIdentity(payload.identity); setPin(''); setConfirmPin(''); setState(payload.identity?.entry_group === 'MANAGEMENT' ? 'management' : 'operator'); };
  const logout = async () => { const token = sessionStorage.getItem(HUMAN_SESSION_KEY); await fetch(`${API}/human-access/logout`, { method: 'POST', headers: token ? { 'X-DairyOS-Human-Session': token } : {} }); sessionStorage.removeItem(HUMAN_SESSION_KEY); setIdentity(null); setSelected(null); await load(); };
  if (state === 'management') return <MainAppShell />; if (state === 'operator' && identity) return <HumanOperatorConsole identity={identity} onLogout={() => void logout()} />; if (state === 'loading') return <div style={screen}>Loading DairyOS access…</div>; if (state === 'error') return <div style={screen}><div style={panel}><h2>DairyOS access unavailable</h2><p>{message}</p></div></div>;
  if (state === 'bootstrap') return <form onSubmit={bootstrap} style={screen}><div style={panel}><Brand /><h1>Set up DairyOS</h1><p>Establish the first Primary Administrator. Do not share the PIN.</p><input aria-label="Administrator name" placeholder="Your name" value={name} onChange={e => setName(e.target.value)} required /><input aria-label="Administrator PIN" type="password" inputMode="numeric" maxLength={4} placeholder="Four-digit PIN" value={pin} onChange={e => setPin(e.target.value)} required /><input aria-label="Confirm administrator PIN" type="password" inputMode="numeric" maxLength={4} placeholder="Confirm PIN" value={confirmPin} onChange={e => setConfirmPin(e.target.value)} required /><button type="submit">Create Primary Administrator</button>{message && <p role="alert">{message}</p>}</div></form>;
  if (state === 'help') return <HelpFlow onBack={() => { setMessage(''); setState('welcome'); }} />;
  if (state === 'pin' && selected) return <form onSubmit={login} style={screen}><div style={panel}><Brand /><button type="button" style={back} onClick={() => setState('welcome')}>← Back</button><div style={avatar}>{initials(selected.display_name)}</div><h1>Welcome, {selected.display_name}</h1><p>{selected.pin_set ? 'Enter your PIN to continue.' : 'Create your four-digit PIN to continue.'}</p><input aria-label="PIN" type="password" inputMode="numeric" maxLength={4} placeholder="PIN" value={pin} onChange={e => setPin(e.target.value)} required />{!selected.pin_set && <input aria-label="Confirm PIN" type="password" inputMode="numeric" maxLength={4} placeholder="Confirm PIN" value={confirmPin} onChange={e => setConfirmPin(e.target.value)} required />}<button type="submit">Continue</button>{message && <p role="alert">{message}</p>}<button type="button" style={linkButton} onClick={() => setState('help')}>Need help? Contact Administrator</button></div></form>;
  return <div style={{ ...screen, backgroundImage: wallpaper ? `linear-gradient(rgba(4,22,44,.58),rgba(4,22,44,.82)),url(${wallpaper})` : undefined }}><div style={hero}><Brand /><div style={date}>{clock.toLocaleDateString('en-PK', { dateStyle: 'full' })}<br />{clock.toLocaleTimeString('en-PK')}</div><h1>Welcome to DairyOS</h1><p>Select your name to continue</p><input aria-label="Find your name" placeholder="Find your name..." value={search} onChange={e => setSearch(e.target.value)} /><div style={grid}>{filteredPeople.map(person => <button type="button" key={person.id} style={identityCard} onClick={() => choose(person)}><span style={avatar}>{initials(person.display_name)}</span><strong>{person.display_name}</strong></button>)}</div>{filteredPeople.length === 0 && <p>No active identities found.</p>}<button type="button" style={linkButton} onClick={() => setState('help')}>Need help? Contact Administrator</button><footer>BETTER DATA • BETTER DECISIONS • A STRONGER DAIRY FUTURE</footer></div></div>;
}
function Brand() { return <div style={brand}><span style={logoFrame}><img src="/dairyos-cow.svg" alt="DairyOS" style={logo} /></span><span>DairyOS</span></div>; }
function HelpFlow({ onBack }: { onBack: () => void }) { const [name, setName] = useState(''); const [detail, setDetail] = useState(''); const [message, setMessage] = useState(''); const submit = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch(`${API}/human-access/help`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ display_name: name, message: detail }) }); const payload = await response.json().catch(() => ({})); setMessage(response.ok ? 'Your request was recorded for Administrator review.' : (payload.detail || 'Unable to record the request.')); }; return <form onSubmit={submit} style={screen}><div style={panel}><Brand /><button type="button" style={back} onClick={onBack}>← Back</button><h1>Contact Administrator</h1><p>No PIN reset is performed here. Your request will be recorded for review.</p><input placeholder="Your name" value={name} onChange={e => setName(e.target.value)} required /><textarea placeholder="How can the Administrator help?" value={detail} onChange={e => setDetail(e.target.value)} required /><button type="submit">Send request</button>{message && <p role="status">{message}</p>}</div></form>; }
const screen: React.CSSProperties = { minHeight: '100vh', display: 'grid', placeItems: 'center', padding: 24, boxSizing: 'border-box', background: 'linear-gradient(160deg,#071a35 0%,#0b4771 55%,#0b1d35 100%)', color: '#f8fafc', fontFamily: 'Segoe UI, sans-serif' }; const hero: React.CSSProperties = { width: 'min(980px,100%)', textAlign: 'center', padding: 28 }; const panel: React.CSSProperties = { width: 'min(430px,100%)', display: 'flex', flexDirection: 'column', gap: 13, padding: 30, boxSizing: 'border-box', background: 'rgba(5,20,42,.92)', border: '1px solid rgba(148,211,255,.35)', borderRadius: 18, boxShadow: '0 24px 70px rgba(0,0,0,.3)' }; const brand: React.CSSProperties = { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10, fontSize: 24, fontWeight: 800, marginBottom: 18 }; const date: React.CSSProperties = { opacity: .8, fontSize: 13, lineHeight: 1.6 }; const grid: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(190px,1fr))', gap: 14, margin: '22px 0' }; const identityCard: React.CSSProperties = { display: 'flex', alignItems: 'center', gap: 12, padding: 17, textAlign: 'left', color: '#f8fafc', background: 'rgba(9,40,72,.9)', border: '1px solid rgba(145,212,255,.34)', borderRadius: 14, cursor: 'pointer', fontSize: 16 }; const avatar: React.CSSProperties = { display: 'grid', placeItems: 'center', flex: '0 0 48px', width: 48, height: 48, borderRadius: '50%', background: '#63b8d8', color: '#06233f', fontWeight: 900, fontSize: 17 }; const linkButton: React.CSSProperties = { background: 'transparent', color: '#bde9ff', border: 0, cursor: 'pointer', padding: 7 }; const back: React.CSSProperties = { alignSelf: 'flex-start', background: 'transparent', color: '#bde9ff', border: 0, cursor: 'pointer' };
