import React, { useEffect, useState } from 'react';
import { API_BASE_URL } from '../config/api';
import ReportingTab from './ReportingTab';

type Props = { identity: { display_name: string; role: string; entry_group: string }; onLogout: () => void };
const API = API_BASE_URL || '';
const today = () => new Date().toISOString().slice(0, 10);

export default function HumanOperatorConsole({ identity, onLogout }: Props) {
  const milk = identity.entry_group === 'MILK_OPERATOR';
  const [animals, setAnimals] = useState<any[]>([]); const [animal, setAnimal] = useState(''); const [litres, setLitres] = useState(''); const [disposition, setDisposition] = useState('DOMESTIC_USE'); const [amount, setAmount] = useState(''); const [revenue, setRevenue] = useState(''); const [category, setCategory] = useState('OTHER_OPERATING'); const [showReports, setShowReports] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { if (milk) void fetch(`${API}/farm/animals?active_only=true`).then(r => r.json()).then(rows => setAnimals(Array.isArray(rows) ? rows : rows.value || [])); }, [milk]);
  const submitMilk = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); const next = await fetch(`${API}/farm/milk/next-session?animal_id=${encodeURIComponent(animal)}&operational_date=${today()}`).then(r => r.json()); const session = next.next_session || next.expected_sessions?.[0]; if (!session) { setMessage('No authorized milking session is available.'); return; } const response = await fetch(`${API}/farm/milk`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ animal_id: animal, milking_session: session, morning_yield: session === 'MORNING' ? Number(litres) : null, afternoon_yield: session === 'AFTERNOON' ? Number(litres) : null, evening_yield: session === 'EVENING' ? Number(litres) : null, production_date: today(), operator: identity.display_name }) }); const payload = await response.json().catch(() => ({})); setMessage(response.ok ? 'Milk production recorded.' : (payload.detail || 'Milk recording failed.')); };
  const submitDisposition = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch(`${API}/farm/milk/dispositions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ production_date: today(), disposition_type: disposition, quantity_litres: Number(litres), notes: `Recorded by ${identity.display_name}` }) }); const payload = await response.json().catch(() => ({})); setMessage(response.ok ? `${disposition} recorded.` : (payload.detail || 'Disposition failed.')); };
  const submitExpense = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch(`${API}/farm/finance-ledger`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ transaction_type: 'EXPENSE', master_category: category === 'FEED' ? 'FEED' : 'OPEX', sub_category: category, amount: Number(amount), transaction_date: today(), payment_method: 'CASH', status: 'PAID', notes: `Accounts Operator: ${identity.display_name}` }) }); const payload = await response.json().catch(() => ({})); setMessage(response.ok ? 'Expense recorded.' : (payload.detail || 'Expense recording failed.')); };
  const submitRevenue = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch(`${API}/farm/finance-ledger`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ transaction_type: 'INCOME', master_category: 'REVENUE', sub_category: 'OTHER_REVENUE', amount: Number(revenue), transaction_date: today(), payment_method: 'CASH', status: 'RECEIVED', notes: `Accounts Operator: ${identity.display_name}` }) }); const payload = await response.json().catch(() => ({})); setMessage(response.ok ? 'Revenue recorded.' : (payload.detail || 'Revenue recording failed.')); };
  if (showReports) return <div style={shell}><button type="button" onClick={() => setShowReports(false)} style={button}>Back to Accounts</button><ReportingTab /></div>;
  return <div style={shell}><header style={header}><div><h1>{milk ? 'Milk Operator' : 'Accounts Operator'}</h1><div>{identity.display_name} · {identity.role}</div><small>{new Date().toLocaleString()}</small></div><button type="button" onClick={onLogout} style={button}>Logout</button></header>{message && <div role="status" style={notice}>{message}</div>}<div style={grid}>{milk ? <><section style={card}><h2>ENTER MILK</h2><form onSubmit={submitMilk}><select required value={animal} onChange={e => setAnimal(e.target.value)} style={field}><option value="">Select animal</option>{animals.map(row => <option key={row.animal_id} value={row.animal_id}>{row.ear_tag || row.animal_id}</option>)}</select><input required min="0" type="number" step="0.01" value={litres} onChange={e => setLitres(e.target.value)} placeholder="Litres" style={field}/><button style={button}>Save Milk</button></form></section><section style={card}><h2>DISPOSITIONS</h2><form onSubmit={submitDisposition}><select value={disposition} onChange={e => setDisposition(e.target.value)} style={field}><option value="DOMESTIC_USE">DOMESTIC USE</option><option value="CALF_FEED">CALF FEED</option><option value="WASTAGE">WASTAGE</option></select><input required min="0.01" type="number" step="0.01" value={litres} onChange={e => setLitres(e.target.value)} placeholder="Litres" style={field}/><button style={button}>Record Disposition</button></form></section><section style={card}><h2>Today's Milk Summary</h2><p>Totals remain authoritative in existing Milk management views.</p></section></> : <><section style={card}><h2>RECORD EXPENSE</h2><form onSubmit={submitExpense}><select value={category} onChange={e => setCategory(e.target.value)} style={field}><option value="FEED">FEED</option><option value="HEALTH">HEALTH</option><option value="BREEDING">BREEDING</option><option value="UTILITIES">UTILITIES</option><option value="OTHER_OPERATING">OTHER OPERATING</option></select><input required min="0.01" type="number" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="Amount" style={field}/><button style={button}>Record Expense</button></form></section><section style={card}><h2>RECORD REVENUE</h2><form onSubmit={submitRevenue}><input required min="0.01" type="number" step="0.01" value={revenue} onChange={e => setRevenue(e.target.value)} placeholder="Amount" style={field}/><button style={button}>Record Revenue</button></form></section><section style={card}><h2>RECONCILIATION &amp; AUDIT STATEMENTS</h2><button type="button" style={button} onClick={() => setShowReports(true)}>Open Existing Reports</button></section></>}</div></div>;
}
const shell: React.CSSProperties = { minHeight: '100vh', background: '#0b0f19', color: '#f8fafc', fontFamily: 'sans-serif', padding: 24, boxSizing: 'border-box' }; const header: React.CSSProperties = { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }; const grid: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: 16 }; const card: React.CSSProperties = { background: '#111827', border: '1px solid #1f2937', borderRadius: 10, padding: 18 }; const field: React.CSSProperties = { width: '100%', boxSizing: 'border-box', marginBottom: 10, padding: 10, background: '#1e293b', color: '#fff', border: '1px solid #475569', borderRadius: 6 }; const button: React.CSSProperties = { background: '#0284c7', color: '#fff', border: 0, borderRadius: 6, padding: '10px 12px', fontWeight: 800, cursor: 'pointer' }; const notice: React.CSSProperties = { background: '#064e3b', padding: 10, borderRadius: 6, marginBottom: 16 };
