import React, { useEffect, useMemo, useState } from 'react';
import { Check, Droplets, Edit3, Milk, RefreshCw, Save, Trash2, X } from 'lucide-react';
import { API_BASE_URL } from '../config/api';

const API_BASE=API_BASE_URL||'http://127.0.0.1:8000';
type HerdAnimal={id:string;breed:string;category:string;frequency?:string};
type ProductionRow={id:number;animal_id:string;production_date:string;milking_session?:string|null;session_ledger:boolean;morning_yield?:number|null;afternoon_yield?:number|null;evening_yield?:number|null;total_yield?:number|null;status:string;notes?:string|null};
type DispositionRow={id:number;production_date:string;disposition_type:string;quantity_litres:number;sale_id?:string|null;counterparty?:string|null;selling_price_per_litre?:number|null;amount_due:number;amount_received:number;receivable_outstanding:number;notes?:string|null;status:string};
type Reconciliation={production_date:string;production_complete:boolean;produced_litres:number|null;accounted_litres:number;sold_litres:number;non_sale_accounted_litres:number;unaccounted_litres:number|null;over_accounted_litres:number|null;sale_value:number;cash_received:number;receivable_outstanding:number;status:string};
type NextSession={animal_id:string;milking_frequency?:string;expected_sessions:string[];settled_sessions:string[];next_session:string|null;status:string};
type QualitySample={id:number;quality_date:string;fat_pct:number;snf_pct:number;sample_type:string;notes?:string|null;recorded_by:string;status:string;recorded_at:string;updated_at:string};
type FinanceRow={transaction_type:string;category?:string;amount:number;quantity?:number|null;date?:string|null;status?:string|null};
type Props={initialOpenModal?:boolean;onModalClose?:()=>void;herdMasterList?:HerdAnimal[];onSaveYield?:(addedLiters:number)=>void;realTimeTodaySold?:number};
const inputStyle:React.CSSProperties={background:'#1e293b',color:'#fff',border:'1px solid #334155',padding:'7px 8px',borderRadius:5,fontSize:11,boxSizing:'border-box',width:'100%'};
const buttonStyle=(background:string):React.CSSProperties=>({background,color:'#fff',border:'none',padding:'8px 11px',borderRadius:5,fontSize:10,fontWeight:800,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:5});
const smallButton:React.CSSProperties={background:'#1e293b',border:'1px solid #334155',color:'#cbd5e1',padding:'4px 7px',borderRadius:4,fontSize:9,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:4};
const today=()=>new Date().toISOString().slice(0,10);const litre=(v:number|null|undefined)=>`${Number(v||0).toFixed(1)} L`;
async function request<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API_BASE}${url}`,{headers:{'Content-Type':'application/json'},...init});if(!response.ok){let detail=`Request failed: ${response.status}`;try{const body=await response.json() as {detail?:unknown};if(body.detail)detail=typeof body.detail==='string'?body.detail:JSON.stringify(body.detail);}catch{}throw new Error(detail);}return response.json() as Promise<T>}
const monthBounds=(value:string)=>{const d=new Date(`${value}T12:00:00`),start=new Date(d.getFullYear(),d.getMonth(),1),end=new Date(d.getFullYear(),d.getMonth()+1,0);return {start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10),label:start.toLocaleDateString('en-PK',{month:'long',year:'numeric'})}};
const datesBetween=(start:string,end:string)=>{const out:string[]=[];const d=new Date(`${start}T12:00:00`),last=new Date(`${end}T12:00:00`);while(d<=last){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return out};

export default function MilkTab({initialOpenModal=false,onModalClose,herdMasterList=[],onSaveYield}:Props){
 const [date,setDate]=useState(today()),[monthData,setMonthData]=useState<{production:ProductionRow[];dispositions:DispositionRow[]}>({production:[],dispositions:[]}),[productions,setProductions]=useState<ProductionRow[]>([]),[dispositions,setDispositions]=useState<DispositionRow[]>([]),[reconciliation,setReconciliation]=useState<Reconciliation|null>(null),[dailyRecon,setDailyRecon]=useState<Reconciliation[]>([]),[finance,setFinance]=useState<FinanceRow[]>([]),[qualitySample,setQualitySample]=useState<QualitySample|null>(null),[qualityFat,setQualityFat]=useState(''),[qualitySnf,setQualitySnf]=useState(''),[qualitySampleType,setQualitySampleType]=useState('BULK_TANK'),[qualityNotes,setQualityNotes]=useState('');
 const [productionAnimal,setProductionAnimal]=useState(herdMasterList[0]?.id||''),[nextSession,setNextSession]=useState<NextSession|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[qualitySaving,setQualitySaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[selectedPanel,setSelectedPanel]=useState<'monthProduced'|'monthSold'|'monthRecon'|'dailyProduced'|'dailySold'|'domestic'|'calves'|'wastage'|'dailyRecon'|null>(null);
 const [showProductionForm,setShowProductionForm]=useState(initialOpenModal),[showDispositionForm,setShowDispositionForm]=useState(false),[editingProduction,setEditingProduction]=useState<ProductionRow|null>(null),[editingDisposition,setEditingDisposition]=useState<DispositionRow|null>(null);
 const [productionSession,setProductionSession]=useState(''),[productionLitres,setProductionLitres]=useState(''),[productionNotes,setProductionNotes]=useState(''),[dispositionType,setDispositionType]=useState('SOLD'),[dispositionLitres,setDispositionLitres]=useState(''),[saleId,setSaleId]=useState(''),[counterparty,setCounterparty]=useState(''),[sellingPrice,setSellingPrice]=useState(''),[dispositionNotes,setDispositionNotes]=useState('');
 const bounds=monthBounds(date);
 const load=async()=>{setLoading(true);setError('');try{const [day,month,rec,quality,financeLedger]=await Promise.all([request<{production:ProductionRow[];dispositions:DispositionRow[]}>(`/farm/milk/ledger?start_date=${date}&end_date=${date}`),request<{production:ProductionRow[];dispositions:DispositionRow[]}>(`/farm/milk/ledger?start_date=${bounds.start}&end_date=${bounds.end}`),request<Reconciliation>(`/farm/milk/reconciliation?production_date=${date}`),request<{sample:QualitySample|null}>(`/farm/milk/quality?quality_date=${date}`),request<{transactions:FinanceRow[]}>(`/farm/finance-ledger`)]);setProductions(day.production||[]);setDispositions(day.dispositions||[]);setMonthData({production:month.production||[],dispositions:month.dispositions||[]});setReconciliation(rec);setFinance(financeLedger.transactions||[]);setQualitySample(quality.sample||null);if(quality.sample){setQualityFat(String(quality.sample.fat_pct));setQualitySnf(String(quality.sample.snf_pct));setQualitySampleType(quality.sample.sample_type);setQualityNotes(quality.sample.notes||'')}else{setQualityFat('');setQualitySnf('');setQualitySampleType('BULK_TANK');setQualityNotes('')};const days=datesBetween(bounds.start,bounds.end);const recs=await Promise.all(days.map(d=>request<Reconciliation>(`/farm/milk/reconciliation?production_date=${d}`).catch(()=>null)));setDailyRecon(recs.filter((v):v is Reconciliation=>Boolean(v)));if(productionAnimal){const next=await request<NextSession>(`/farm/milk/next-session?animal_id=${encodeURIComponent(productionAnimal)}&operational_date=${date}`).catch(()=>null);setNextSession(next);if(next)setProductionSession(next.next_session||next.expected_sessions[0]||'')}}catch(err){setError(err instanceof Error?err.message:'Unable to load Milk data.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[date]);useEffect(()=>{if(!productionAnimal&&herdMasterList[0])setProductionAnimal(herdMasterList[0].id)},[herdMasterList,productionAnimal]);
 const monthProduced=monthData.production.filter(r=>r.status!=='VOID').reduce((s,r)=>s+Number(r.total_yield||0),0);
 const financeMilkSold=finance.filter(r=>['INCOME','RECEIPT'].includes(r.transaction_type)&&r.status!=='VOID'&&String(r.category||'').toUpperCase().includes('MILK')).reduce((s,r)=>s+Number(r.quantity||0),0);
 const monthSoldDisposition=monthData.dispositions.filter(r=>r.status!=='VOID'&&r.disposition_type==='SOLD').reduce((s,r)=>s+Number(r.quantity_litres||0),0);
 const monthSold=financeMilkSold||monthSoldDisposition;
 const dispositionTotal=(type:string)=>dispositions.filter(r=>r.status!=='VOID'&&r.disposition_type===type).reduce((s,r)=>s+Number(r.quantity_litres||0),0);
 const soldToday=finance.filter(r=>['INCOME','RECEIPT'].includes(r.transaction_type)&&r.status!=='VOID'&&String(r.category||'').toUpperCase().includes('MILK')&&String(r.date||'').slice(0,10)===date).reduce((s,r)=>s+Number(r.quantity||0),0)||dispositionTotal('SOLD');
 const domestic=dispositionTotal('DOMESTIC_USE'),calves=dispositionTotal('CALF_FEED'),wastage=dispositionTotal('WASTAGE');
 const dailyDifference=Number(reconciliation?.produced_litres||0)-soldToday-domestic-calves-wastage;
 const monthRecon=monthProduced-monthSold-monthData.dispositions.filter(r=>r.status!=='VOID'&&['DOMESTIC_USE','CALF_FEED','WASTAGE'].includes(r.disposition_type)).reduce((s,r)=>s+Number(r.quantity_litres||0),0);
 const click=(p:typeof selectedPanel)=>setSelectedPanel(selectedPanel===p?null:p);
 const resetProduction=()=>{setProductionLitres('');setProductionNotes('');setEditingProduction(null);setShowProductionForm(false);onModalClose?.()};
 const resetDisposition=()=>{setDispositionLitres('');setSaleId('');setCounterparty('');setSellingPrice('');setDispositionNotes('');setEditingDisposition(null);setShowDispositionForm(false)};
 const saveProduction=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const l=Number(productionLitres);if(!(l>0)||!productionAnimal||!productionSession)throw new Error('Animal, expected session and litres are required.');if(editingProduction)await request(`/farm/milk/production/${editingProduction.id}`,{method:'PATCH',body:JSON.stringify({production_date:date,morning_yield:productionSession==='MORNING'?l:editingProduction.morning_yield,afternoon_yield:productionSession==='AFTERNOON'?l:editingProduction.afternoon_yield,evening_yield:productionSession==='EVENING'?l:editingProduction.evening_yield,notes:productionNotes})});else{await request('/farm/milk',{method:'POST',body:JSON.stringify({animal_id:productionAnimal,milking_session:productionSession,morning_yield:productionSession==='MORNING'?l:null,afternoon_yield:productionSession==='AFTERNOON'?l:null,evening_yield:productionSession==='EVENING'?l:null,production_date:date,notes:productionNotes,operator:'WEB'})});if(onSaveYield&&date===today())onSaveYield(l)}setMessage(editingProduction?'Milk production record updated.':'Milk production recorded.');resetProduction();await load()}catch(err){setError(err instanceof Error?err.message:'Milk production save failed.')}finally{setSaving(false)}};
 const saveDisposition=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const l=Number(dispositionLitres);if(!(l>0))throw new Error('Litres must be greater than zero.');await request(editingDisposition?`/farm/milk/dispositions/${editingDisposition.id}`:'/farm/milk/dispositions',{method:editingDisposition?'PATCH':'POST',body:JSON.stringify({production_date:date,disposition_type:dispositionType,quantity_litres:l,sale_id:dispositionType==='SOLD'?(saleId||`SALE-${Date.now()}`):null,counterparty:counterparty||null,selling_price_per_litre:dispositionType==='SOLD'?Number(sellingPrice||0):null,notes:dispositionNotes||null})});setMessage(editingDisposition?'Milk disposition updated.':'Milk disposition recorded.');resetDisposition();await load()}catch(err){setError(err instanceof Error?err.message:'Milk disposition save failed.')}finally{setSaving(false)}};
 const saveQuality=async(e:React.FormEvent)=>{e.preventDefault();setQualitySaving(true);setError('');try{const fat=Number(qualityFat),snf=Number(qualitySnf);if(!(fat>0)||!(snf>0))throw new Error('Fat % and SNF % must be greater than zero.');await request('/farm/milk/quality',{method:'POST',body:JSON.stringify({quality_date:date,fat_pct:fat,snf_pct:snf,sample_type:qualitySampleType,notes:qualityNotes||null,recorded_by:'UI Operator'})});setMessage('Milk quality sample saved.');await load()}catch(err){setError(err instanceof Error?err.message:'Milk quality save failed.')}finally{setQualitySaving(false)}};
 const editProduction=(r:ProductionRow)=>{setEditingProduction(r);setProductionAnimal(r.animal_id);setProductionSession(r.milking_session||'MORNING');setProductionLitres(String(r.morning_yield??r.afternoon_yield??r.evening_yield??''));setProductionNotes(r.notes||'');setDate(r.production_date.slice(0,10));setShowProductionForm(true)};
 const editDisposition=(r:DispositionRow)=>{setEditingDisposition(r);setDispositionType(r.disposition_type);setDispositionLitres(String(r.quantity_litres));setSaleId(r.sale_id||'');setCounterparty(r.counterparty||'');setSellingPrice(String(r.selling_price_per_litre??''));setDispositionNotes(r.notes||'');setDate(r.production_date.slice(0,10));setShowDispositionForm(true)};
 const voidProduction=async(r:ProductionRow)=>{if(!window.confirm(`Void milk production record ${r.id}?`))return;try{await request(`/farm/milk/production/${r.id}/void`,{method:'POST',body:JSON.stringify({reason:'Operator void from Milk register'})});await load()}catch(err){setError(err instanceof Error?err.message:'Unable to void production.')}};
 const voidDisposition=async(r:DispositionRow)=>{if(!window.confirm(`Void milk disposition ${r.id}?`))return;try{await request(`/farm/milk/dispositions/${r.id}/void`,{method:'POST',body:JSON.stringify({reason:'Operator void from Milk register'})});await load()}catch(err){setError(err instanceof Error?err.message:'Unable to void disposition.')}};
 const detail=useMemo(()=>{if(selectedPanel==='monthProduced')return monthData.production.filter(r=>r.status!=='VOID').sort((a,b)=>a.production_date.localeCompare(b.production_date));if(selectedPanel==='dailyProduced')return productions.filter(r=>r.status!=='VOID');if(selectedPanel==='monthSold')return monthData.dispositions.filter(r=>r.status!=='VOID'&&r.disposition_type==='SOLD');if(selectedPanel==='dailySold')return dispositions.filter(r=>r.status!=='VOID'&&r.disposition_type==='SOLD');if(selectedPanel==='domestic')return dispositions.filter(r=>r.status!=='VOID'&&r.disposition_type==='DOMESTIC_USE');if(selectedPanel==='calves')return dispositions.filter(r=>r.status!=='VOID'&&r.disposition_type==='CALF_FEED');if(selectedPanel==='wastage')return dispositions.filter(r=>r.status!=='VOID'&&r.disposition_type==='WASTAGE');return []},[selectedPanel,monthData,productions,dispositions]);
 const titleMap:any={monthProduced:`Daily milk production — ${bounds.label}`,monthSold:`Milk sold — ${bounds.label}`,monthRecon:`Daily reconciliation — ${bounds.label}`,dailyProduced:`Animal milk production — ${date}`,dailySold:`Milk sold — ${date}`,domestic:`Domestic use — ${date}`,calves:`Calves feed — ${date}`,wastage:`Wastage / unusable — ${date}`,dailyRecon:`Daily reconciliation — ${date}`};
 return <div style={{padding:14,color:'#fff',height:'100%',overflowY:'auto',overflowX:'hidden',boxSizing:'border-box',minWidth:0}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginBottom:10,flexWrap:'wrap'}}><div><div style={{fontSize:18,fontWeight:800,display:'flex',alignItems:'center',gap:7}}><Milk size={18} color="#38bdf8"/> Milk</div><div style={{fontSize:10,color:'#94a3b8'}}>Current-month production, sales and daily reconciliation.</div></div><button style={smallButton} onClick={()=>void load()}><RefreshCw size={12}/> Refresh</button></div>
  {error&&<div style={{background:'rgba(239,68,68,.12)',border:'1px solid #ef4444',color:'#fecaca',padding:8,borderRadius:6,marginBottom:10,fontSize:10}}>{error}</div>}{message&&<div style={{background:'rgba(52,211,153,.1)',border:'1px solid #34d399',color:'#bbf7d0',padding:8,borderRadius:6,marginBottom:10,fontSize:10}}><Check size={12}/> {message}</div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8,marginBottom:8}}>
   <MetricButton label={`Total Milk Produced (${bounds.label})`} value={litre(monthProduced)} color="#38bdf8" active={selectedPanel==='monthProduced'} onClick={()=>click('monthProduced')}/><MetricButton label="Milk Sold (month)" value={litre(monthSold)} color="#34d399" active={selectedPanel==='monthSold'} onClick={()=>click('monthSold')}/><MetricButton label="Overall Reconciliation" value={litre(monthRecon)} color={monthRecon===0?'#34d399':'#f59e0b'} active={selectedPanel==='monthRecon'} onClick={()=>click('monthRecon')}/>
  </div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(6,minmax(0,1fr))',gap:7,marginBottom:10}}>
   <MetricButton label="Milk Produced" value={litre(reconciliation?.produced_litres)} color="#38bdf8" active={selectedPanel==='dailyProduced'} onClick={()=>click('dailyProduced')} suffix={<input type="date" value={date} onChange={e=>{e.stopPropagation();setDate(e.target.value)}} style={{...inputStyle,width:'100%',marginTop:5,fontSize:9}}/>}/>
   <MetricButton label="Milk Sold" value={litre(soldToday)} color="#34d399" active={selectedPanel==='dailySold'} onClick={()=>click('dailySold')} />
   <MetricButton label="Domestic Use" value={litre(domestic)} color="#f59e0b" active={selectedPanel==='domestic'} onClick={()=>click('domestic')} suffix={<button type="button" onClick={e=>{e.stopPropagation();setDispositionType('DOMESTIC_USE');setShowDispositionForm(true)}} style={{...buttonStyle('#b45309'),width:'100%',justifyContent:'center',marginTop:5}}>Enter Milk for Domestic Use</button>}/>
   <MetricButton label="Calves Feed" value={litre(calves)} color="#a78bfa" active={selectedPanel==='calves'} onClick={()=>click('calves')} suffix={<button type="button" onClick={e=>{e.stopPropagation();setDispositionType('CALF_FEED');setShowDispositionForm(true)}} style={{...buttonStyle('#7c3aed'),width:'100%',justifyContent:'center',marginTop:5}}>Enter Milk for Calves</button>}/>
   <MetricButton label="Wastage / Not Usable" value={litre(wastage)} color="#f87171" active={selectedPanel==='wastage'} onClick={()=>click('wastage')} suffix={<button type="button" onClick={e=>{e.stopPropagation();setDispositionType('WASTAGE');setShowDispositionForm(true)}} style={{...buttonStyle('#dc2626'),width:'100%',justifyContent:'center',marginTop:5}}>Enter Wastage / Unusable</button>}/>
   <MetricButton label="Reconciliation" value={litre(dailyDifference)} color={Math.abs(dailyDifference)<0.05?'#34d399':'#f59e0b'} active={selectedPanel==='dailyRecon'} onClick={()=>click('dailyRecon')} />
  </div>
  {selectedPanel&&<section style={{background:'#111827',border:'1px solid #1f2937',borderRadius:8,padding:10,marginBottom:10,overflow:'hidden'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:8}}><strong style={{fontSize:12}}>{titleMap[selectedPanel]}</strong><button style={smallButton} onClick={()=>setSelectedPanel(null)}><X size={11}/> Close</button></div>{selectedPanel==='monthRecon'||selectedPanel==='dailyRecon'?<div style={{overflowX:'auto'}}><table style={tableStyle}><thead><tr><th>Date</th><th>Produced</th><th>Sold</th><th>Non-sale</th><th>Unaccounted</th><th>Status</th></tr></thead><tbody>{(selectedPanel==='monthRecon'?dailyRecon:reconciliation?[reconciliation]:[]).map(r=><tr key={r.production_date}><td>{r.production_date}</td><td>{litre(r.produced_litres)}</td><td>{litre(r.sold_litres)}</td><td>{litre(r.non_sale_accounted_litres)}</td><td>{litre(r.unaccounted_litres)}</td><td>{r.status}</td></tr>)}</tbody></table></div>:<DetailTable rows={detail} kind={selectedPanel}/>}</section>}
  <section style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(260px,.5fr)',gap:10,alignItems:'start'}}>
   <div style={{background:'#111827',border:'1px solid #1f2937',borderRadius:8,overflow:'hidden'}}><div style={{padding:'9px 11px',borderBottom:'1px solid #1f2937',display:'flex',justifyContent:'space-between',alignItems:'center'}}><strong style={{fontSize:12}}>Daily Milk Register — {date}</strong><span style={{fontSize:9,color:'#64748b'}}>{loading?'Loading…':`${productions.length+dispositions.length} records`}</span></div><div style={{overflowX:'auto'}}><table style={{width:'100%',minWidth:720,borderCollapse:'collapse',fontSize:10}}><thead><tr style={{background:'#161f30',color:'#94a3b8',textAlign:'left'}}><th style={{padding:8}}>Date</th><th>Type / Animal</th><th>Quantity</th><th>Status</th><th>Notes</th><th style={{textAlign:'right',padding:8}}>Actions</th></tr></thead><tbody>{[...productions.map(r=>({kind:'PRODUCTION' as const,id:r.id,label:`${r.animal_id} • ${r.milking_session||'LEGACY'}`,qty:litre(r.total_yield),status:r.status,notes:r.notes,row:r})),...dispositions.map(r=>({kind:'DISPOSITION' as const,id:r.id,label:`${r.disposition_type}${r.sale_id?` • ${r.sale_id}`:''}`,qty:litre(r.quantity_litres),status:r.status,notes:r.notes,row:r}))].map(e=><tr key={`${e.kind}-${e.id}`} style={{borderTop:'1px solid #1a2234',opacity:e.status==='VOID'?.55:1}}><td style={{padding:8}}>{date}</td><td>{e.label}</td><td>{e.qty}</td><td>{e.status}</td><td style={{color:'#94a3b8'}}>{e.notes||'—'}</td><td style={{padding:8,textAlign:'right'}}>{e.status!=='VOID'&&<span style={{display:'inline-flex',gap:5}}>{e.kind==='PRODUCTION'?<><button style={smallButton} onClick={()=>editProduction(e.row)}><Edit3 size={10}/> Edit</button><button style={smallButton} onClick={()=>voidProduction(e.row)}><Trash2 size={10}/> Void</button></>:<><button style={smallButton} onClick={()=>editDisposition(e.row)}><Edit3 size={10}/> Edit</button><button style={smallButton} onClick={()=>voidDisposition(e.row)}><Trash2 size={10}/> Void</button></>}</span>}</td></tr>)}</tbody></table></div></div>
   <div style={{display:'grid',gap:10}}>
    <div style={{background:'#111827',border:'1px solid #1f2937',borderRadius:8,padding:10}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:7}}><strong style={{fontSize:11,color:'#38bdf8'}}>Milk Production Entry</strong>{showProductionForm&&<button style={smallButton} onClick={resetProduction}><X size={11}/></button>}</div>{!showProductionForm?<button style={{...buttonStyle('#0284c7'),width:'100%',justifyContent:'center'}} onClick={()=>setShowProductionForm(true)}><Droplets size={12}/> Enter Milk Production</button>:<form onSubmit={saveProduction}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}><select value={productionAnimal} onChange={e=>setProductionAnimal(e.target.value)} style={inputStyle} required>{herdMasterList.map(a=><option key={a.id} value={a.id}>{a.id} • {a.breed}</option>)}</select><select value={productionSession} onChange={e=>setProductionSession(e.target.value)} style={inputStyle} required><option value="">Expected session</option>{(nextSession?.expected_sessions||[]).map(s=><option key={s}>{s}</option>)}</select></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6,marginTop:6}}><input type="number" min="0.001" step="0.001" value={productionLitres} onChange={e=>setProductionLitres(e.target.value)} style={inputStyle} placeholder="Litres" required/><input value={productionNotes} onChange={e=>setProductionNotes(e.target.value)} style={inputStyle} placeholder="Notes"/></div><button disabled={saving} type="submit" style={{...buttonStyle('#0284c7'),width:'100%',justifyContent:'center',marginTop:6}}>{saving?'Saving…':editingProduction?'Update Production':'Save Production'}</button></form>}</div>
    <div style={{background:'#111827',border:'1px solid #1f2937',borderRadius:8,padding:10}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:7}}><strong style={{fontSize:11,color:'#34d399'}}>Milk Disposition</strong>{showDispositionForm&&<button style={smallButton} onClick={resetDisposition}><X size={11}/></button>}</div>{!showDispositionForm?<button style={{...buttonStyle('#059669'),width:'100%',justifyContent:'center'}} onClick={()=>setShowDispositionForm(true)}>Record Sale / Farm Use</button>:<form onSubmit={saveDisposition}><select value={dispositionType} onChange={e=>setDispositionType(e.target.value)} style={inputStyle}><option>SOLD</option><option>DOMESTIC_USE</option><option>CALF_FEED</option><option>WASTAGE</option><option>OTHER</option></select><input type="number" min="0.001" step="0.001" value={dispositionLitres} onChange={e=>setDispositionLitres(e.target.value)} style={{...inputStyle,marginTop:6}} placeholder="Litres" required/>{dispositionType==='SOLD'&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6,marginTop:6}}><input value={counterparty} onChange={e=>setCounterparty(e.target.value)} style={inputStyle} placeholder="Customer"/><input type="number" min="0" step="0.01" value={sellingPrice} onChange={e=>setSellingPrice(e.target.value)} style={inputStyle} placeholder="Price / litre"/></div>}<input value={counterparty} onChange={e=>setCounterparty(e.target.value)} style={{...inputStyle,marginTop:6}} placeholder={dispositionType==='SOLD'?'Customer / destination':'Destination'}/><input value={dispositionNotes} onChange={e=>setDispositionNotes(e.target.value)} style={{...inputStyle,marginTop:6}} placeholder="Notes"/><button disabled={saving} type="submit" style={{...buttonStyle('#059669'),width:'100%',justifyContent:'center',marginTop:6}}>{saving?'Saving…':editingDisposition?'Update Disposition':'Save Disposition'}</button></form>}</div>
   </div>
  </section>
  <section style={{background:'#111827',border:'1px solid #1f2937',borderRadius:8,padding:10,marginTop:10}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:7}}><div><strong style={{fontSize:11,color:'#a78bfa'}}>Milk Quality — Daily Sample</strong><div style={{fontSize:9,color:'#64748b'}}>Persisted Fat % and SNF %.</div></div><span style={{fontSize:9,color:qualitySample?'#34d399':'#64748b'}}>{qualitySample?'SAVED':'NOT RECORDED'}</span></div><form onSubmit={saveQuality}><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:6}}><input type="number" min="0.001" max="15" step="0.001" value={qualityFat} onChange={e=>setQualityFat(e.target.value)} style={inputStyle} placeholder="Fat %" required/><input type="number" min="0.001" max="15" step="0.001" value={qualitySnf} onChange={e=>setQualitySnf(e.target.value)} style={inputStyle} placeholder="SNF %" required/><select value={qualitySampleType} onChange={e=>setQualitySampleType(e.target.value)} style={inputStyle}><option>BULK_TANK</option><option>COLLECTION</option><option>PROCESSOR</option><option>OTHER</option></select></div><input value={qualityNotes} onChange={e=>setQualityNotes(e.target.value)} style={{...inputStyle,marginTop:6}} placeholder="Quality notes"/><button disabled={qualitySaving} type="submit" style={{...buttonStyle('#7c3aed'),marginTop:6}}>{qualitySaving?'Saving…':qualitySample?'Update Quality Sample':'Save Quality Sample'}</button></form></section>
 </div>
}
function MetricButton({label,value,color,active,onClick,suffix}:{label:string;value:string;color:string;active:boolean;onClick:()=>void;suffix?:React.ReactNode}){return <button type="button" onClick={onClick} style={{textAlign:'left',background:active?'#16253a':'#111827',border:`1px solid ${active?color:'#1f2937'}`,borderLeft:`4px solid ${color}`,borderRadius:7,padding:'9px 10px',color:'#fff',cursor:'pointer',minWidth:0,fontFamily:'inherit'}}><div style={{fontSize:8,color:'#94a3b8',textTransform:'uppercase',fontWeight:800,lineHeight:1.25}}>{label}</div><div style={{fontSize:15,fontWeight:900,color,marginTop:3}}>{value}</div>{suffix}</button>}
function DetailTable({rows,kind}:{rows:(ProductionRow|DispositionRow)[];kind:string}){const isProd=kind==='monthProduced'||kind==='dailyProduced';return <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:10,minWidth:620}}><thead><tr style={{color:'#94a3b8',textAlign:'left',borderBottom:'1px solid #1f2937'}}>{isProd?<><th style={{padding:7}}>Date</th><th style={{padding:7}}>Animal ID</th><th style={{padding:7}}>Session</th><th style={{padding:7}}>Milk</th><th style={{padding:7}}>Status</th></>:<><th style={{padding:7}}>Date</th><th style={{padding:7}}>Disposition</th><th style={{padding:7}}>Litres</th><th style={{padding:7}}>Destination / Customer</th><th style={{padding:7}}>Status</th></>}</tr></thead><tbody>{rows.map(r=>isProd?<tr key={r.id} style={{borderBottom:'1px solid #1a2234'}}><td style={{padding:7}}>{r.production_date.slice(0,10)}</td><td style={{padding:7,color:'#38bdf8',fontWeight:700}}>{(r as ProductionRow).animal_id}</td><td style={{padding:7}}>{(r as ProductionRow).milking_session||'—'}</td><td style={{padding:7}}>{litre((r as ProductionRow).total_yield)}</td><td style={{padding:7}}>{r.status}</td></tr>:<tr key={r.id} style={{borderBottom:'1px solid #1a2234'}}><td style={{padding:7}}>{r.production_date.slice(0,10)}</td><td style={{padding:7}}>{(r as DispositionRow).disposition_type}</td><td style={{padding:7}}>{litre((r as DispositionRow).quantity_litres)}</td><td style={{padding:7}}>{(r as DispositionRow).counterparty||'—'}</td><td style={{padding:7}}>{r.status}</td></tr>)}</tbody></table></div>}
const tableStyle:React.CSSProperties={width:'100%',borderCollapse:'collapse',fontSize:10};
