import React, { useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import { API_BASE_URL } from '../config/api';
import { readApiPayload } from '../api/response';
import { NAVIGATION_TABS, normalizeHiddenNavigationTabs } from '../navigation';
import type { NavigationTabId } from '../navigation';

interface Props { hiddenNavigationTabs: NavigationTabId[]; onHiddenNavigationTabsChange?: (hiddenTabs: NavigationTabId[]) => void; onError: (message: string) => void; onMessage: (message: string) => void; resetConfirm: string; resetLoading: boolean; onResetConfirmChange: (value: string) => void; onRequestSystemReset: () => void; }
const API = API_BASE_URL || 'http://127.0.0.1:8000';
const button: React.CSSProperties = { background: '#0284c7', color: '#fff', padding: '8px 11px', border: 0, borderRadius: 5, cursor: 'pointer', fontWeight: 800, display: 'inline-flex', alignItems: 'center', gap: 5 };
const field: React.CSSProperties = { width: '100%', boxSizing: 'border-box', background: '#1e293b', color: '#fff', padding: 8, border: '1px solid #334155', borderRadius: 5 };

export default function NavigationVisibilityControl({ hiddenNavigationTabs, onHiddenNavigationTabsChange, onError, onMessage, resetConfirm, resetLoading, onResetConfirmChange, onRequestSystemReset }: Props) {
  const [draft, setDraft] = useState(() => normalizeHiddenNavigationTabs(hiddenNavigationTabs));
  const [authorized, setAuthorized] = useState(false);
  useEffect(() => { setDraft(normalizeHiddenNavigationTabs(hiddenNavigationTabs)); }, [hiddenNavigationTabs]);
  useEffect(() => { void fetch(`${API}/human-access/me`).then(response => { setAuthorized(response.ok); }); }, []);
  const save = async () => { try { const response = await fetch(`${API}/settings/navigation`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ hidden_tabs: draft }) }); const payload = await readApiPayload<{ navigation?: { hidden_tabs?: unknown } }>(response, 'Unable to save navigation visibility.'); const hidden = normalizeHiddenNavigationTabs(payload.navigation?.hidden_tabs); setDraft(hidden); onHiddenNavigationTabsChange?.(hidden); onMessage('Navigation visibility saved.'); } catch (error) { onError(error instanceof Error ? error.message : 'Unable to save navigation visibility.'); } };
  const setVisible = (id: NavigationTabId, visible: boolean) => setDraft(current => visible ? current.filter(item => item !== id) : normalizeHiddenNavigationTabs([...current, id]));
  return <section style={{ background: '#111827', padding: 15, borderRadius: 8, border: '1px solid #7c3aed', minWidth: 0 }}><strong style={{ fontSize: 12 }}>Navigation Visibility</strong><div style={{ color: '#94a3b8', fontSize: 9, margin: '5px 0 10px' }}>{authorized ? 'Authorized by the signed-in DairyOS operator session. No second password is required.' : 'A signed-in PRIMARY_ADMIN operator session is required.'}</div>{authorized && <><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 7 }}>{NAVIGATION_TABS.map(item => <label key={item.id} style={{ display: 'flex', alignItems: 'center', gap: 7, background: '#1e293b', border: '1px solid #334155', padding: '8px 10px', borderRadius: 5, fontSize: 10 }}><input type="checkbox" checked={!draft.includes(item.id)} onChange={event => setVisible(item.id, event.target.checked)} /><span>Show {item.label}</span></label>)}</div><button type="button" onClick={() => void save()} style={{ ...button, marginTop: 10 }}><Save size={13} />Save Navigation</button><div style={{ borderTop: '1px solid #334155', marginTop: 12, paddingTop: 10 }}><strong style={{ fontSize: 12, color: '#fca5a5' }}>Reset to Zero State</strong><div style={{ color: '#fecaca', fontSize: 10, margin: '7px 0 10px' }}>Requires the signed-in PRIMARY_ADMIN session and literal confirmation only. No password re-entry.</div><input value={resetConfirm} onChange={event => onResetConfirmChange(event.target.value)} placeholder="Type: RESET DAIRYOS TO ZERO STATE" style={field} /><button type="button" onClick={onRequestSystemReset} disabled={resetLoading || !resetConfirm} style={{ ...button, background: '#991b1b', marginTop: 8, opacity: resetLoading || !resetConfirm ? 0.6 : 1 }}>{resetLoading ? 'Queueing reset…' : 'Queue Reset for Next Start'}</button></div></>}</section>;
}
