import React, { useEffect, useMemo, useState } from "react";
import "./OperationalModule.css";
import OperationalEntryPanel, { type OperationalEntryConfig } from "./OperationalEntryPanel";
type Mode="cards"|"entries"|"decisions"|"state"; type Props={title:string;endpoint:string;selector?:string;mode:Mode;entry?:OperationalEntryConfig}; type Primitive=string|number|boolean|null; type JsonValue=Primitive|JsonValue[]|{[key:string]:JsonValue};
const API="http://localhost:8000"; const obj=(v:JsonValue):Record<string,JsonValue>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,JsonValue>:{}; const txt=(v:JsonValue)=>v===null||v===undefined?"—":typeof v==="object"?JSON.stringify(v):String(v); const num=(v:JsonValue)=>Number.isFinite(Number(v))?Number(v):0;
const rdate=(v:JsonValue)=>new Date(String(obj(v).timestamp??obj(v).date??obj(v).created_at??"0")).getTime(); const milkTotal=(v:JsonValue)=>{const o=obj(v);return num(o.total_yield??o.litres??(num(o.morning_yield)+num(o.afternoon_yield)+num(o.evening_yield)))};
function selectPath(v:JsonValue,s?:string):JsonValue{if(!s)return v;return s.split(".").reduce<JsonValue>((c,k)=>{const o=obj(c);return k in o?o[k]:null},v)} function label(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function periodMatch(v:JsonValue,p:string,from:string,to:string){const t=rdate(v);if(!Number.isFinite(t))return p==="all";const now=new Date();if(p==="today"){const d=new Date(t);return d.toDateString()===now.toDateString()}if(p==="custom")return t>=new Date(from).getTime()&&t<new Date(to).getTime()+86400000;const start=new Date(now);if(p==="7d")start.setDate(now.getDate()-7);if(p==="month")start.setMonth(now.getMonth()-1);if(p==="quarter")start.setMonth(now.getMonth()-3);if(p==="year")start.setFullYear(now.getFullYear()-1);return t>=start.getTime()}
export default function OperationalModule({title,endpoint,selector,mode,entry}:Props){const [payload,setPayload]=useState<JsonValue|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[updated,setUpdated]=useState<string|null>(null);const special=title.toLowerCase();const isMilk=special.includes("milk");const isFinance=special.includes("finance");const[period,setPeriod]=useState(isMilk?"7d":isFinance?"today":"all");const[from,setFrom]=useState("");const[to,setTo]=useState("");
 const load=()=>{setLoading(true);setError(null);fetch(`${API}${endpoint}`).then(r=>{if(!r.ok)throw Error(`Request failed: ${r.status}`);return r.json()}).then(d=>{setPayload(selectPath(d,selector));setUpdated(new Date().toLocaleTimeString())}).catch(e=>setError(e.message??"Unable to load data")).finally(()=>setLoading(false))}; useEffect(()=>{load();const t=window.setInterval(load,60000);return()=>window.clearInterval(t)},[endpoint,selector]);
 const rows=useMemo(()=>Array.isArray(payload)?payload:[],[payload]);const filtered=useMemo(()=>rows.filter(r=>periodMatch(r,period,from,to)),[rows,period,from,to]);
 if(loading&&payload===null)return <section className="module-view">{entry&&<OperationalEntryPanel config={entry} onSaved={load}/>}<div className="module-loading">Loading {title.toLowerCase()} data…</div></section>; if(error&&payload===null)return <section className="module-view">{entry&&<OperationalEntryPanel config={entry} onSaved={load}/>}<div className="module-error"><div><strong>Unable to load live data.</strong><p>{error}</p></div><button onClick={load}>Retry</button></div></section>;
 return <section className="module-view">{entry&&<OperationalEntryPanel config={entry} onSaved={load}/>} {(isMilk||isFinance)&&<PeriodBar finance={isFinance} period={period} setPeriod={setPeriod} from={from} to={to} setFrom={setFrom} setTo={setTo}/>}<div className="module-toolbar"><div><strong>{filtered.length} record{filtered.length===1?"":"s"}</strong>{updated&&<span>Updated {updated}</span>}</div><button onClick={load}>Refresh</button></div>{mode==="cards"?<AnimalGrid rows={filtered}/>:mode==="state"?<StateGrid payload={payload}/>:<RecordList rows={filtered} decision={mode==="decisions"} finance={isFinance} milk={isMilk}/>}</section>}
}
function PeriodBar({finance,period,setPeriod,from,to,setFrom,setTo}:{finance:boolean;period:string;setPeriod:(v:string)=>void;from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void}){const options=finance?["today","cash","bank","month","quarter","year"]:["7d","month","year","custom"];return <div className="period-bar"><div><strong>{finance?"Finance view":"Production period"}</strong><span>Calculated from actual recorded API data.</span></div><div className="period-controls">{options.map(o=><button type="button" key={o} className={period===o?"selected":""} onClick={()=>setPeriod(o)}>{o==="7d"?"7 Days":o==="month"?"Month":o==="quarter"?"Quarter":o==="year"?"Year":o==="cash"?"Cash in Hand":o==="bank"?"Money at Bank":o==="today"?"Today":"Custom"}</button>)}{period==="custom"&&<><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></>}</div></div>}
function AnimalGrid({rows}:{rows:JsonValue[]}){const[selected,setSelected]=useState<JsonValue|null>(null);return <>{rows.length?<div className="animal-grid">{rows.map((r,i)=>{const o=obj(r);return <button type="button" className="animal-card" key={i} onClick={()=>setSelected(r)}><div className="animal-card-top"><span className="animal-tag">{txt(o.ear_tag??o.animal_id)}</span><span className="animal-status">{txt(o.lifecycle_status??o.status)}</span></div><h2>{txt(o.animal_id)}</h2><div className="animal-meta"><div><span>Breed</span><strong>{txt(o.breed)}</strong></div><div><span>Sex</span><strong>{txt(o.sex)}</strong></div><div><span>Milking</span><strong>{o.is_currently_milking?"Yes":"No"}</strong></div></div></button>})}</div>:<EmptyState title="No animal records in this view"/>}{selected&&<div className="record-detail-backdrop" onClick={()=>setSelected(null)}><div className="record-detail" onClick={e=>e.stopPropagation()}><div className="record-detail-head"><h2>Animal detail</h2><button onClick={()=>setSelected(null)}>×</button></div>{Object.entries(obj(selected)).map(([k,v])=><div className="detail-row" key={k}><span>{label(k)}</span><strong>{txt(v)}</strong></div>)}</div></div>}</>}
function RecordList({rows,decision,finance,milk}:{rows:JsonValue[];decision:boolean;finance:boolean;milk:boolean}){if(!rows.length)return <EmptyState title="No records in this view"/>;return <div className="record-list">{rows.slice(0,100).map((r,i)=><RecordCard key={i} value={r} decision={decision} finance={finance} milk={milk}/>)}</div>}
function RecordCard({value,decision,finance,milk}:{value:JsonValue;decision:boolean;finance:boolean;milk:boolean}){const o=obj(value);const title=txt(o.title??o.animal_id??o.item??o.transaction_type??o.feed_type??"Operational record");const keys=["animal_id","worker_id","equipment_id","item","transaction_type","amount","feed_type","quantity_kg","quantity","litres","total_yield","morning_yield","afternoon_yield","evening_yield","severity","observation","event_type","title","priority","action","timestamp","operator","source","status","category","payment_method","counterparty","group_or_pen"];return <article className={`record-card ${decision?"decision-card":""}`}><div className="record-card-header"><strong>{title}</strong><span>{txt(o.priority??o.status??"RECORDED")}</span></div>{milk&&<div className="record-highlight">{milkTotal(value).toFixed(2)} L</div>}{finance&&o.amount!==undefined&&<div className="record-highlight">PKR {num(o.amount).toLocaleString("en-PK")}</div>}<div className="record-fields">{Object.entries(o).filter(([k])=>keys.includes(k)).map(([k,v])=><div key={k}><span>{label(k)}</span><strong>{txt(v)}</strong></div>)}</div></article>}
function StateGrid({payload}:{payload:JsonValue|null}){const entries=Object.entries(obj(payload??null));return entries.length?<div className="state-grid">{entries.map(([k,v])=><div className="state-card" key={k}><div className="state-card-title">{label(k)}</div><div className="state-card-value">{typeof v==="object"?<pre>{JSON.stringify(v,null,2)}</pre>:txt(v)}</div></div>)}</div>:<EmptyState title="No operational state yet"/>}
function EmptyState({title}:{title:string}){return <div className="empty-state"><strong>{title}</strong><span>The API is available, but there is no recorded data for this view.</span></div>}
