import React, { useEffect, useMemo, useState } from 'react';
import { Building, Mail, Plus, Save, Trash2 } from 'lucide-react';
import { API_BASE_URL } from '../config/api';
interface SettingsTabProps { onFarmProfileUpdate?: (profile:{farmName:string;location:string})=>void; }
type EmailConfig={configured:boolean;source?:string;sender_email?:string;sender_display_name?:string;smtp_host?:string;smtp_port?:number;smtp_username?:string;use_tls?:boolean;password_configured?:boolean;};
type Recipient={id:string;name:string;designation:string;email:string;};
const API_BASE=API_BASE_URL||'http://127.0.0.1:8000',RECIPIENT_KEY='dairyos_notification_recipients';
const SMTP_PRESETS:Record<string,{host:string;port:number;tls:boolean}>={'gmail.com':{host:'smtp.gmail.com',port:587,tls:true},'googlemail.com':{host:'smtp.gmail.com',port:587,tls:true},'outlook.com':{host:'smtp-mail.outlook.com',port:587,tls:true},'hotmail.com':{host:'smtp-mail.outlook.com',port:587,tls:true},'live.com':{host:'smtp-mail.outlook.com',port:587,tls:true},'office365.com':{host:'smtp.office365.com',port:587,tls:true},'yahoo.com':{host:'smtp.mail.yahoo.com',port:587,tls:true},'icloud.com':{host:'smtp.mail.me.com',port:587,tls:true},'me.com':{host:'smtp.mail.me.com',port:587,tls:true},'aol.com':{host:'smtp.aol.com',port:587,tls:true}};
const field:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#1e293b',color:'#fff',padding:8,marginBottom:9,border:'1px solid #334155',borderRadius:5},label:React.CSSProperties={fontSize:10,color:'#94a3b8',display:'block',marginBottom:4},button:React.CSSProperties={background:'#0284c7',color:'#fff',padding:'8px 11px',border:0,borderRadius:5,cursor:'pointer',fontWeight:800,display:'inline-flex',alignItems:'center',gap:5},card:React.CSSProperties={background:'#111827',padding:15,borderRadius:8,border:'1px solid #1f2937',minWidth:0};
function loadRecipients():Recipient[]{try{const p=JSON.parse(localStorage.getItem(RECIPIENT_KEY)||'[]');return Array.isArray(p)?p:[]}catch{return []}}
export default function SettingsTab({onFarmProfileUpdate}:SettingsTabProps){
 const [activeTab,setActiveTab]=useState<'FARM'|'EMAIL'>('FARM'),[farmName,setFarmName]=useState(localStorage.getItem('dairyos_farm_name')||'Barki Dairy Farm'),[location,setLocation]=useState(localStorage.getItem('dairyos_farm_loc')||'Lahore, Punjab, PK'),[emailConfig,setEmailConfig]=useState<EmailConfig>({configured:false}),[emailPassword,setEmailPassword]=useState(''),[testRecipient,setTestRecipient]=useState(''),[recipients,setRecipients]=useState<Recipient[]>(loadRecipients()),[recipientName,setRecipientName]=useState(''),[recipientDesignation,setRecipientDesignation]=useState(''),[recipientEmail,setRecipientEmail]=useState(''),[clock,setClock]=useState(new Date()),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const t=window.setInterval(()=>setClock(new Date()),30000);return()=>window.clearInterval(t)},[]);
 const localDateTime=useMemo(()=>new Intl.DateTimeFormat('en-PK',{dateStyle:'full',timeStyle:'medium'}).format(clock),[clock]);
 useEffect(()=>{void(async()=>{try{const r=await fetch(`${API_BASE}/settings`);if(!r.ok)return;const d=await r.json();if(d.farm_name)setFarmName(d.farm_name);if(d.location)setLocation(d.location)}catch(e){console.error(e)}})()},[]);
 useEffect(()=>{if(activeTab==='EMAIL')void(async()=>{try{const r=await fetch(`${API_BASE}/settings/email`);if(r.ok)setEmailConfig(await r.json())}catch(e){console.error(e)}})()},[activeTab]);
 const saveFarm=()=>{localStorage.setItem('dairyos_farm_name',farmName);localStorage.setItem('dairyos_farm_loc',location);onFarmProfileUpdate?.({farmName,location});window.dispatchEvent(new Event('storage'));setMessage('Farm profile saved.')};
 const applyProviderPreset=(email:string)=>{const domain=email.trim().toLowerCase().split('@')[1]||'',preset=SMTP_PRESETS[domain];setEmailConfig(prev=>({...prev,sender_email:email,smtp_username:email,...(preset?{smtp_host:preset.host,smtp_port:preset.port,use_tls:preset.tls}:{})}));if(preset)setMessage(`SMTP defaults loaded automatically for @${domain}.`)};
 const saveEmail=async()=>{setError('');setMessage('');try{const r=await fetch(`${API_BASE}/settings/email`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...emailConfig,smtp_password:emailPassword||undefined})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Unable to save email settings.');setEmailConfig(d);setEmailPassword('');setMessage('DairyOS sender settings saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save email settings.')}};
 const sendTest=async()=>{setError('');setMessage('');try{const r=await fetch(`${API_BASE}/settings/email/test`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipient:testRecipient})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Test email failed.');setMessage(`Test email sent to ${d.recipient}.`)}catch(e){setError(e instanceof Error?e.message:'Test email failed.')}};
 const addRecipient=()=>{const email=recipientEmail.trim();if(!recipientName.trim()||!email.includes('@')){setError('Recipient name and valid email are required.');return}const next=[...recipients,{id:`${Date.now()}`,name:recipientName.trim(),designation:recipientDesignation.trim(),email}];setRecipients(next);localStorage.setItem(RECIPIENT_KEY,JSON.stringify(next));setRecipientName('');setRecipientDesignation('');setRecipientEmail('');setError('');setMessage('Notification recipient added.')};
 const removeRecipient=(id:string)=>{const next=recipients.filter(r=>r.id!==id);setRecipients(next);localStorage.setItem(RECIPIENT_KEY,JSON.stringify(next))};
 return <div style={{padding:18,color:'#fff',height:'100%',overflowY:'auto',boxSizing:'border-box'}}><h2 style={{color:'#38bdf8',margin:'0 0 12px'}}>System Settings</h2><div style={{display:'flex',gap:8,marginBottom:12}}><button onClick={()=>setActiveTab('FARM')} style={tab(activeTab==='FARM')}><Building size={13}/>Farm & System</button><button onClick={()=>setActiveTab('EMAIL')} style={tab(activeTab==='EMAIL')}><Mail size={13}/>Email & Notifications</button></div>{error&&<div style={{background:'#450a0a',border:'1px solid #7f1d1d',color:'#fecaca',padding:8,borderRadius:6,marginBottom:8,fontSize:10}}>{error}</div>}{message&&<div style={{background:'#064e3b',border:'1px solid #065f46',color:'#a7f3d0',padding:8,borderRadius:6,marginBottom:8,fontSize:10}}>{message}</div>}
 {activeTab==='FARM'&&<div style={{display:'grid',gridTemplateColumns:'minmax(0,440px) minmax(280px,1fr)',gap:12,alignItems:'start'}}><section style={card}><label style={label}>Farm Name</label><input value={farmName} onChange={e=>setFarmName(e.target.value)} style={field}/><label style={label}>Location</label><input value={location} onChange={e=>setLocation(e.target.value)} style={field}/><button onClick={saveFarm} style={button}><Save size={13}/>Save Farm</button></section><section style={card}><strong style={{fontSize:12}}>System Date & Time</strong><div style={{color:'#e2e8f0',marginTop:8,fontWeight:800}}>{localDateTime}</div><div style={{color:'#94a3b8',fontSize:10,marginTop:6}}>DairyOS operator forms use the computer/browser clock as their default date and time. Forms may still select a different historical date where required.</div></section></div>}
 {activeTab==='EMAIL'&&<div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12,alignItems:'start'}}><section style={card}><strong style={{fontSize:12}}>DairyOS Sender</strong><div style={{color:'#64748b',fontSize:9,margin:'5px 0 10px'}}>Recognized provider settings populate automatically from the sender email domain.</div><label style={label}>From Email</label><input type="email" value={emailConfig.sender_email??''} onChange={e=>applyProviderPreset(e.target.value)} style={field}/><label style={label}>Display Name</label><input value={emailConfig.sender_display_name??''} onChange={e=>setEmailConfig({...emailConfig,sender_display_name:e.target.value})} style={field}/><label style={label}>SMTP Host</label><input value={emailConfig.smtp_host??''} onChange={e=>setEmailConfig({...emailConfig,smtp_host:e.target.value})} style={field}/><div style={{display:'grid',gridTemplateColumns:'120px 1fr',gap:7}}><div><label style={label}>Port</label><input type="number" value={emailConfig.smtp_port??587} onChange={e=>setEmailConfig({...emailConfig,smtp_port:Number(e.target.value)})} style={field}/></div><div><label style={label}>Username</label><input value={emailConfig.smtp_username??''} onChange={e=>setEmailConfig({...emailConfig,smtp_username:e.target.value})} style={field}/></div></div><label style={label}>SMTP Password {emailConfig.password_configured&&'(stored)'}</label><input type="password" value={emailPassword} onChange={e=>setEmailPassword(e.target.value)} placeholder={emailConfig.password_configured?'Leave blank to keep current password':''} style={field}/><label style={{fontSize:10,display:'flex',alignItems:'center',gap:6,marginBottom:9}}><input type="checkbox" checked={emailConfig.use_tls!==false} onChange={e=>setEmailConfig({...emailConfig,use_tls:e.target.checked})}/>Use TLS</label><button onClick={()=>void saveEmail()} style={button}><Save size={13}/>Save Sender</button></section>
 <div style={{display:'grid',gap:12}}><section style={card}><strong style={{fontSize:12}}>Test Email</strong><input type="email" value={testRecipient} onChange={e=>setTestRecipient(e.target.value)} placeholder="recipient@example.com" style={{...field,marginTop:8}}/><button disabled={!testRecipient} onClick={()=>void sendTest()} style={button}><Mail size={13}/>Send Test</button></section><section style={card}><strong style={{fontSize:12}}>Notification Recipients</strong><div style={{color:'#64748b',fontSize:9,margin:'5px 0 9px'}}>Name, designation and email entry points for farm notification recipients.</div><input value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Name" style={field}/><input value={recipientDesignation} onChange={e=>setRecipientDesignation(e.target.value)} placeholder="Designation" style={field}/><input type="email" value={recipientEmail} onChange={e=>setRecipientEmail(e.target.value)} placeholder="Email address" style={field}/><button type="button" onClick={addRecipient} style={button}><Plus size={13}/>Add Recipient</button><div style={{marginTop:9,display:'grid',gap:5}}>{recipients.map(r=><div key={r.id} style={{display:'flex',gap:7,alignItems:'center',borderTop:'1px solid #1f2937',paddingTop:6}}><div style={{flex:1,minWidth:0}}><strong style={{fontSize:10}}>{r.name}</strong><div style={{color:'#94a3b8',fontSize:9}}>{r.designation||'No designation'} Â· {r.email}</div></div><button onClick={()=>removeRecipient(r.id)} style={{background:'none',border:0,color:'#fca5a5',cursor:'pointer'}}><Trash2 size={13}/></button></div>)}</div></section></div></div>}
 </div>
}
const tab=(active:boolean):React.CSSProperties=>({background:active?'#0c4a6e':'#1e293b',color:'#f8fafc',border:active?'1px solid #38bdf8':'1px solid #475569',borderRadius:5,padding:'7px 10px',cursor:'pointer',fontWeight:800,display:'inline-flex',alignItems:'center',gap:5});
