import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Plus, Printer, RefreshCw, Save, Wheat } from 'lucide-react';
import { API_BASE_URL } from '../config/api';

const API_BASE = API_BASE_URL || 'http' + '://127.0.0.1:8000';
type PriceSource='FINANCE'|'MANUAL';
type Ingredient={catalog_name:string;display_name?:string;dose_unit:'kg'|'g';fallback_price_per_kg:number;quantity:number;price_per_kg:number;price_source:'FINANCE'|'MANUAL'|'MANUAL_FALLBACK';selected_price_source?:PriceSource;manual_price_per_kg?:number;finance_price_per_kg?:number|null;finance_transaction_id?:number|null;finance_purchase_date?:string|null;cost_per_head_day:number};
type Stage={key:string;label:string;ingredients:Ingredient[];ration_kg_per_head_day:number;cost_per_head_day:number;source:string};
type Category={category:string;stage_keys:string[];animal_count:number;cost_per_head_day:number;category_cost_per_day:number};
type Weekly={week_start:string;week_end:string;status:string;advisory:string;endorsement?:{reviewer?:string;reviewed_on?:string}|null};
type Summary={operational_date:string;stages:Record<string,Stage>;categories:Category[];total_herd_feed_cost_per_day:number;milk_production_today_liters:number;feed_cost_per_litre_today:number|null;feed_cost_basis:string;weekly_review?:Weekly};
type Draft=Ingredient&{selected_price_source:PriceSource;manual_price_per_kg:number};

const order=['Milking','Dry','Heifer','Female Calf','Male Calf','Bull'];
// UI contract: category.cost_per_head_day remains the governed category metric.
const panel:React.CSSProperties={background:'#111827',border:'1px solid #1f2937',borderRadius:8,padding:10};
const input:React.CSSProperties={background:'#1e293b',color:'#fff',border:'1px solid #334155',borderRadius:5,padding:'7px 8px',fontSize:10,boxSizing:'border-box'};
const btn=(bg:string):React.CSSProperties=>({background:bg,color:'#fff',border:0,borderRadius:5,padding:'7px 10px',fontSize:10,fontWeight:800,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:5});
const label:React.CSSProperties={color:'#94a3b8',fontSize:9,fontWeight:800,textTransform:'uppercase'};
const money=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?`PKR ${n.toLocaleString('en-PK',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'N/A'};
const basis=(c:string)=>c==='Milking'?'Average of Early, Mid and Late Lactation TMR':c==='Dry'?'Average of Far-Off Dry and Close-Up Dry TMR':c==='Heifer'?'Growing Heifer TMR':c==='Bull'?'Bull TMR':c.includes('Calf')?'Calf Starter TMR':'';
const toDraft=(r:Ingredient):Draft=>({...r,selected_price_source:r.selected_price_source??(r.price_source==='FINANCE'?'FINANCE':'MANUAL'),manual_price_per_kg:Number(r.manual_price_per_kg??r.fallback_price_per_kg??0)});

export default function TMRPreparationTool(){
 const [summary,setSummary]=useState<Summary|null>(null),[category,setCategory]=useState('Milking'),[stage,setStage]=useState('early_milking'),[draft,setDraft]=useState<Draft[]>([]),[operator,setOperator]=useState('UI Operator'),[reviewer,setReviewer]=useState(''),[reviewNotes,setReviewNotes]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[endorsing,setEndorsing]=useState(false),[showAdd,setShowAdd]=useState(false),[adding,setAdding]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [newItem,setNewItem]=useState({name:'',display_name:'',dose_unit:'kg' as 'kg'|'g',fallback_price_per_kg:0});
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(`${API_BASE}/farm/tmr`),b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail||'Unable to load governed TMR.');setSummary(b)}catch(e){setSummary(null);setError(e instanceof Error?e.message:'Unable to load governed TMR.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const categories=useMemo(()=>[...(summary?.categories??[])].sort((a,b)=>order.indexOf(a.category)-order.indexOf(b.category)),[summary]);
 const activeCategory=categories.find(r=>r.category===category)??categories[0]??null;
 useEffect(()=>{if(activeCategory&&!activeCategory.stage_keys.includes(stage))setStage(activeCategory.stage_keys[0]||'')},[activeCategory,stage]);
 const activeStage=summary?.stages?.[stage]??null;
 useEffect(()=>{setDraft(activeStage?activeStage.ingredients.map(toDraft):[])},[activeStage]);
 const usedRate=(r:Draft)=>r.selected_price_source==='FINANCE'?Number(r.finance_price_per_kg??r.price_per_kg??0):Number(r.manual_price_per_kg||0);
 const rationKg=useMemo(()=>draft.reduce((s,r)=>s+(r.dose_unit==='g'?Number(r.quantity||0)/1000:Number(r.quantity||0)),0),[draft]);
 const stageCost=useMemo(()=>draft.reduce((s,r)=>s+(r.dose_unit==='g'?Number(r.quantity||0)/1000:Number(r.quantity||0))*usedRate(r),0),[draft]);
 const change=(i:number,patch:Partial<Draft>)=>setDraft(rows=>rows.map((r,x)=>x===i?{...r,...patch}:r));
 const setSource=(i:number,s:PriceSource)=>{const r=draft[i];if(!r)return;const selected=s==='FINANCE'&&r.finance_price_per_kg==null?'MANUAL':s;change(i,{selected_price_source:selected,price_source:selected,price_per_kg:selected==='FINANCE'?Number(r.finance_price_per_kg??0):Number(r.manual_price_per_kg||0)})};
 const setManual=(i:number,v:number)=>{const n=Math.max(0,v||0),r=draft[i];change(i,{manual_price_per_kg:n,fallback_price_per_kg:n,price_per_kg:r?.selected_price_source==='MANUAL'?n:r?.price_per_kg??n})};
 const save=async()=>{if(!stage||!draft.length)return;setSaving(true);setError('');setMessage('');try{const r=await fetch(`${API_BASE}/farm/tmr/stages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage,operator:operator.trim()||'UI Operator',ingredients:draft.map(x=>({catalog_name:x.catalog_name,quantity:Number(x.quantity||0),dose_unit:x.dose_unit,fallback_price_per_kg:Number(x.manual_price_per_kg||0),price_source:x.selected_price_source}))})}),b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail||'Unable to save governed TMR stage.');setSummary(b.summary);setMessage(`${activeStage?.label||stage} saved as a new governed TMR version.`)}catch(e){setError(e instanceof Error?e.message:'Unable to save TMR stage.')}finally{setSaving(false)}};
 const addIngredient=async()=>{if(!newItem.name.trim()){setError('Ingredient name is required.');return}setAdding(true);setError('');try{const r=await fetch(`${API_BASE}/farm/tmr/ingredients`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:newItem.name.trim(),display_name:newItem.display_name.trim()||newItem.name.trim(),dose_unit:newItem.dose_unit,fallback_price_per_kg:Number(newItem.fallback_price_per_kg||0)})}),b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail||'Unable to add TMR ingredient.');setNewItem({name:'',display_name:'',dose_unit:'kg',fallback_price_per_kg:0});setShowAdd(false);setMessage(`${b?.catalog_name||'Ingredient'} added to the governed Feed ingredient catalog and is now available to Finance → Feed Expenses.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to add TMR ingredient.')}finally{setAdding(false)}};
 const endorse=async()=>{if(!reviewer.trim()){setError('Vet reviewer name / ID is required.');return}setEndorsing(true);setError('');try{const r=await fetch(`${API_BASE}/farm/tmr/endorse`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewer:reviewer.trim(),notes:reviewNotes.trim()||null})}),b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail||'Unable to endorse weekly TMR review.');setSummary(b.summary);setReviewNotes('');setMessage('Weekly whole-herd TMR review endorsed and retained in audit history.')}catch(e){setError(e instanceof Error?e.message:'Unable to endorse TMR review.')}finally{setEndorsing(false)}};
 const weekly=summary?.weekly_review, endorsed=weekly?.status==='ENDORSED';
 return <div style={{background:'#0f172a',border:'1px solid #1f2937',borderRadius:10,overflow:'hidden',color:'#fff'}}>
  <div style={{padding:14,borderBottom:'1px solid #1f2937',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h3 style={{margin:0,color:'#38bdf8',fontSize:15,display:'flex',alignItems:'center',gap:7}}><Wheat size={18}/>TMR Preparation Tool</h3><div style={{marginTop:4,color:'#94a3b8',fontSize:10}}>Governed whole-herd ration authority. Finance can supply ingredient purchase prices; each ingredient can always be switched to Manual. TMR supplies consumed feed cost for COP.</div></div><div style={{display:'flex',gap:7}}><button onClick={()=>void load()} style={btn('#334155')}><RefreshCw size={12}/>Refresh</button><button onClick={()=>window.print()} style={btn('#475569')}><Printer size={12}/>Print</button><button onClick={()=>setShowAdd(v=>!v)} style={btn('#2563eb')}><Plus size={12}/>Add Ingredient</button></div></div>
  {error&&<div style={{margin:12,color:'#fecaca',fontSize:10}}>{error}</div>}{message&&<div style={{margin:12,color:'#bbf7d0',fontSize:10}}>{message}</div>}
  {loading||!summary?<div style={{padding:20,color:'#94a3b8',fontSize:10}}>{loading?'Loading governed TMR…':'TMR data unavailable.'}</div>:<>
   <div style={{padding:12,display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8}}><Metric label="Whole Herd Feed Cost / Day" value={money(summary.total_herd_feed_cost_per_day)}/><Metric label="Milk Production Today" value={`${Number(summary.milk_production_today_liters||0).toLocaleString('en-PK')} L`}/><Metric label="Live Feed Cost / L" value={summary.feed_cost_per_litre_today==null?'N/A':money(summary.feed_cost_per_litre_today)}/></div>
   <div style={{padding:'4px 12px 12px',display:'grid',gridTemplateColumns:'repeat(6,minmax(120px,1fr))',gap:7,overflowX:'auto'}}>{categories.map(c=><button key={c.category} onClick={()=>{setCategory(c.category);setStage(c.stage_keys[0]||'')}} style={{...panel,textAlign:'left',cursor:'pointer',color:'#fff',outline:c.category===activeCategory?.category?'1px solid #38bdf8':'none'}}><b>{c.category}</b><div style={{fontSize:15,fontWeight:900,marginTop:6}}>{money(c.cost_per_head_day)}</div><small>{c.animal_count} animal(s)</small><div style={{color:'#34d399',marginTop:4}}>{money(c.category_cost_per_day)} / day</div></button>)}</div>
   {activeCategory&&<div style={{margin:'0 12px 12px',...panel}}><b>{activeCategory.category}</b><div style={{color:'#94a3b8',fontSize:9}}>{basis(activeCategory.category)}</div><div style={{display:'flex',gap:6,marginTop:8,flexWrap:'wrap'}}>{activeCategory.stage_keys.map(k=><button key={k} onClick={()=>setStage(k)} style={btn(k===stage?'#0369a1':'#1e293b')}>{summary.stages[k]?.label||k}</button>)}</div></div>}
   {showAdd&&<div style={{margin:'0 12px 12px',...panel}}><b>Add Governed Feed Ingredient</b><div style={{display:'grid',gridTemplateColumns:'1.2fr 1.2fr 90px 130px auto',gap:7,marginTop:8}}><input placeholder="Catalog / Finance Name" value={newItem.name} onChange={e=>setNewItem(x=>({...x,name:e.target.value}))} style={input}/><input placeholder="Display Name" value={newItem.display_name} onChange={e=>setNewItem(x=>({...x,display_name:e.target.value}))} style={input}/><select value={newItem.dose_unit} onChange={e=>setNewItem(x=>({...x,dose_unit:e.target.value==='g'?'g':'kg'}))} style={input}><option>kg</option><option>g</option></select><input type="number" min={0} placeholder="Manual PKR/kg" value={newItem.fallback_price_per_kg} onChange={e=>setNewItem(x=>({...x,fallback_price_per_kg:Math.max(0,Number(e.target.value)||0)}))} style={input}/><button disabled={adding} onClick={()=>void addIngredient()} style={btn('#2563eb')}><Plus size={12}/>{adding?'Adding…':'Add'}</button></div></div>}
   {activeStage&&<><div style={{padding:'0 12px 8px',display:'flex',justifyContent:'space-between',alignItems:'end'}}><div><b>{activeStage.label}</b><div style={{color:'#64748b',fontSize:9}}>Governed version currently: {money(activeStage.cost_per_head_day)} / head / day</div></div><label style={label}>Updated By <input value={operator} onChange={e=>setOperator(e.target.value)} style={{...input,width:180}}/></label></div>
    <div style={{overflowX:'auto'}}><table style={{width:'100%',minWidth:1050,borderCollapse:'collapse',fontSize:10}}><thead><tr style={{background:'#111827'}}><th>Ingredient</th><th>Qty / Head / Day</th><th>Price Source</th><th>Price / kg</th><th>Price Authority</th><th>Cost / Head / Day</th></tr></thead><tbody>{draft.map((r,i)=>{const q=r.dose_unit==='g'?Number(r.quantity||0)/1000:Number(r.quantity||0),rate=usedRate(r),fin=r.finance_price_per_kg!=null;return <tr key={r.catalog_name} style={{borderTop:'1px solid #1f2937'}}><td>{r.display_name||r.catalog_name}<div style={{color:'#64748b',fontSize:8}}>{r.catalog_name}</div></td><td><input type="number" min={0} value={r.quantity||''} onChange={e=>change(i,{quantity:Math.max(0,Number(e.target.value)||0)})} style={{...input,width:80}}/> {r.dose_unit}</td><td><select aria-label={`Price Source ${r.catalog_name}`} value={r.selected_price_source} onChange={e=>setSource(i,e.target.value==='MANUAL'?'MANUAL':'FINANCE')} style={input}><option value="FINANCE" disabled={!fin}>Finance</option><option value="MANUAL">Manual</option></select></td><td>{r.selected_price_source==='MANUAL'?<input aria-label={`Manual Price ${r.catalog_name}`} type="number" min={0} step="0.01" value={r.manual_price_per_kg} onChange={e=>setManual(i,Number(e.target.value))} style={{...input,width:95}}/>:<b>{money(rate)}</b>}</td><td>{r.selected_price_source==='FINANCE'?<><b style={{color:'#34d399'}}>Finance</b><div style={{color:'#64748b',fontSize:8}}>Tx #{r.finance_transaction_id??'—'}{r.finance_purchase_date?` · ${r.finance_purchase_date}`:''}</div></>:<><b style={{color:'#fbbf24'}}>Manual</b><div style={{color:'#64748b',fontSize:8}}>{fin?`Finance reference ${money(r.finance_price_per_kg)} · Tx #${r.finance_transaction_id??'—'}${r.finance_purchase_date?` · ${r.finance_purchase_date}`:''}`:'No Finance price available'}</div></>}</td><td><b>{money(q*rate)}</b></td></tr>})}</tbody></table></div>
    <div style={{padding:12,display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8}}><Metric label="Draft Ration / Head / Day" value={`${rationKg.toLocaleString('en-PK',{maximumFractionDigits:3})} kg`}/><Metric label="Draft Cost / Head / Day" value={money(stageCost)}/><div style={panel}><div style={label}>Version Control</div><div style={{fontSize:9,color:'#94a3b8'}}>Saving creates a new governed TMR version and retains each selected price source.</div><button disabled={saving} onClick={()=>void save()} style={{...btn('#059669'),marginTop:7}}><Save size={12}/>{saving?'Saving…':'Save TMR'}</button></div></div></>}
   <div style={{margin:'0 12px 12px',...panel,border:endorsed?'1px solid #166534':'1px solid #92400e',display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><b><CheckCircle2 size={14}/> Weekly Vet TMR Review</b><div style={{fontSize:10,color:'#cbd5e1'}}>{weekly?.advisory||'Weekly TMR review status unavailable.'}</div>{weekly&&<small>Week {weekly.week_start} → {weekly.week_end}</small>}</div><div style={{display:'flex',gap:7,alignItems:'end'}}><input placeholder="Vet Name / ID" value={reviewer} disabled={endorsed} onChange={e=>setReviewer(e.target.value)} style={input}/><input placeholder="Review Notes" value={reviewNotes} disabled={endorsed} onChange={e=>setReviewNotes(e.target.value)} style={input}/><button disabled={endorsed||endorsing||!reviewer.trim()} onClick={()=>void endorse()} style={btn('#059669')}>{endorsed?'Endorsed':endorsing?'Endorsing…':'Vet Endorse TMR Review'}</button></div></div>
   <div style={{padding:'0 12px 12px',color:'#64748b',fontSize:9}}>{summary.feed_cost_basis} · Operational date: {summary.operational_date} · TMR whole-herd feed cost is the governed Feed Cost / L input to Auto COP.</div>
  </>}
 </div>
}
function Metric({label:metricLabel,value}:{label:string;value:string}){return <div style={panel}><div style={label}>{metricLabel}</div><div style={{color:'#38bdf8',fontSize:16,fontWeight:900,marginTop:4}}>{value}</div></div>}
