import React,{useEffect,useMemo,useState} from 'react';
import {CalendarClock,CheckCircle2,Plus,Search,ShieldCheck,X} from 'lucide-react';
import AnimalPassportModal from './AnimalPassportModal';
import {apiUrl} from '../config/api';
interface HerdAnimal{id:string;breed:string;category:string;status:string}
type Vax={id:string;animalId:string;date:string;vaccine:string;dose:string;vet:string;batch:string;nextDue:string;category:string}
interface Props{onOpenPassport?:(id:string)=>void;herdMasterList?:HerdAnimal[];onChanged?:()=>void}
const VACCINES=['Foot-and-Mouth Disease (FMD)','Hemorrhagic Septicemia (HS)','Black Quarter (BQ)','Lumpy Skin Disease (LSD)','Brucellosis','Anthrax','Bovine Viral Diarrhea (BVD)','IBR / Respiratory complex','Clostridial disease','Calf scours / enteric disease','Other'];
const field:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#0f172a',color:'#fff',border:'1px solid #334155',padding:'9px 10px',borderRadius:6,fontSize:12};
const card:React.CSSProperties={background:'#111827',border:'1px solid #1f2937',borderRadius:8};
const th:React.CSSProperties={padding:'9px 10px',textAlign:'left',color:'#cbd5e1',fontSize:10,whiteSpace:'nowrap'};
const td:React.CSSProperties={padding:'9px 10px',borderTop:'1px solid #1f2937',verticalAlign:'top'};
const btn=(bg:string):React.CSSProperties=>({background:bg,color:'#fff',border:0,padding:'8px 11px',borderRadius:6,fontWeight:800,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:5,fontSize:11});
function d(v:unknown){if(!v)return'';const x=new Date(String(v));return Number.isNaN(x.getTime())?String(v).slice(0,10):x.toISOString().slice(0,10)}
function today(){const x=new Date(),o=x.getTimezoneOffset();return new Date(x.getTime()-o*60000).toISOString().slice(0,10)}
function rank(v:Vax){if(!v.nextDue)return Number.MAX_SAFE_INTEGER;return new Date(v.nextDue+'T00:00:00').getTime()}
async function get<T>(p:string):Promise<T>{const r=await fetch(apiUrl(p));if(!r.ok)throw new Error(`Request failed: ${r.status}`);return r.json() as Promise<T>}
async function post<T>(p:string,x:unknown):Promise<T>{const r=await fetch(apiUrl(p),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});if(!r.ok)throw new Error(`Request failed: ${r.status}`);return r.json() as Promise<T>}
function counts<T>(rows:T[],key:(r:T)=>string){const m=new Map<string,number>();rows.forEach(r=>{const k=key(r).trim()||'Unspecified';m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8)}
export default function VaccinationTab({onOpenPassport,herdMasterList=[],onChanged}:Props){
 const [rows,setRows]=useState<Vax[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[show,setShow]=useState(false),[passport,setPassport]=useState<string|null>(null),[saving,setSaving]=useState(false);
 const [animal,setAnimal]=useState(herdMasterList[0]?.id||''),[purpose,setPurpose]=useState(''),[vaccine,setVaccine]=useState(''),[dose,setDose]=useState(''),[route,setRoute]=useState(''),[batch,setBatch]=useState(''),[vet,setVet]=useState(''),[nextDue,setNextDue]=useState('');
 useEffect(()=>{if(herdMasterList.length&&!herdMasterList.some(a=>a.id===animal))setAnimal(herdMasterList[0].id)},[herdMasterList,animal]);
 const open=(id:string)=>onOpenPassport?onOpenPassport(id):setPassport(id);
 const load=async()=>{setLoading(true);setError('');try{const lists=await Promise.all(herdMasterList.map(async a=>{try{return {a,items:await get<any[]>(`/farm/animals/${encodeURIComponent(a.id)}/vaccinations`)}}catch{return {a,items:[]}}}));setRows(lists.flatMap(({a,items})=>items.map((x,i)=>({id:`VAX-${a.id}-${x.administered_date||i}`,animalId:String(x.animal_id||a.id),date:d(x.administered_date),vaccine:String(x.vaccine||x.vaccination||'Vaccination'),dose:String(x.dose||'-'),vet:String(x.veterinarian||x.operator||'API'),batch:String(x.batch_number||x.batch||'-'),nextDue:d(x.next_due_date),category:a.category}))).sort((a,b)=>rank(a)-rank(b)||b.date.localeCompare(a.date)))}catch(e){setError(e instanceof Error?e.message:'Unable to load Vaccination register.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[herdMasterList]);
 const t=today(),overdue=useMemo(()=>rows.filter(r=>r.nextDue&&r.nextDue<t).length,[rows,t]),due30=useMemo(()=>{const x=new Date();x.setDate(x.getDate()+30);const end=x.toISOString().slice(0,10);return rows.filter(r=>r.nextDue&&r.nextDue>=t&&r.nextDue<=end).length},[rows,t]),thisMonth=useMemo(()=>rows.filter(r=>r.date.startsWith(t.slice(0,7))).length,[rows,t]),recorded=new Set(rows.map(r=>r.animalId)),noHistory=herdMasterList.filter(a=>!recorded.has(a.id)).length;
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?rows.filter(r=>`${r.animalId} ${r.vaccine} ${r.batch} ${r.vet} ${r.category}`.toLowerCase().includes(q)):rows},[rows,search]);
 const vaxStats=useMemo(()=>counts(rows,r=>r.vaccine),[rows]),catStats=useMemo(()=>counts(rows,r=>r.category),[rows]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{await post(`/farm/animals/${encodeURIComponent(animal)}/vaccinations`,{vaccine:vaccine||purpose,dose,route:route||null,administered_date:today(),veterinarian:vet||null,notes:purpose,operator:vet||'Operator UI',batch_number:batch||null,next_due_date:nextDue||null});setShow(false);setPurpose('');setVaccine('');setDose('');setRoute('');setBatch('');setNextDue('');setMessage('Vaccination marked GIVEN and permanent next-due schedule updated.');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to save vaccination.')}finally{setSaving(false)}};
 return <div style={{padding:16,color:'#fff',height:'100%',overflowY:'auto',boxSizing:'border-box'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',flexWrap:'wrap',marginBottom:12}}><div><h2 style={{margin:0,color:'#22c55e',display:'flex',gap:7,alignItems:'center'}}><ShieldCheck size={20}/>Vaccination</h2><div style={{fontSize:11,color:'#94a3b8'}}>Preventive herd protection: due worklist, completed register and coverage gaps.</div></div><button onClick={()=>setShow(true)} style={btn('#15803d')}><Plus size={14}/>Record Vaccination Given</button></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:8,marginBottom:12}}><Metric title="Overdue Vaccinations" value={overdue}/><Metric title="Due Next 30 Days" value={due30}/><Metric title="Vaccinated This Month" value={thisMonth}/><Metric title="Animals With No Vax History" value={noHistory}/></div>
 {error&&<Notice error text={error}/>} {message&&<Notice text={message}/>}
 <section style={{...card,marginBottom:12,overflowX:'auto'}}><div style={{padding:12,display:'flex',justifyContent:'space-between',gap:8,flexWrap:'wrap'}}><strong style={{display:'flex',gap:6,alignItems:'center'}}><CalendarClock size={15}/>Action Queue - earliest due first</strong><SearchBox value={search} set={setSearch}/></div><table style={{width:'100%',minWidth:980,borderCollapse:'collapse',fontSize:11}}><thead><tr><th style={th}>Next Due</th><th style={th}>Due State</th><th style={th}>Given Date</th><th style={th}>Animal</th><th style={th}>Category</th><th style={th}>Vaccine</th><th style={th}>Dose</th><th style={th}>Batch</th><th style={th}>Administrator</th><th style={th}>Record</th></tr></thead><tbody>{!loading&&filtered.map(r=>{const state=!r.nextDue?'Unscheduled':r.nextDue<t?'OVERDUE':r.nextDue===t?'DUE TODAY':'Scheduled';return <tr key={r.id}><td style={{...td,fontWeight:900,color:state==='OVERDUE'?'#f87171':state==='DUE TODAY'?'#fbbf24':'#e2e8f0'}}>{r.nextDue||'-'}</td><td style={td}>{state}</td><td style={td}>{r.date}</td><td style={td}><button onClick={()=>open(r.animalId)} style={{background:'none',border:0,color:'#7dd3fc',fontWeight:800,cursor:'pointer'}}>#{r.animalId}</button></td><td style={td}>{r.category}</td><td style={td}>{r.vaccine}</td><td style={td}>{r.dose}</td><td style={td}>{r.batch}</td><td style={td}>{r.vet}</td><td style={td}><span style={{color:'#86efac',display:'inline-flex',gap:4}}><CheckCircle2 size={12}/>GIVEN</span></td></tr>})}</tbody></table></section>
 <section style={{...card,padding:12,marginBottom:12}}><strong>Vaccination Analytics</strong><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,marginTop:10}}><Stats title="Vaccines Recorded" rows={vaxStats}/><Stats title="Records by Animal Category" rows={catStats}/><Stats title="Schedule Signals" rows={[['Overdue',overdue],['Due next 30 days',due30],['No history',noHistory]]}/></div></section>
 {show&&<Modal close={()=>setShow(false)}><form onSubmit={save} style={{display:'grid',gap:10}}><strong>Record Vaccination Given</strong><Field label="Animal"><select required value={animal} onChange={e=>setAnimal(e.target.value)} style={field}>{herdMasterList.map(a=><option key={a.id} value={a.id}>{a.id} Â· {a.category}</option>)}</select></Field><Field label="Disease / Vaccine Purpose"><select required value={purpose} onChange={e=>setPurpose(e.target.value)} style={field}><option value="">Select purpose</option>{VACCINES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Vaccine"><select required value={vaccine} onChange={e=>setVaccine(e.target.value)} style={field}><option value="">Select vaccine</option>{VACCINES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Dose"><input required value={dose} onChange={e=>setDose(e.target.value)} style={field}/></Field><Field label="Route"><input value={route} onChange={e=>setRoute(e.target.value)} style={field} placeholder="SC, IM, etc."/></Field><Field label="Batch / Lot"><input value={batch} onChange={e=>setBatch(e.target.value)} style={field}/></Field><Field label="Veterinarian / Administrator"><input value={vet} onChange={e=>setVet(e.target.value)} style={field}/></Field><Field label="Next Due Date"><input type="date" value={nextDue} onChange={e=>setNextDue(e.target.value)} style={field}/></Field><button disabled={saving} style={btn('#15803d')}>Mark Vaccination GIVEN</button></form></Modal>}
 {passport&&<AnimalPassportModal animalId={passport} onClose={()=>setPassport(null)}/>}</div>
}
function Metric({title,value}:{title:string;value:React.ReactNode}){return <div style={card}><div style={{padding:11}}><div style={{fontSize:9,color:'#94a3b8',fontWeight:800,textTransform:'uppercase'}}>{title}</div><div style={{fontSize:20,fontWeight:900,marginTop:3}}>{value}</div></div></div>}
function Notice({text,error=false}:{text:string;error?:boolean}){return <div style={{background:error?'#450a0a':'#064e3b',color:error?'#fecaca':'#a7f3d0',padding:9,borderRadius:6,marginBottom:10,fontSize:11}}>{text}</div>}
function SearchBox({value,set}:{value:string;set:(x:string)=>void}){return <div style={{position:'relative',minWidth:260}}><Search size={13} style={{position:'absolute',left:9,top:10,color:'#64748b'}}/><input value={value} onChange={e=>set(e.target.value)} placeholder="Search animal, vaccine, batch, administrator" style={{...field,paddingLeft:28}}/></div>}
function Stats({title,rows}:{title:string;rows:Array<[string,number]>}){return <div style={{background:'#0f172a',border:'1px solid #1f2937',borderRadius:6,padding:10}}><div style={{fontSize:10,color:'#94a3b8',fontWeight:900}}>{title}</div>{rows.map(([n,c])=><div key={n} style={{display:'flex',justifyContent:'space-between',borderTop:'1px solid #1f2937',padding:'5px 0',fontSize:10}}><span>{n}</span><strong>{c}</strong></div>)}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{fontSize:10,color:'#94a3b8'}}>{label}{children}</label>}
function Modal({close,children}:{close:()=>void;children:React.ReactNode}){return <div style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(0,0,0,.82)',display:'flex',alignItems:'center',justifyContent:'center',padding:14,overflowY:'auto'}}><div style={{width:'min(620px,100%)',maxHeight:'calc(100vh - 28px)',overflowY:'auto',background:'#111827',border:'1px solid #22c55e',borderRadius:9,padding:18,boxSizing:'border-box',position:'relative'}}><button onClick={close} style={{position:'absolute',right:10,top:10,background:'none',border:0,color:'#fff'}}><X size={18}/></button>{children}</div></div>}
