from dataclasses import dataclass
from datetime import datetime


@dataclass
class OperationalSignal:
    """
    Represents an operational observation generated by DairyOS.
    """

    signal_id: str
    category: str
    description: str
    severity: str
    source: str
    created_at: datetime

    resolved: bool = False

    def resolve(self) -> None:
        self.resolved = True
