from dataclasses import dataclass, field
from datetime import datetime
from dairyos.core.time_utils import utcnow


@dataclass
class IntelligenceSignal:
    """
    Represents an intelligence observation generated by any DairyOS domain.
    """

    source: str
    category: str
    message: str
    severity: str = "normal"
    timestamp: datetime = field(default_factory=utcnow)