from dataclasses import dataclass
from datetime import datetime


@dataclass
class IntelligenceSignal:
    """
    Represents an intelligence observation generated by any DairyOS domain.
    """

    source: str
    category: str
    message: str
    severity: str = "normal"
    timestamp: datetime = datetime.utcnow()

