import React, { useCallback, useEffect, useMemo, useState } from "react";
import "./DairyOSShell.css";
import { getDashboard } from "../api/dashboardClient";
import type { DashboardResponse, OperationalDecision } from "../models/dashboard";
import { API_BASE_URL as API } from "../config/api";


type ViewId = "dashboard" | "animals" | "milk" | "feeding" | "health" | "breeding" | "workforce" | "inventory" | "equipment" | "finance" | "analytics" | "alerts" | "settings";
type Period = "7d" | "month" | "year" | "custom";
type FinanceView = "cash" | "bank" | "monthly" | "quarterly" | "yearly";
type Field = { name: string; label: string; type?: string; required?: boolean; options?: string[]; source?: "animals" | "workers" | "inventory" | "equipment" | "locations" | "breeds" };
type ModuleConfig = { endpoint: string; title: string; description: string; fields: Field[] };

const modules: Record<Exclude<ViewId, "dashboard" | "analytics" | "alerts" | "settings">, ModuleConfig> = {
  animals: { endpoint: "/farm/animals", title: "Animals", description: "Permanent herd registry and lifecycle records.", fields: [
    { name: "name", label: "Name" }, { name: "animal_type", label: "Animal Type", options: ["CATTLE", "BUFFALO"] },
    { name: "ear_tag", label: "Ear Tag" }, { name: "rfid", label: "RFID" }, { name: "breed", label: "Breed", source: "breeds" },
    { name: "sex", label: "Sex", options: ["FEMALE", "MALE"] }, { name: "date_of_birth", label: "Date of Birth", type: "date" },
    { name: "lifecycle_status", label: "Lifecycle", options: ["CALF", "HEIFER", "LACTATING", "DRY", "CLOSE_UP", "SICK", "CULLED"] },
    { name: "milking_frequency", label: "Milking Frequency", options: ["ONCE_DAILY", "TWICE_DAILY", "THRICE_DAILY"] },
    { name: "production_group", label: "Production Group" }, { name: "location", label: "Location", source: "locations" },
  ]},
  milk: { endpoint: "/farm/milk", title: "Milk Production", description: "Record production against a permanent animal ID.", fields: [
    { name: "animal_id", label: "Animal", required: true, source: "animals" }, { name: "milking_session", label: "Session", options: ["MORNING", "AFTERNOON", "EVENING"] },
    { name: "morning_yield", label: "Morning Yield (L)", type: "number" }, { name: "afternoon_yield", label: "Afternoon Yield (L)", type: "number" },
    { name: "evening_yield", label: "Evening Yield (L)", type: "number" }, { name: "operator", label: "Operator", source: "workers" },
  ]},
  feeding: { endpoint: "/farm/feed", title: "Feeding", description: "Live feed inputs and consumption records.", fields: [
    { name: "feed_type", label: "Feed", required: true, options: ["SILAGE", "VANDA", "WHEAT STRAW", "SOYBEAN MEAL", "MOLASSES", "MINERAL MIXTURE", "BYPASS FAT", "ANIONIC SALTS", "TOXIN BINDER", "LYSINE / METHIONINE"] },
    { name: "quantity_kg", label: "Quantity (kg)", type: "number", required: true }, { name: "group_or_pen", label: "Group / Pen" }, { name: "animal_id", label: "Animal", source: "animals" }, { name: "operator", label: "Operator", source: "workers" },
  ]},
  health: { endpoint: "/farm/health-observations", title: "Health", description: "Observations, treatment follow-up and animal safety context.", fields: [
    { name: "animal_id", label: "Animal", required: true, source: "animals" }, { name: "observation", label: "Observation", required: true }, { name: "symptom", label: "Symptom" },
    { name: "temperature_c", label: "Temperature (°C)", type: "number" }, { name: "severity", label: "Severity", options: ["NORMAL", "ELEVATED", "HIGH", "CRITICAL"] }, { name: "operator", label: "Operator", source: "workers" },
  ]},
  breeding: { endpoint: "/farm/breeding", title: "Breeding", description: "Heat, insemination, pregnancy and calving events.", fields: [
    { name: "animal_id", label: "Animal", required: true, source: "animals" }, { name: "event_type", label: "Event", required: true, options: ["heat_detected", "insemination", "pregnancy_diagnosis", "pregnancy_confirmed", "pregnancy_negative", "dry_off", "calving"] },
    { name: "technician", label: "Technician", source: "workers" }, { name: "result", label: "Result" }, { name: "notes", label: "Notes" }, { name: "operator", label: "Operator", source: "workers" },
  ]},
  workforce: { endpoint: "/farm/workforce", title: "Workforce", description: "People, assignments and completed work.", fields: [
    { name: "worker_id", label: "Worker ID", required: true }, { name: "activity", label: "Activity", required: true, options: ["MILKING", "FEEDING", "CLEANING", "HEALTH", "BREEDING", "INVENTORY", "EQUIPMENT", "GENERAL"] },
    { name: "task", label: "Task" }, { name: "status", label: "Status", options: ["ASSIGNED", "IN_PROGRESS", "COMPLETED", "MISSED"] }, { name: "hours", label: "Hours", type: "number" }, { name: "location", label: "Location", source: "locations" }, { name: "operator", label: "Recorded By", source: "workers" },
  ]},
  inventory: { endpoint: "/farm/inventory", title: "Inventory", description: "Stock movement, receipts, consumption and alerts.", fields: [
    { name: "item", label: "Item", required: true, source: "inventory" }, { name: "quantity", label: "Quantity", type: "number", required: true },
    { name: "movement_type", label: "Movement", options: ["PURCHASE", "RECEIPT", "CONSUMPTION", "TRANSFER", "WASTAGE", "ADJUSTMENT"] }, { name: "unit", label: "Unit", options: ["kg", "L", "g", "unit", "pack"] },
    { name: "location", label: "Location", source: "locations" }, { name: "supplier", label: "Supplier" }, { name: "operator", label: "Operator", source: "workers" },
  ]},
  equipment: { endpoint: "/farm/equipment", title: "Equipment", description: "Operating status, inspections and maintenance records.", fields: [
    { name: "equipment_id", label: "Equipment ID", required: true, source: "equipment" }, { name: "activity", label: "Activity", required: true, options: ["INSPECTION", "MAINTENANCE", "BREAKDOWN", "SERVICE", "OPERATING"] },
    { name: "status", label: "Status", options: ["OPERATIONAL", "WARNING", "OUT_OF_SERVICE", "MAINTENANCE"] }, { name: "running_hours", label: "Running Hours", type: "number" }, { name: "location", label: "Location", source: "locations" }, { name: "notes", label: "Notes" }, { name: "operator", label: "Operator", source: "workers" },
  ]},
  finance: { endpoint: "/farm/financial", title: "Finance", description: "Cash, bank, income, expense and reconciliation records.", fields: [
    { name: "transaction_type", label: "Transaction Type", required: true, options: ["INCOME", "EXPENSE", "RECEIPT", "PAYMENT", "OWNER_WITHDRAWAL", "LOAN_PAYMENT"] }, { name: "amount", label: "Amount (PKR)", type: "number", required: true },
    { name: "category", label: "Category", options: ["MILK SALES", "FEED", "MEDICINE", "LABOUR", "UTILITIES", "EQUIPMENT", "BREEDING", "TRANSPORT", "OTHER"] }, { name: "payment_method", label: "Account", options: ["CASH", "BANK", "MOBILE", "CREDIT"] },
    { name: "counterparty", label: "Counterparty" }, { name: "notes", label: "Notes" }, { name: "operator", label: "Operator", source: "workers" },
  ]},
};

const nav: Array<{ id: ViewId; label: string; icon: string }> = [
  { id: "dashboard", label: "Dashboard", icon: "⌂" }, { id: "animals", label: "Animals", icon: "◉" }, { id: "milk", label: "Milk", icon: "◌" },
  { id: "feeding", label: "Feeding", icon: "≋" }, { id: "health", label: "Health", icon: "✚" }, { id: "breeding", label: "Breeding", icon: "♧" },
  { id: "workforce", label: "Workforce", icon: "♙" }, { id: "inventory", label: "Inventory", icon: "▤" }, { id: "equipment", label: "Equipment", icon: "⚙" },
  { id: "finance", label: "Finance", icon: "₨" }, { id: "analytics", label: "Analytics", icon: "⌁" }, { id: "alerts", label: "Alerts", icon: "!" },
];

function unwrap(value: unknown): unknown[] { if (Array.isArray(value)) return value; if (!value || typeof value !== "object") return []; const o = value as Record<string, unknown>; for (const k of ["items", "data", "records", "results", "events", "animals", "transactions"]) if (Array.isArray(o[k])) return o[k] as unknown[]; return []; }
function rec(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function num(v: unknown): number | null { const n = typeof v === "number" ? v : Number(v); return Number.isFinite(n) ? n : null; }
function fmt(v: unknown, suffix = ""): string { const n = num(v); return n === null ? "—" : `${n.toLocaleString(undefined, { maximumFractionDigits: 1 })}${suffix}`; }
function animalLabel(a: Record<string, unknown>): string { return String(a.animal_id ?? a.id ?? ""); }
function dateOf(r: Record<string, unknown>): number { const v = r.timestamp ?? r.created_at ?? r.date ?? r.recorded_at; const d = typeof v === "string" ? new Date(v).getTime() : 0; return Number.isFinite(d) ? d : 0; }

function useLiveJson(endpoint: string | null, refresh = 30000) {
  const [data, setData] = useState<unknown>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { if (!endpoint) return; setLoading(true); setError(null); try { const r = await fetch(`${API}${endpoint}`, { headers: { Accept: "application/json" } }); if (!r.ok) throw new Error(`Request failed: ${r.status}`); setData(await r.json()); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load live data."); } finally { setLoading(false); } }, [endpoint]);
  useEffect(() => { void load(); if (!endpoint) return; const t = window.setInterval(() => void load(), refresh); return () => window.clearInterval(t); }, [endpoint, refresh, load]);
  return { data, error, loading, reload: load };
}

function Card({ title, action, children, className = "" }: { title: string; action?: React.ReactNode; children: React.ReactNode; className?: string }) { return <section className={`dos-card ${className}`}><div className="dos-card-head"><h2>{title}</h2>{action}</div><div className="dos-card-body">{children}</div></section>; }
function Kpi({ label, value, sub, tone = "" }: { label: string; value: string; sub?: string; tone?: string }) { return <div className={`dos-kpi ${tone}`}><span>{label}</span><strong>{value}</strong>{sub && <small>{sub}</small>}</div>; }
function Button({ children, onClick, kind = "secondary", type = "button" }: { children: React.ReactNode; onClick?: () => void; kind?: "primary" | "secondary" | "ghost" | "danger"; type?: "button" | "submit" }) { return <button type={type} className={`dos-btn ${kind}`} onClick={onClick}>{children}</button>; }

function Table({ rows, onRow }: { rows: Record<string, unknown>[]; onRow?: (r: Record<string, unknown>) => void }) {
  const columns = useMemo(() => { const s = new Set<string>(); rows.slice(0, 30).forEach(r => Object.keys(r).slice(0, 8).forEach(k => s.add(k))); return [...s].slice(0, 8); }, [rows]);
  if (!rows.length) return <div className="dos-empty">No live records available.</div>;
  return <div className="dos-table-wrap"><table className="dos-table"><thead><tr>{columns.map(c => <th key={c}>{c.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{rows.slice(0, 40).map((r, i) => <tr key={i} className={onRow ? "clickable" : ""} onClick={() => onRow?.(r)}>{columns.map(c => <td key={c}>{typeof r[c] === "object" ? JSON.stringify(r[c]) : String(r[c] ?? "—")}</td>)}</tr>)}</tbody></table></div>;
}

function Donut({ segments }: { segments: Array<{ label: string; value: number }> }) {
  const total = segments.reduce((a, b) => a + b.value, 0); let cursor = 0; const colors = ["#2f9d67", "#3b82f6", "#8b5cf6", "#f59e0b", "#94a3b8"];
  const gradient = total ? `conic-gradient(${segments.map((s, i) => { const start = cursor / total * 100; cursor += s.value; return `${colors[i % colors.length]} ${start}% ${cursor / total * 100}%`; }).join(",")})` : "#e7ece8";
  return <div className="donut-wrap"><div className="donut" style={{ background: gradient }}><div className="donut-hole"><strong>{total}</strong><span>head</span></div></div><div className="legend">{segments.map((s, i) => <div className="legend-row" key={s.label}><span><i style={{ background: colors[i % colors.length] }} />{s.label}</span><b>{s.value}</b></div>)}</div></div>;
}

function LineChart({ points }: { points: Array<{ label: string; value: number }> }) {
  if (!points.length) return <div className="dos-empty">No live production history returned.</div>;
  const w = 700, h = 220, p = 24, max = Math.max(...points.map(x => x.value), 1); const path = points.map((x, i) => { const px = p + (i / Math.max(points.length - 1, 1)) * (w - p * 2); const py = h - p - (x.value / max) * (h - p * 2); return `${i ? "L" : "M"}${px.toFixed(1)},${py.toFixed(1)}`; }).join(" ");
  return <div className="line-chart"><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none"><path d={path} fill="none" stroke="currentColor" strokeWidth="3" vectorEffect="non-scaling-stroke" /></svg><div className="chart-labels">{points.map(x => <span key={x.label}>{x.label}</span>)}</div></div>;
}

function CommandCenter({ dashboard, onOpen, onQuick }: { dashboard: DashboardResponse | null; onOpen: (id: ViewId) => void; onQuick: (id: ViewId) => void }) {
  const runtime = (dashboard?.dashboard ?? {}) as Record<string, unknown>; const state = (dashboard?.operational_state ?? {}) as Record<string, unknown>; const decisions = (state.decisions ?? dashboard?.decisions ?? []) as OperationalDecision[]; const animals = rec(runtime.animals ?? runtime.herd); const milk = rec(runtime.milk ?? runtime.milk_production); const finance = rec(runtime.finance); const herd = unwrap(animals.items ?? animals.records ?? runtime.animals); const milking = herd.filter(x => { const a = rec(x); return a.is_currently_milking === true || String(a.lifecycle_status).toUpperCase() === "LACTATING"; }).length; const dry = herd.filter(x => String(rec(x).lifecycle_status).toUpperCase() === "DRY").length;
  const totalMilk = num(milk.today_litres ?? milk.total_litres ?? milk.today) ?? num(runtime.milk_today_litres); const financeToday = num(finance.today ?? finance.today_amount ?? runtime.finance_today);
  const yieldAlerts = decisions.filter(d => JSON.stringify(d).toLowerCase().match(/(yield|milk|production)/) && JSON.stringify(d).toLowerCase().match(/(drop|declin|decreas)/) && Number((JSON.stringify(d).match(/(\d+(?:\.\d+)?)\s*%/) ?? [])[1]) > 20);
  const segments = [{ label: "Milking", value: milking }, { label: "Dry", value: dry }, { label: "Heifers", value: herd.filter(x => ["HEIFER", "CLOSE_UP"].includes(String(rec(x).lifecycle_status).toUpperCase())).length }, { label: "Calves", value: herd.filter(x => String(rec(x).lifecycle_status).toUpperCase() === "CALF").length }].filter(x => x.value > 0);
  return <div className="dashboard-grid">
    <div className="kpi-grid"><Kpi label="Herd" value={fmt(runtime.herd_count ?? runtime.total_animals ?? herd.length)} sub="registered animals" /><Kpi label="Milk Today" value={fmt(totalMilk, " L")} sub="live production" /><Kpi label="Health" value={fmt(runtime.active_health_issues ?? runtime.health_issues)} sub="active issues" tone="warning" /><Kpi label="Breeding" value={fmt(runtime.active_breeding_cases ?? runtime.breeding_cases)} sub="active cases" /><Kpi label="Finance Today" value={financeToday === null ? "—" : `PKR ${financeToday.toLocaleString()}`} sub="select account / period" /></div>
    <div className="dashboard-main">
      <Card title="Herd Composition" action={<Button kind="ghost" onClick={() => onOpen("animals")}>View details →</Button>}><Donut segments={segments} /></Card>
      <Card title="Milk Production" action={<Button kind="ghost" onClick={() => onOpen("milk")}>Open Milk →</Button>}><div className="dashboard-milk"><div><strong>{fmt(totalMilk, " L")}</strong><span>Today</span></div><div className="mini-bars"><i /><i /><i /><i /><i /><i /><i /></div><small>Choose 7 days, month, year or any custom timeframe inside Milk.</small></div></Card>
      <Card title="Production Intelligence" className="alert-card" action={<Button kind="ghost" onClick={() => onOpen("alerts")}>Open alerts →</Button>}><div className="alert-summary"><strong>{yieldAlerts.length || 0}</strong><span>animal yield alerts above 20% drop</span></div>{yieldAlerts.slice(0, 2).map((d, i) => <div className="alert-row" key={i}><b>{d.title ?? d.type ?? "Yield alert"}</b><span>{d.action ?? "Review animal production history"}</span></div>)}</Card>
      <Card title="Finance" action={<Button kind="ghost" onClick={() => onOpen("finance")}>Open Finance →</Button>}><div className="finance-select-note"><b>Choose view in Finance</b><span>Cash in Hand · Money at Bank · Monthly · Quarterly · Yearly reconciliation</span></div></Card>
    </div>
    <Card title="Quick Access" className="quick-card"><div className="quick-grid"><button onClick={() => onQuick("animals")}><b>＋</b><span>Add Animal</span></button><button onClick={() => onQuick("milk")}><b>＋</b><span>Record Milk</span></button><button onClick={() => onQuick("health")}><b>＋</b><span>Record Health</span></button><button onClick={() => onQuick("breeding")}><b>＋</b><span>Add Breeding</span></button><button onClick={() => onQuick("finance")}><b>＋</b><span>Add Expense</span></button></div></Card>
  </div>;
}

function SettingsPage() {
  const [farmName, setFarmName] = useState(() => localStorage.getItem("dairyos.farmName") || "Meadowbrook Dairy"); const [operator, setOperator] = useState(() => localStorage.getItem("dairyos.operator") || "Farm Manager"); const [refresh, setRefresh] = useState(() => localStorage.getItem("dairyos.refresh") || "30");
  const save = () => { localStorage.setItem("dairyos.farmName", farmName); localStorage.setItem("dairyos.operator", operator); localStorage.setItem("dairyos.refresh", refresh); window.dispatchEvent(new Event("dairyos-settings")); };
  return <div className="module-page settings-page"><div className="page-heading"><div><span className="eyebrow">SYSTEM</span><h1>Settings</h1><p>Farm identity, operator defaults and display behaviour.</p></div><Button kind="primary" onClick={save}>Save settings</Button></div><div className="settings-grid"><Card title="Farm"><label>Farm name<input value={farmName} onChange={e => setFarmName(e.target.value)} /></label><label>Default operator<input value={operator} onChange={e => setOperator(e.target.value)} /></label></Card><Card title="Live data"><label>Refresh interval<select value={refresh} onChange={e => setRefresh(e.target.value)}><option value="15">15 seconds</option><option value="30">30 seconds</option><option value="60">60 seconds</option></select></label><div className="setting-note">Dashboard values remain live-only. No synthetic operating values are introduced by the frontend.</div></Card><Card title="Animal identity"><div className="identity-lock"><b>Permanent system-generated ID</b><span>Operators never type or edit Animal ID. DairyOS derives the next available ID from the live herd registry and stores it with the animal record.</span></div></Card></div></div>;
}

function ModulePage({ id, initialAction }: { id: Exclude<ViewId, "dashboard" | "analytics" | "alerts" | "settings">; initialAction?: "add"; onDone?: () => void }) {
  const config = modules[id]; const live = useLiveJson(config.endpoint); const animals = useLiveJson(id === "animals" ? null : "/farm/animals"); const workers = useLiveJson(id === "workforce" ? null : "/farm/workforce"); const inventory = useLiveJson(id === "inventory" ? null : "/farm/inventory"); const equipment = useLiveJson(id === "equipment" ? null : "/farm/equipment"); const [formOpen, setFormOpen] = useState(initialAction === "add"); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [period, setPeriod] = useState<Period>("7d"); const [financeView, setFinanceView] = useState<FinanceView>("cash"); const [customFrom, setCustomFrom] = useState(""); const [customTo, setCustomTo] = useState("");
  useEffect(() => { if (initialAction === "add") setFormOpen(true); }, [initialAction]);
  const rows = useMemo(() => unwrap(live.data).map(rec).sort((a, b) => dateOf(b) - dateOf(a)), [live.data]); const animalRows = useMemo(() => unwrap(animals.data).map(rec), [animals.data]); const workerRows = useMemo(() => unwrap(workers.data).map(rec), [workers.data]); const inventoryRows = useMemo(() => unwrap(inventory.data).map(rec), [inventory.data]); const equipmentRows = useMemo(() => unwrap(equipment.data).map(rec), [equipment.data]);
  const options = useMemo(() => ({ animals: animalRows.map(animalLabel).filter(Boolean), workers: workerRows.map(x => String(x.worker_id ?? x.name ?? "")).filter(Boolean), inventory: [...new Set(inventoryRows.map(x => String(x.item ?? "")).filter(Boolean))], equipment: [...new Set(equipmentRows.map(x => String(x.equipment_id ?? "")).filter(Boolean))], locations: [...new Set([...animalRows, ...workerRows, ...inventoryRows, ...equipmentRows].map(x => String(x.location ?? "")).filter(Boolean))], breeds: [...new Set(animalRows.map(x => String(x.breed ?? "")).filter(Boolean))] }), [animalRows, workerRows, inventoryRows, equipmentRows]);
  const [values, setValues] = useState<Record<string, string>>({});
  useEffect(() => { const next: Record<string, string> = {}; config.fields.forEach(f => { if (f.options?.length) next[f.name] = f.options[0]; }); setValues(next); }, [id]);
  const generatedId = useMemo(() => { if (id !== "animals") return ""; const ids = animalRows.map(x => String(x.animal_id ?? "")).map(s => Number((s.match(/(\d+)$/) ?? [])[1])).filter(Number.isFinite); const next = Math.max(0, ...ids) + 1; return `AN-${String(next).padStart(6, "0")}`; }, [animalRows, id]);
  const fieldOptions = (f: Field) => f.source ? options[f.source] : f.options ?? [];
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); setMessage(null); try { const payload: Record<string, unknown> = { ...values }; if (id === "animals") payload.animal_id = generatedId; Object.keys(payload).forEach(k => { if (payload[k] === "") delete payload[k]; }); const r = await fetch(`${API}${config.endpoint}`, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify(payload) }); if (!r.ok) { const t = await r.text(); throw new Error(t || `Request failed: ${r.status}`); } setValues({}); setFormOpen(false); setMessage(id === "animals" ? `Animal ${generatedId} created. The ID is permanent.` : "Record saved successfully."); await live.reload(); } catch (err) { setMessage(err instanceof Error ? err.message : "Unable to save record."); } finally { setSaving(false); } };
  const filteredRows = useMemo(() => { if (id !== "milk") return rows; const now = Date.now(); const from = period === "7d" ? now - 7 * 864e5 : period === "month" ? now - 31 * 864e5 : period === "year" ? now - 366 * 864e5 : customFrom ? new Date(customFrom).getTime() : 0; const to = period === "custom" && customTo ? new Date(customTo).getTime() + 864e5 : now + 864e5; return rows.filter(r => { const d = dateOf(r); return d >= from && d <= to; }); }, [rows, id, period, customFrom, customTo]);
  return <div className="module-page"><div className="page-heading"><div><span className="eyebrow">OPERATIONS</span><h1>{config.title}</h1><p>{config.description}</p></div><div className="heading-actions">{id === "milk" && <select value={period} onChange={e => setPeriod(e.target.value as Period)}><option value="7d">7 days</option><option value="month">Month</option><option value="year">Year</option><option value="custom">Custom timeframe</option></select>}{id === "finance" && <select value={financeView} onChange={e => setFinanceView(e.target.value as FinanceView)}><option value="cash">Cash in Hand</option><option value="bank">Money at Bank</option><option value="monthly">Monthly Reconciliation</option><option value="quarterly">Quarterly Reconciliation</option><option value="yearly">Yearly Reconciliation</option></select>}<Button kind="primary" onClick={() => setFormOpen(true)}>＋ Add {config.title === "Animals" ? "Animal" : "Record"}</Button></div></div>
    {id === "milk" && period === "custom" && <div className="period-strip"><label>From<input type="date" value={customFrom} onChange={e => setCustomFrom(e.target.value)} /></label><label>To<input type="date" value={customTo} onChange={e => setCustomTo(e.target.value)} /></label></div>}
    {id === "finance" && <div className="finance-strip"><Kpi label={financeView === "cash" ? "Cash in Hand" : financeView === "bank" ? "Money at Bank" : financeView === "monthly" ? "Monthly Reconciliation" : financeView === "quarterly" ? "Quarterly Reconciliation" : "Yearly Reconciliation"} value="—" sub="calculated from live records" /></div>}
    {message && <div className="dos-message">{message}</div>}
    <Card title={id === "milk" ? `Milk records · ${period === "7d" ? "7 days" : period === "month" ? "month" : period === "year" ? "year" : "custom"}` : id === "finance" ? financeView.replaceAll("_", " ") : "Live records"} action={<span className="live-dot">● Live</span>}><Table rows={id === "milk" ? filteredRows : rows} onRow={id === "animals" ? r => setMessage(`Selected permanent ID: ${String(r.animal_id ?? r.id ?? "—")}`) : undefined} /></Card>
    {formOpen && <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">QUICK ENTRY</span><h2>{config.title === "Animals" ? "Add Animal" : `Add ${config.title} record`}</h2></div><button className="modal-close" onClick={() => setFormOpen(false)}>×</button></div>{id === "animals" && <div className="generated-id"><span>System-generated permanent Animal ID</span><strong>{generatedId || "Preparing…"}</strong></div>}<form className="entry-grid" onSubmit={submit}>{config.fields.map(f => <label key={f.name}>{f.label}{f.required && <em> *</em>}{f.options || f.source ? <select required={f.required} value={values[f.name] ?? ""} onChange={e => setValues(v => ({ ...v, [f.name]: e.target.value }))}><option value="">Select…</option>{fieldOptions(f).map(o => <option key={o} value={o}>{o}</option>)}</select> : <input required={f.required} type={f.type ?? "text"} value={values[f.name] ?? ""} onChange={e => setValues(v => ({ ...v, [f.name]: e.target.value }))} />}</label>)}<div className="form-actions"><Button kind="secondary" onClick={() => setFormOpen(false)}>Cancel</Button><Button kind="primary" type="submit">{saving ? "Saving…" : "Save record"}</Button></div></form></div></div>}
  </div>;
}

function AnalyticsPage({ dashboard }: { dashboard: DashboardResponse | null }) { const milk = useLiveJson("/farm/milk"); const rows = unwrap(milk.data).map(rec); const points = rows.sort((a, b) => dateOf(a) - dateOf(b)).slice(-14).map((r) => ({ label: new Date(dateOf(r) || Date.now()).toLocaleDateString(undefined, { month: "short", day: "numeric" }), value: num(r.total_yield ?? r.litres ?? r.morning_yield ?? 0) ?? 0 })); return <div className="module-page"><div className="page-heading"><div><span className="eyebrow">INTELLIGENCE</span><h1>Analytics</h1><p>Live operational trends from recorded farm inputs.</p></div></div><div className="analytics-grid"><Card title="Milk trend · recent live records"><LineChart points={points} /></Card><Card title="Operational state"><pre className="state-json">{JSON.stringify(dashboard?.operational_state ?? {}, null, 2)}</pre></Card></div></div>; }

function AlertsPage({ dashboard }: { dashboard: DashboardResponse | null }) { const decisions = ((dashboard?.operational_state?.decisions ?? dashboard?.decisions ?? []) as OperationalDecision[]).filter(Boolean); const alerts = decisions.filter(d => /alert|warning|exception|drop|declin|low stock/i.test(JSON.stringify(d))); return <div className="module-page"><div className="page-heading"><div><span className="eyebrow">NOTIFICATIONS</span><h1>Alerts</h1><p>Actionable notifications generated from live operational intelligence.</p></div></div><Card title={`${alerts.length} active notification${alerts.length === 1 ? "" : "s"}`}><div className="notification-list">{alerts.length ? alerts.map((d, i) => <div className="notification" key={i}><div className="notification-id">N-{String(i + 1).padStart(4, "0")}</div><div><b>{d.title ?? d.type ?? "Operational notification"}</b><p>{d.action ?? "Review the affected record."}</p></div></div>) : <div className="dos-empty">No active notifications.</div>}</div></Card></div>; }

export default function DairyOSShell() {
  const [view, setView] = useState<ViewId>("dashboard"); const [dashboard, setDashboard] = useState<DashboardResponse | null>(null); const [error, setError] = useState<string | null>(null); const [quick, setQuick] = useState<{ id: ViewId; action?: "add" } | null>(null); const [farmName, setFarmName] = useState(() => localStorage.getItem("dairyos.farmName") || "Meadowbrook Dairy");
  const loadDashboard = useCallback(async () => { try { setDashboard(await getDashboard()); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load live dashboard."); } }, []);
  useEffect(() => { void loadDashboard(); const t = window.setInterval(() => void loadDashboard(), Number(localStorage.getItem("dairyos.refresh") || 30) * 1000); const settings = () => setFarmName(localStorage.getItem("dairyos.farmName") || "Meadowbrook Dairy"); window.addEventListener("dairyos-settings", settings); return () => { window.clearInterval(t); window.removeEventListener("dairyos-settings", settings); }; }, [loadDashboard]);
  const decisionCount = ((dashboard?.operational_state?.decisions ?? dashboard?.decisions ?? []) as OperationalDecision[]).filter(d => /alert|warning|exception|drop|declin|low stock/i.test(JSON.stringify(d))).length;
  const open = (id: ViewId) => { setQuick(null); setView(id); }; const quickOpen = (id: ViewId) => { if (id === "animals" || id === "milk" || id === "health" || id === "breeding" || id === "finance") { setQuick({ id, action: "add" }); setView(id); } else setView(id); };
  return <div className="dairyos-shell"><aside className="dos-sidebar"><div className="brand"><div className="brand-mark">D</div><div><strong>DairyOS</strong><span>Intelligent Farm Operations</span></div></div><div className="farm-chip"><b>{farmName}</b><span>Farm Manager</span></div><nav>{nav.map(n => <button key={n.id} className={view === n.id ? "active" : ""} onClick={() => open(n.id)}><i>{n.icon}</i><span>{n.label}</span>{n.id === "alerts" && decisionCount > 0 && <b className="nav-badge">{decisionCount}</b>}</button>)}</nav><div className="sidebar-bottom"><button className={view === "settings" ? "active" : ""} onClick={() => open("settings")}><i>⚙</i><span>Settings</span></button><div className="system-status"><span />All systems operational</div></div></aside>
    <main className="dos-main"><header className="dos-topbar"><div><span className="breadcrumb">{view === "dashboard" ? "Farm overview" : nav.find(n => n.id === view)?.label ?? "Settings"}</span><span className="system-copy">Live operational workspace</span></div><div className="top-actions"><button className="bell" onClick={() => open("alerts")} aria-label="Notifications">♢{decisionCount > 0 && <b>{decisionCount}</b>}</button><div className="user-chip"><span>RM</span><div><b>{localStorage.getItem("dairyos.operator") || "Ramesh"}</b><small>Farm Manager</small></div></div></div></header><div className="dos-content">{error && <div className="dos-error">{error}</div>}{view === "dashboard" && <CommandCenter dashboard={dashboard} onOpen={open} onQuick={quickOpen} />}{view === "analytics" && <AnalyticsPage dashboard={dashboard} />}{view === "alerts" && <AlertsPage dashboard={dashboard} />}{view === "settings" && <SettingsPage />}{Object.prototype.hasOwnProperty.call(modules, view) && <ModulePage id={view as Exclude<ViewId, "dashboard" | "analytics" | "alerts" | "settings">} initialAction={quick?.id === view ? quick.action : undefined} onDone={() => setQuick(null)} />}</div></main></div>;
}
