from dataclasses import dataclass, field


@dataclass(frozen=True)
class MilkProductionTrendIntelligence:
    """Read-only date-based milk production trend analytics.

    This object is deliberately separate from alert semantics. It describes
    the verified daily farm series over a selected period. Drop alerts are
    generated by the individual-animal and herd daily-comparison boundaries.
    """

    reference_date: str | None = None
    last_date: str | None = None
    current_total_litres: float | None = None
    last_date_total_litres: float | None = None
    variance_litres: float | None = None
    variance_percentage: float | None = None
    comparison_status: str = "NO_COMPARISON"
    trend_direction: str = "UNKNOWN"
    period_days: int = 30
    series: list = field(default_factory=list)
    signals: list = field(default_factory=list)

    def summary(self):
        return {
            "reference_date": self.reference_date,
            "last_date": self.last_date,
            "current_total_litres": self.current_total_litres,
            "last_date_total_litres": self.last_date_total_litres,
            "variance_litres": self.variance_litres,
            "variance_percentage": self.variance_percentage,
            "comparison_status": self.comparison_status,
            "trend_direction": self.trend_direction,
            "period_days": self.period_days,
            "series": self.series,
            "signals": self.signals,
        }
