import React, { useState, useEffect, useCallback } from 'react';
import UnifiedDashboard from './components/UnifiedDashboard';
import FinanceTab from './components/FinanceTab';
import FeedTab from './components/FeedTab';
import COML from './components/COML';
import Analytics from './components/Analytics';
import FarmIntelligenceWidget from './components/FarmIntelligenceWidget';
import DigitalTwinPanel from './components/DigitalTwinPanel';
import SettingsTab from './components/SettingsTab';
import AuditTab from './components/AuditTab';
import MilkTab from './components/MilkTab';
import HealthTab from './components/HealthTab';
import BreedingTab from './components/BreedingTab';
import AnimalTab from './components/AnimalTab';
import AnimalPassportModal from './components/AnimalPassportModal';
import PayrollWindow from './components/PayrollWindow';
import { API_BASE_URL } from './config/api';
import { useAlertAudit } from './context/AlertAuditContext';
import { LayoutDashboard, Calculator, BarChart3, DollarSign, Milk, HeartPulse, Activity, Settings, Bell, Wheat, Users, WalletCards } from 'lucide-react';
import './App.css';

interface HerdAnimal { id:string; breed:string; category:string; age:string; status:string; frequency:string; earTag:string; gender?:string; stage?:string }
interface BackendAnimal { animal_id:string; animal_type?:string|null; animal_category?:string|null; ear_tag?:string|null; rfid?:string|null; breed?:string|null; sex?:string|null; date_of_birth?:string|null; lifecycle_status?:string|null; status?:string|null; milking_frequency?:string|null; active?:boolean; dam_id?:string|null; sire_id?:string|null; location?:string|null; production_group?:string|null }
function ageFromBirthDate(value?:string|null){if(!value)return 'Unknown';const birth=new Date(value);if(Number.isNaN(birth.getTime()))return 'Unknown';const now=new Date();let years=now.getFullYear()-birth.getFullYear();const before=now.getMonth()<birth.getMonth()||(now.getMonth()===birth.getMonth()&&now.getDate()<birth.getDate());if(before)years-=1;if(years>=1)return `${years} Years`;return `${Math.max(0,Math.floor((now.getTime()-birth.getTime())/2592000000))} Months`}
function toUiAnimal(animal:BackendAnimal):HerdAnimal{return{id:animal.animal_id,breed:animal.breed||'Unknown',category:animal.animal_category||'Unclassified',age:ageFromBirthDate(animal.date_of_birth),status:animal.active===false?(animal.status||'Inactive'):(animal.status||animal.lifecycle_status||'Active'),frequency:animal.milking_frequency||'NONE',earTag:animal.ear_tag||animal.animal_id,gender:(animal.sex||'').toUpperCase()==='MALE'?'Male':'Female',stage:animal.lifecycle_status||undefined}}

export default function MainAppShell(){
 const [currentView,setCurrentView]=useState('dashboard'),[selectedPassportAnimalId,setSelectedPassportAnimalId]=useState<string|null>(null),[autoOpenYieldModal,setAutoOpenYieldModal]=useState(false);
 const [farmName,setFarmName]=useState('DairyOS'),[farmLocation,setFarmLocation]=useState('');
 const {alerts,activeCount}=useAlertAudit();const [showNotifications,setShowNotifications]=useState(false);
 const [animals,setAnimals]=useState<BackendAnimal[]>([]);const [showAnimalModal,setShowAnimalModal]=useState(false),[todayYield,setTodayYield]=useState(0),[todayMilkSoldLiters,setTodayMilkSoldLiters]=useState(0),[accountsReceivable,setAccountsReceivable]=useState(0);
 const refreshAnimals=useCallback(async()=>{try{const response=await fetch(`${API_BASE_URL||'http://127.0.0.1:8000'}/farm/animals?active_only=false`);if(!response.ok)throw new Error(`Unable to load herd (${response.status})`);const payload = await response.json();const records = Array.isArray(payload) ? payload : Array.isArray(payload?.value) ? payload.value : [];setAnimals(records as BackendAnimal[]);}catch(error){console.error('DairyOS herd register load failed:',error)}},[]);
 useEffect(()=>{const storedName=localStorage.getItem('dairyos_farm_name');const storedLocation=localStorage.getItem('dairyos_farm_loc');if(storedName)setFarmName(storedName);if(storedLocation)setFarmLocation(storedLocation);void refreshAnimals()},[refreshAnimals]);
 const handleOpenYieldEntry=()=>{setAutoOpenYieldModal(true);setCurrentView('milk')};
 const handleRegisterAnimal=()=>{void refreshAnimals()};
 const handleFarmProfileUpdate=(p:{farmName:string;location:string})=>{setFarmName(p.farmName);setFarmLocation(p.location);localStorage.setItem('dairyos_farm_name',p.farmName);localStorage.setItem('dairyos_farm_loc',p.location)};
 const openPayroll=()=>window.open(`${window.location.origin}${window.location.pathname}?window=payroll`,'DairyOSPayroll','width=1280,height=900,noopener,noreferrer');
 const openLinkedPassport=(id:string)=>setSelectedPassportAnimalId(id);
 const herdMasterList=animals.map(toUiAnimal);
 const navItems=[{id:'dashboard',label:'Dashboard',icon:<LayoutDashboard size={14}/>},{id:'animals',label:'Animals',icon:<Users size={14}/>},{id:'milk',label:'Milk',icon:<Milk size={14}/>},{id:'feed',label:'Feed',icon:<Wheat size={14}/>},{id:'finance',label:'Finance',icon:<DollarSign size={14}/>},{id:'breeding',label:'Breeding',icon:<Activity size={14}/>},{id:'health',label:'Health',icon:<HeartPulse size={14}/>},{id:'coml',label:'COML',icon:<Calculator size={14}/>},{id:'analytics',label:'Analytics',icon:<BarChart3 size={14}/>}];
 const canSettings=true;const canAudit=true;
 if(new URLSearchParams(window.location.search).get('window')==='payroll')return <PayrollWindow/>;
 return <div className="app-shell" style={{display:'flex',flexDirection:'column',height:'100vh',minWidth:0,background:'#0b0f19',color:'#f8fafc',overflow:'hidden',fontFamily:'sans-serif'}}>
  <header style={{height:60,background:'#0f172a',borderBottom:'1px solid #1e293b',display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 12px',zIndex:50,flexShrink:0,boxShadow:'0 4px 6px -1px rgba(0,0,0,.3)',minWidth:0}}>
   <div style={{display:'flex',alignItems:'center',gap:8,flexShrink:0}}><div aria-label="DairyOS cow" title="DairyOS" style={{width:32,height:32,borderRadius:6,background:'#0284c7',display:'flex',alignItems:'center',justifyContent:'center',color:'#fff',fontSize:19,lineHeight:1}} aria-hidden="true">🐄</div><div style={{display:'flex',flexDirection:'column'}}><h1 style={{margin:0,fontSize:13,fontWeight:'bold',whiteSpace:'nowrap'}}>{farmName}</h1><span style={{fontSize:10,color:'#94a3b8',whiteSpace:'nowrap'}}>{farmLocation}</span></div></div>
   <nav style={{display:'flex',gap:6,justifyContent:'center',flex:1,minWidth:0,margin:'0 12px',overflowX:'auto',overflowY:'hidden',scrollbarWidth:'thin'}}>{navItems.map(tab=>{const isActive=currentView===tab.id;const colorMap:Record<string,string>={dashboard:'#3b82f6',animals:'#f59e0b',milk:'#0ea5e9',feed:'#10b981',finance:'#22c55e',breeding:'#f97316',health:'#ef4444',coml:'#a855f7',analytics:'#6366f1'};const themeColor=colorMap[tab.id]||'#94a3b8';return <button key={tab.id} onClick={()=>setCurrentView(tab.id)} style={{display:'flex',alignItems:'center',gap:4,flex:'0 0 auto',background:isActive?`${themeColor}25`:'#1e293b',color:isActive?themeColor:`${themeColor}d9`,border:isActive?`1px solid ${themeColor}`:'1px solid #334155',padding:'6px 10px',borderRadius:6,cursor:'pointer',fontSize:11,fontWeight:isActive?'bold':'600',whiteSpace:'nowrap',transition:'all 0.2s'}}><span style={{color:themeColor,display:'flex',alignItems:'center'}}>{tab.icon}</span>{tab.label}</button>})}</nav>
   <div style={{display:'flex',alignItems:'center',gap:8,flexShrink:0}}><div style={{position:'relative'}}><button onClick={()=>setShowNotifications(!showNotifications)} style={{position:'relative',background:'#1e293b',border:'1px solid #334155',padding:6,borderRadius:'50%',color:'#f59e0b',cursor:'pointer',display:'flex'}}><Bell size={14}/>{activeCount>0&&<span style={{position:'absolute',top:-4,right:-4,minWidth:16,height:16,background:'#ef4444',border:'2px solid #0f172a',borderRadius:'50%',color:'#fff',fontSize:9,fontWeight:'bold',display:'flex',alignItems:'center',justifyContent:'center'}}>{activeCount}</span>}</button>{showNotifications&&<div style={{position:'absolute',right:0,top:40,width:380,maxWidth:'min(380px,calc(100vw - 20px))',background:'#111827',border:'1px solid #1f2937',borderRadius:8,boxShadow:'0 20px 25px -5px rgba(0,0,0,.75)',padding:12,zIndex:100}}><div style={{fontSize:12,fontWeight:'bold',borderBottom:'1px solid #1f2937',paddingBottom:8,marginBottom:8,display:'flex',justifyContent:'space-between',alignItems:'center',gap:8}}><span>Active Warnings ({activeCount})</span>{canAudit&&<button onClick={()=>{setCurrentView('audit');setShowNotifications(false)}} style={{background:'none',border:'none',color:'#38bdf8',fontSize:11,cursor:'pointer',textDecoration:'underline'}}>Open Full Audit Register</button>}</div><div style={{display:'flex',flexDirection:'column',gap:8,maxHeight:340,overflowY:'auto'}}>{alerts.filter(a=>a.status!=='RESOLVED').map(n=><div key={n.id} onClick={()=>canAudit&&setCurrentView('audit')} style={{fontSize:11,background:'#161f30',padding:9,borderRadius:6,cursor:canAudit?'pointer':'default'}}><div style={{color:'#e2e8f0',fontWeight:'bold'}}>{n.title}</div><div style={{fontSize:10,color:'#94a3b8',marginTop:4}}>{n.details}</div></div>)}</div></div>}</div>{currentView==='finance'&&<button onClick={openPayroll} title="Open Finance Payroll" style={{background:'#1e293b',border:'1px solid #334155',padding:6,borderRadius:'50%',color:'#cbd5e1',cursor:'pointer',display:'flex'}}><WalletCards size={14}/></button>}{canSettings&&<button onClick={()=>setCurrentView('settings')} style={{background:currentView==='settings'?'#0ea5e9':'#1e293b',border:currentView==='settings'?'1px solid #7dd3fc':'1px solid #334155',padding:6,borderRadius:'50%',color:'#e2e8f0',cursor:'pointer',display:'flex'}}><Settings size={14}/></button>}</div>
  </header>
  <main style={{flex:1,minHeight:0,minWidth:0,overflowY:'auto',overflowX:'hidden',background:'#0b0f19',position:'relative'}}>
   {currentView==='dashboard'&&<UnifiedDashboard onNavigate={v=>setCurrentView(v)} onOpenYieldModal={handleOpenYieldEntry} onOpenPassport={id=>setSelectedPassportAnimalId(id)} herdMasterList={herdMasterList} realTimeTodayYield={todayYield} realTimeReceivables={accountsReceivable}/>} {currentView==='animals'&&<AnimalTab animals={animals} onOpenPassport={id=>setSelectedPassportAnimalId(id)} onRegister={()=>setShowAnimalModal(true)} onRefresh={refreshAnimals}/>} {currentView==='finance'&&<FinanceTab onSaveSale={liters=>setTodayMilkSoldLiters(prev=>prev+liters)} onUpdateReceivables={setAccountsReceivable}/>} {currentView==='feed'&&<FeedTab/>} {currentView==='coml'&&<COML/>} {currentView==='analytics'&&<><Analytics/><div style={{display:'grid',gap:12,padding:'0 14px 14px'}}><FarmIntelligenceWidget/><DigitalTwinPanel/></div></>} {currentView==='audit'&&<AuditTab/>} {currentView==='settings'&&<SettingsTab onFarmProfileUpdate={handleFarmProfileUpdate}/>} {currentView==='milk'&&<MilkTab initialOpenModal={autoOpenYieldModal} onModalClose={()=>setAutoOpenYieldModal(false)} herdMasterList={herdMasterList} onSaveYield={added=>setTodayYield(prev=>prev+added)} realTimeTodaySold={todayMilkSoldLiters}/>} {currentView==='health'&&<HealthTab onOpenPassport={id=>setSelectedPassportAnimalId(id)} herdMasterList={herdMasterList}/>} {currentView==='breeding'&&<BreedingTab onOpenPassport={id=>setSelectedPassportAnimalId(id)} herdMasterList={herdMasterList}/>} 
  </main>
  {selectedPassportAnimalId&&<AnimalPassportModal animalId={selectedPassportAnimalId} onClose={()=>setSelectedPassportAnimalId(null)} onSave={handleRegisterAnimal} onOpenPassport={openLinkedPassport}/>} {showAnimalModal&&<AnimalPassportModal animalId="NEW-ANIMAL" onClose={()=>setShowAnimalModal(false)} onSave={handleRegisterAnimal} onOpenPassport={openLinkedPassport}/>} 
 </div>
}
