from dataclasses import dataclass


@dataclass
class AutomationEvent:
    """
    Event generated by operational automation.
    """

    event_type: str
    description: str
    executed: bool = False
